using './main.bicep'

param location = 'uaenorth'
param environmentName = 'production-owner-test'
param resourceNamePrefix = 'owner-test'
param appEnvironment = 'PROD'
param syntheticOnly = false
param realDataAllowed = false
param sourceIntakeMode = 'BRIDGE'
param synologyMode = 'BRIDGE'
param azureDirectSynologySmb = false
param storageProvider = 'azure_blob'
param managedArtifactStoreRequired = true
param apiIngressExternal = true
param deriveApiOriginHostName = true
param apiOriginHostName = ''
param edgeCustomDomainName = 'amecidsystem.com'
param apiImage = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_API_IMAGE', 'REQUIRED_AT_DEPLOYMENT')
param workerImage = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_WORKER_IMAGE', 'REQUIRED_AT_DEPLOYMENT')
param migrationImage = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_MIGRATION_IMAGE', 'REQUIRED_AT_DEPLOYMENT')
param frontendImage = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_FRONTEND_IMAGE', 'REQUIRED_AT_DEPLOYMENT')
param frontendOrigin = 'https://amecidsystem.com'
param tenantId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_TENANT_ID', 'REQUIRED_AT_DEPLOYMENT')
param sqlAdministratorObjectId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_SQL_ADMIN_OBJECT_ID', 'REQUIRED_AT_DEPLOYMENT')
param sqlAdministratorLogin = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_SQL_ENTRA_LOGIN', 'REQUIRED_AT_DEPLOYMENT')
param bridgeTenantId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_BRIDGE_TENANT_ID', 'REQUIRED_AT_DEPLOYMENT')
param bridgeClientId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_BRIDGE_CLIENT_ID', 'REQUIRED_AT_DEPLOYMENT')
param bridgeAudience = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_BRIDGE_AUDIENCE', 'REQUIRED_AT_DEPLOYMENT')
param entraApiClientId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_API_CLIENT_ID', 'REQUIRED_AT_DEPLOYMENT')
param entraWebClientId = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_WEB_CLIENT_ID', 'REQUIRED_AT_DEPLOYMENT')
param databaseUrl = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_DATABASE_URL', 'REQUIRED_AT_DEPLOYMENT')
param databaseMigrationUrl = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_DATABASE_MIGRATION_URL', 'REQUIRED_AT_DEPLOYMENT')
param sqlAdministratorPassword = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_SQL_PASSWORD', 'REQUIRED_AT_DEPLOYMENT')
param sqlServerName = 'sql-proposalops-owner-test-uaenorth'
param sqlDatabaseName = 'proposalops-owner-test'
param acrName = 'acrproposalopsowner'
param artifactStorageName = 'stproposalopsownertest'
param aiFeatureEnabled = true
param aiExternalInferenceEnabled = true
param aiRealContentAllowed = false
param aiD4CommissioningId = 'D4-PROPOSAL-OWNER-TEST-20260914'
param aiResourceGroupName = 'rg-proposalops-ai-d3-real-20260908'
param aiAccountName = 'proposalopsd3real20260908'
param aiAzureOpenaiEndpoint = 'https://proposalopsd3real20260908.openai.azure.com/'
param aiD3SyntheticProjectIds = readEnvironmentVariable('PROPOSALOPS_OWNER_TEST_AI_D3_SYNTHETIC_PROJECT_IDS', 'synthetic-proposal')
