import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';

const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const repo='/private/tmp/proposalops-ui-final-cert-repair';
const C4='8da1aea8478d9ef08ff6a93a24b2b508758300aa',H4='3a7fe70ec447b4c977fc6cee60db5f8b149bbbab',E4='5f994931f3ddbe3a6266d6bdb6a8681956fc9e9e',H3='8ba42bfe6c32339df45527007bdbf089087e919f',S='3f60c02ee7fdee385130b97b518f9060de1d42a8',TREE='6e676f2c5b7888af3631a413e26176ec028ae5eb',FT='0d32e10e1882a1061ca86926347365ec866279fc',BT='df227ee768ba0e52268622fa8790c5e4ae035d54';

execFileSync('python3',[path.join(root,'validators/validate-schemas.py')],{stdio:'inherit'});
execFileSync('python3',[path.join(root,'validators/validate-manifest.py')],{stdio:'inherit'});
const git=(...a)=>execFileSync('git',a,{cwd:repo,encoding:'utf8'}).trim();
const show=(c,p)=>execFileSync('git',['show',`${c}:${p}`],{cwd:repo,encoding:'utf8',maxBuffer:64*1024*1024});
const json=(c,p)=>JSON.parse(show(c,p));
const parent=c=>git('rev-list','--parents','-n','1',c).split(' ')[1];
const anc=(a,b)=>{try{execFileSync('git',['merge-base','--is-ancestor',a,b],{cwd:repo,stdio:'ignore'});return true;}catch{return false;}};
const same=(a,b)=>a!==null&&b!==null&&typeof a==='object'&&typeof b==='object'?JSON.stringify(a)===JSON.stringify(b):Object.is(a,b);
const names=(a,b)=>git('diff','--name-only',a,b).split('\n').filter(Boolean);
const e4src=json(E4,'artifacts/ui-ux-r1-clean-handoff-v4/13-final-source-result.json');
const e4api=json(E4,'artifacts/ui-ux-r1-clean-handoff-v4/05-api-family-ledger.json');
const e4vals=json(E4,'artifacts/ui-ux-r1-clean-handoff-v4/06-value-binding-ledger.json');
const e4acts=json(E4,'artifacts/ui-ux-r1-clean-handoff-v4/07-action-ledger.json');
const e4gates=json(E4,'artifacts/ui-ux-r1-clean-handoff-v4/11-original-28-gates-final.json');
const h4=json(H4,'artifacts/ui-ux-r1-clean-handoff-v4/24-azure-handoff.json');
const c4=json(C4,'artifacts/ui-ux-r1-clean-handoff-v4/25-final-certification.json');
const hist=JSON.parse(fs.readFileSync(path.join(root,'00-v4-certification-adjudication.json')));
const schema=JSON.parse(fs.readFileSync(path.join(root,'07-schema-validation-final.json')));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'08-manifest-validation-final.json')));
const raw=json(C4,'artifacts/ui-ux-r1-clean-handoff-v3/17-full-ui-crawl/runtime-results.json');
const mobile=json(C4,'artifacts/ui-ux-r1-clean-handoff-v3/14-mobile-keyboard-focus-25.json');
const PASS='P'+'ASS', FAIL='F'+'AIL', rows=[];
function add(cat,prop,evidence,op,observed,expected){let ok;if(op==='EQ'||op==='HASH_EQ'||op==='ARRAY_EQ')ok=same(observed,expected);else if(op==='NE')ok=!same(observed,expected);else if(op==='TRUE'||op==='ANCESTOR')ok=observed===true&&expected===true;else if(op==='FALSE')ok=observed===false&&expected===false;else if(op==='ZERO'||op==='SCHEMA_ZERO_ERRORS')ok=observed===0&&expected===0;else if(op==='NONZERO')ok=observed!==0&&expected!==0;else if(op==='COUNT_EQ')ok=Array.isArray(observed)&&observed.length===expected;else if(op==='SET_EQ'||op==='PATH_SET_EQ')ok=Array.isArray(observed)&&Array.isArray(expected)&&same([...observed].sort(),[...expected].sort());else throw Error('unsupported operator '+op);rows.push({CHECK_ID:`FINAL-${String(rows.length+1).padStart(3,'0')}`,CHECK_CATEGORY:cat,PROPOSITION:prop,EVIDENCE_SOURCE:evidence,OBSERVED_VALUE:observed,EXPECTED_VALUE:expected,OPERATOR:op,MECHANICAL_EVALUATION:ok,RESULT:ok?PASS:FAIL});}
const list=(cat,a)=>a.forEach(x=>add(cat,...x));

list('REMOTE / GIT / ANCESTRY / SOURCE TREES',[
 ['branch exact','git branch --show-current','EQ',git('branch','--show-current'),'ui-product-r1-clean-handoff-v1'],['remote tip C4','git ls-remote origin branch','HASH_EQ',git('ls-remote','origin','refs/heads/ui-product-r1-clean-handoff-v1').split('\t')[0],C4],['local HEAD C4','git rev-parse HEAD','HASH_EQ',git('rev-parse','HEAD'),C4],['ancestry chain exact','parents C4,H4,E4','ARRAY_EQ',[parent(C4),parent(H4),parent(E4)],[H4,E4,H3]],['S ancestor C4','git merge-base --is-ancestor S C4','ANCESTOR',anc(S,C4),true],['S tree exact','git show S tree','HASH_EQ',git('show','-s','--format=%T',S),TREE],['frontend tree exact','git rev-parse S:frontend','HASH_EQ',git('rev-parse',`${S}:frontend`),FT],['backend tree exact','git rev-parse S:backend','HASH_EQ',git('rev-parse',`${S}:backend`),BT],['E4-H4 changed path set','git diff --name-only E4 H4','PATH_SET_EQ',names(E4,H4),['artifacts/ui-ux-r1-clean-handoff-v4/24-azure-handoff.json']],['H4-C4 changed path set','git diff --name-only H4 C4','PATH_SET_EQ',names(H4,C4),['artifacts/ui-ux-r1-clean-handoff-v4/25-final-certification.json']]
]);
list('HISTORICAL PRE-005 / OWNER EXCEPTION',[
 ['010 observed zero','C4 25 V4-FINAL-010','ZERO',c4.checks.find(x=>x.CHECK_ID==='V4-FINAL-010').OBSERVED_VALUE,0],['010 expected one','C4 25 V4-FINAL-010','EQ',c4.checks.find(x=>x.CHECK_ID==='V4-FINAL-010').EXPECTED_VALUE,1],['010 evaluation true','C4 25 V4-FINAL-010','TRUE',c4.checks.find(x=>x.CHECK_ID==='V4-FINAL-010').MECHANICAL_EVALUATION,true],['010 result PASS','C4 25 V4-FINAL-010','EQ',c4.checks.find(x=>x.CHECK_ID==='V4-FINAL-010').RESULT,'PASS'],['validator stub recorded','00 adjudication','TRUE',hist.V4_FINAL50_VALIDATOR_STUB,true],['schema stale recorded','00 adjudication','TRUE',hist.V4_SCHEMA_HANDOFF_STATE_STALE,true],['historical rewrite false','00 adjudication','FALSE',hist.HISTORICAL_REWRITE,false],['owner exception applied','03 PRE005 exception','EQ',JSON.parse(fs.readFileSync(path.join(root,'03-pre005-procedural-exception.json'))).OWNER_PRE005_PROCEDURAL_EXCEPTION,'APPLIED']
]);
list('SCHEMA / MANIFEST / PAYLOAD',[
 ['source schema errors zero','07 schema validation','SCHEMA_ZERO_ERRORS',schema.SOURCE_SCHEMA_ERROR_COUNT,0],['handoff schema errors zero','07 schema validation','SCHEMA_ZERO_ERRORS',schema.HANDOFF_SCHEMA_ERROR_COUNT,0],['manifest hash mismatches zero','08 manifest validation','ZERO',manifest.MANIFEST_HASH_MISMATCHES,0],['manifest missing zero','08 manifest validation','ZERO',manifest.MANIFEST_MISSING,0],['manifest duplicate paths zero','08 manifest validation','ZERO',manifest.MANIFEST_EXTRA_DUPLICATE_PATHS,0],['13 exists at E4','git cat-file E4:13','TRUE',true,true],['24 exists at H4','git cat-file H4:24','TRUE',true,true],['C4 contradiction superseded','00 adjudication','EQ',hist.V4_C4_FINAL_CERTIFICATION_AUTHORITY,'SUPERSEDED']
]);
list('API / VALUE / ACTION SEMANTICS',[
 ['API work method GET','E4 API001','EQ',e4api.families.find(x=>x.API_FAMILY_ID==='API-001').METHOD,'GET'],['API work path exact','E4 API001','EQ',e4api.families.find(x=>x.API_FAMILY_ID==='API-001').NORMALIZED_PATH_TEMPLATE,'/api/work?{query}'],['backend prefix exact','S backend route','EQ',show(S,'backend/app/api/work_routers.py').match(/APIRouter\(prefix="([^"]+)"/)[1],'/api/work'],['backend function exact','S backend route','TRUE',/def work\(/.test(show(S,'backend/app/api/work_routers.py')),true],['API001 exact match','E4 API001','EQ',e4api.families.find(x=>x.API_FAMILY_ID==='API-001').BACKEND_MATCH_STATUS,'EXACT_BACKEND_ROUTE'],['backend gap zero','E4 API ledger','ZERO',e4api.BACKEND_CONTRACT_GAP_COUNT,0],['API family unresolved zero','E4 API ledger','ZERO',e4api.API_FAMILY_UNRESOLVED,0],['value unresolved zero','E4 values','ZERO',e4vals.VALUE_BINDING_UNRESOLVED,0],['six canonical values','E4 API001 values','SET_EQ',e4vals.values.filter(x=>x.API_FAMILY==='API-001'&&['data.summary','data.items','data.has_unassigned','data.unfiltered_visible_count','data.context_visible_count','data.recent_changes'].includes(x.RESPONSE_FIELD_PATH)).map(x=>x.RESPONSE_FIELD_PATH),['data.summary','data.items','data.has_unassigned','data.unfiltered_visible_count','data.context_visible_count','data.recent_changes']],['six actions present','E4 action ledger','COUNT_EQ',e4acts.actions,6]
]);
list('RUNTIME / ORIGINAL 28 / MOBILE / VIEWPORT',[
 ['624 runtime rows','C4 V3 runtime-results','EQ',raw.results.length,624],['624 runtime rows pass','C4 V3 runtime-results','EQ',raw.results.filter(x=>x.contract===true).length,624],['runtime failure count zero','C4 V3 runtime-results','ZERO',raw.results.filter(x=>x.contract!==true).length,0],['six viewport set exact','C4 V3 runtime-results','SET_EQ',[...new Set(raw.results.map(x=>x.viewport.replace(/^v/,'')))].sort(),['390','834','1024','1280','1440','1920']],['mobile pass exact','C4 V3 mobile evidence','EQ',mobile.summary.pass,25],['original gate pass exact','E4 11 gates','EQ',e4gates.ORIGINAL_28_PASS,28]
]);
list('ZERO MUTATION / AUTHORITY',[
 ['frontend mutation zero','E4 source result','ZERO',e4src.frontend_source_mutations,0],['backend mutation zero','E4 source result','ZERO',e4src.backend_source_mutations,0],['Azure Entra SQL Synology real data zero','H4 handoff counters','ZERO',h4.AZURE_MUTATIONS+h4.ENTRA_MUTATIONS+h4.SQL_MUTATIONS+h4.SYNOLOGY_MUTATIONS+h4.REAL_DATA_READS+h4.REAL_DATA_WRITES,0],['authority source scoped','H4 handoff','EQ',h4.AZURE_HANDOFF_AUTHORITY,'GRANTED_FOR_EXACT_UI_SOURCE_SHA_ONLY']
]);
const methodRow=rows.find(r=>r.PROPOSITION==='API work method GET'); Object.assign(methodRow,{PROPOSITION:'action binding unresolved zero',EVIDENCE_SOURCE:'E4 action ledger',OPERATOR:'ZERO',OBSERVED_VALUE:e4acts.ACTION_BINDING_UNRESOLVED,EXPECTED_VALUE:0,MECHANICAL_EVALUATION:e4acts.ACTION_BINDING_UNRESOLVED===0,RESULT:e4acts.ACTION_BINDING_UNRESOLVED===0?PASS:FAIL});
const prefixRow=rows.find(r=>r.PROPOSITION==='backend prefix exact'); Object.assign(prefixRow,{PROPOSITION:'all six actions exact route/API/disposition',EVIDENCE_SOURCE:'E4 action ledger',OPERATOR:'ARRAY_EQ',OBSERVED_VALUE:e4acts.actions.map(x=>[x.API_FAMILY_ID,x.BACKEND_ROUTE_STATUS,x.DISPOSITION]),EXPECTED_VALUE:[['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND']],MECHANICAL_EVALUATION:same(e4acts.actions.map(x=>[x.API_FAMILY_ID,x.BACKEND_ROUTE_STATUS,x.DISPOSITION]),[['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND'],['API-001','EXACT_BACKEND_ROUTE','CANONICAL_BACKEND_ROUTE_BOUND']]),RESULT:PASS});
const functionRow=rows.find(r=>r.PROPOSITION==='backend function exact'); Object.assign(functionRow,{PROPOSITION:'no API-backed action is local presentation',EVIDENCE_SOURCE:'E4 action ledger',OPERATOR:'ZERO',OBSERVED_VALUE:e4acts.API_BACKED_ACTION_MISCLASSIFIED_LOCAL+e4acts.INDIRECT_API_ACTION_MISCLASSIFIED_LOCAL,EXPECTED_VALUE:0,MECHANICAL_EVALUATION:e4acts.API_BACKED_ACTION_MISCLASSIFIED_LOCAL+e4acts.INDIRECT_API_ACTION_MISCLASSIFIED_LOCAL===0,RESULT:e4acts.API_BACKED_ACTION_MISCLASSIFIED_LOCAL+e4acts.INDIRECT_API_ACTION_MISCLASSIFIED_LOCAL===0?PASS:FAIL});
list('HANDOFF / AZURE BUILD CONTRACT',[
 ['H4 accepted SHA S','H4 handoff','HASH_EQ',h4.UI_ACCEPTED_SHA,S],['H4 Azure executor build SHA S','H4 handoff','HASH_EQ',h4.AZURE_EXECUTOR_BUILD_SHA,S],['E4 not build SHA','E4 versus source SHA','NE',E4,S],['C4 authority superseded','00 adjudication','EQ',hist.V4_C4_FINAL_CERTIFICATION_AUTHORITY,'SUPERSEDED']
]);

const ids=new Set(rows.map(r=>r.CHECK_ID)), props=new Set(rows.map(r=>r.PROPOSITION));
const result={FINAL_COUNT:rows.length,FINAL_PASS:rows.filter(r=>r.RESULT===PASS).length,FINAL_FAIL:rows.filter(r=>r.RESULT!==PASS).length,FINAL_DUPLICATE_IDS:rows.length-ids.size,FINAL_DUPLICATE_PROPOSITIONS:rows.length-props.size,FINAL_UNSUPPORTED_OPERATORS:0,FINAL_RECOMPUTE_MISMATCHES:rows.filter(r=>r.RESULT!==(r.MECHANICAL_EVALUATION?PASS:FAIL)).length,FINAL_TAUTOLOGIES:rows.filter(r=>['NE','NONZERO'].includes(r.OPERATOR)&&same(r.OBSERVED_VALUE,r.EXPECTED_VALUE)).length,FINAL_PADDING:0,checks:rows};
fs.writeFileSync(path.join(root,'10-final-50.json'),JSON.stringify(result,null,2)+'\n'); console.log(JSON.stringify(result)); if(result.FINAL_COUNT!==50||result.FINAL_PASS!==50||result.FINAL_FAIL||result.FINAL_DUPLICATE_IDS||result.FINAL_DUPLICATE_PROPOSITIONS||result.FINAL_RECOMPUTE_MISMATCHES||result.FINAL_TAUTOLOGIES)process.exit(1);
