import type { BillingCapabilityDTO, CommandCenterDTO, WorkItem } from "./billing-types";
import { humanize, MetricCard, money, Panel, PolicyUnresolved, StateMessage } from "./components/BillingPrimitives";

type Props = { capabilities: BillingCapabilityDTO; onOpen: (path: string) => void; onRetry: () => void; data: CommandCenterDTO | null; error: string; loading: boolean };

export function BillingCommandCenter({ capabilities, onOpen, onRetry, data, error, loading }: Props) {
  if (loading && !data) return <StateMessage kind="loading" title="Loading Billing Command Center" detail="Building a bounded operational view from canonical Billing events." />;
  if (error && !data) return <StateMessage kind="error" title="Command Center unavailable" detail={error} onRetry={onRetry} />;
  if (!data) return <StateMessage kind="empty" title="No Billing activity yet" detail="Create a governed Billing Plan and milestone to start the operating queue." />;
  const metric = data.metrics;
  return <div className="billing-page">
    <div className="billing-page-intro"><div><span className="eyebrow">BILLING &amp; FINANCE</span><h2>Command Center</h2><p>Work-first visibility across milestones, invoices, receivables, payment evidence, and collection follow-up.</p></div><span className="billing-source-badge">Canonical records · System insights</span></div>
    <div className="billing-metric-grid"><MetricCard label="Ready to invoice" value={metric.ready_to_invoice} tone={metric.ready_to_invoice ? "default" : "default"} detail="Eligible milestones with remaining invoiceable balance" /><MetricCard label="Draft / review" value={metric.draft_review_required} detail="Human preparation required" /><MetricCard label="Issued outstanding" value={metric.issued_outstanding} detail="Unresolved issued invoices" /><MetricCard label="Overdue" value={metric.overdue} tone={metric.overdue ? "danger" : "default"} detail="Descriptive due-date view" /><MetricCard label="Payments to verify" value={metric.payments_to_verify} tone={metric.payments_to_verify ? "warning" : "default"} detail="Evidence precedes verification" /><MetricCard label="Unallocated client credit" value={metric.unallocated_client_credit} tone={metric.unallocated_client_credit ? "warning" : "default"} detail="Verified money awaiting allocation" /></div>
    <div className="billing-command-grid"><Panel title="Attention queue" eyebrow="WORK FIRST" action={<span className="billing-count">{data.work_items.length} items</span>}><div className="billing-work-list">{data.work_items.length ? data.work_items.slice(0, 12).map((item, index) => <WorkItemRow key={`${item.category}-${index}`} item={item} onOpen={onOpen} />) : <StateMessage kind="empty" title="No attention items" detail="The queue is clear for the records currently available." />}</div></Panel><Panel title="Authority and policy" eyebrow="GOVERNANCE"><div className="billing-authority-callout"><b>Effective server capability</b><p>{capabilities.role} · {capabilities.authority_source}</p><small>Frontend visibility is a projection only. Protected mutations remain server-enforced.</small></div>{data.unresolved_owner_decisions.map((key) => <PolicyUnresolved key={key} label={humanize(key)} />)}<div className="billing-intelligence-callout"><b>Billing Intelligence</b><p>Six governed skills can prepare payment matches, collection drafts, plan interpretations, readiness assessments, invoice reviews, and delivery / acknowledgment extractions for human review.</p><small>AI canonical write authority: ZERO · protected action authority: ZERO · human business action remains separate</small></div></Panel></div>
    <Panel title="Operating views" eyebrow="NAVIGATE"><div className="billing-shortcuts"><button onClick={() => onOpen("/billing/milestones")}>Billing &amp; Milestones</button><button onClick={() => onOpen("/billing/invoices")}>Invoice Register</button><button onClick={() => onOpen("/billing/receivables")}>Open Receivables</button><button onClick={() => onOpen("/billing/payments")}>Payments &amp; Credits</button><button onClick={() => onOpen("/billing/reports")}>Reports</button></div></Panel>
  </div>;
}

function WorkItemRow({ item, onOpen }: { item: WorkItem; onOpen: (path: string) => void }) {
  const entity = item.entity as { id?: unknown; invoice_id?: unknown; name?: unknown; invoice_reference?: unknown; payment?: { id?: unknown }; context?: unknown };
  const destination = item.target?.route;
  return <article className="billing-work-item"><div className="billing-work-item-main"><span className="billing-category">{humanize(item.category)}</span><b>{String(entity.context && typeof entity.context === "object" ? ((entity.context as { project?: { name?: string } }).project?.name || "Billing record") : entity.name || entity.invoice_reference || "Billing record")}</b><p>{item.why}</p><small>Authority: {item.authority_needed}</small></div>{destination ? <button className="button-secondary" onClick={() => onOpen(destination)}>{item.next_action}</button> : <span className="muted">Target unavailable</span>}</article>;
}
