import { useState } from "react";
import { api } from "../api";
import { Icon } from "../Icon";
import { billingApi } from "./billing-api";
import type { BillingCapabilityDTO, InvoiceDetailDTO } from "./billing-types";
import { humanize, money, Panel, PolicyUnresolved, StateMessage, StatusSet, TechnicalDetails } from "./components/BillingPrimitives";

export function InvoiceWorkspace({ detail, capabilities, onBack, onRefresh }: { detail: InvoiceDetailDTO; capabilities: BillingCapabilityDTO; onBack: () => void; onRefresh: () => void }) {
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [cloneOpen, setCloneOpen] = useState(false);
  const [periodStart, setPeriodStart] = useState("");
  const [periodEnd, setPeriodEnd] = useState("");
  const invoice = detail.invoice;
  const revision = detail.revision;
  const client = detail.client as { display_name?: unknown; client_reference?: unknown } | null | undefined;
  const project = detail.project as { project_name?: unknown; project_code?: unknown; project_number?: unknown } | null | undefined;
  const contract = detail.contract as { contract_name?: unknown; contract_reference?: unknown } | null | undefined;
  const execute = async (path: string, payload: Record<string, unknown>, success: string) => { setBusy(true); setMessage(""); try { await api(path, { method: "POST", body: JSON.stringify(payload) }); setMessage(success); onRefresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Action could not be recorded."); } finally { setBusy(false); } };
  const accept = () => execute(`/api/billing/invoice-revisions/${revision.id}/accept`, { invoice_id: invoice.id, idempotency_key: `ui-accept-${revision.id}` }, "Invoice accepted. Issue remains a separate human action.");
  const issue = () => execute(`/api/billing/invoice-revisions/${revision.id}/issue`, { idempotency_key: `ui-issue-${revision.id}` }, "Invoice issued. Delivery and acknowledgment remain separate evidence events.");
  const clone = async () => { await execute(`/api/billing/invoices/${invoice.id}/clone`, { service_period_start: periodStart, service_period_end: periodEnd, service_period_label: `${periodStart} – ${periodEnd}`, idempotency_key: `ui-clone-${invoice.id}-${periodStart}-${periodEnd}` }, "New draft cloned. No lifecycle, payment, or collection evidence was copied."); setCloneOpen(false); };
  if (!detail) return <StateMessage kind="empty" title="Invoice not found" detail="This invoice is not available in the current Billing scope." />;
  return <div className="billing-page"><button className="text-button" onClick={onBack}><Icon name="arrow-left" size={14} /> Invoice Register</button><div className="billing-page-intro"><div><span className="eyebrow">INVOICE WORKSPACE</span><h2>{invoice.invoice_reference}</h2><p>{String(contract?.contract_name || contract?.contract_reference || "Contract context unavailable")} · {String(project?.project_name || project?.project_code || "Project context unavailable")}</p></div><span className="billing-source-badge">{humanize(invoice.status)}</span></div><div className="billing-identity-grid"><div><small>Global Invoice Reference</small><b>{invoice.invoice_reference}</b></div><div><small>Project Invoice #</small><b>{invoice.project_invoice_ordinal ?? "Reserved on Issue"}</b></div><div><small>Client</small><b>{String(client?.display_name || "Client unavailable")}</b></div><div><small>Invoice amount</small><b>{money(revision.payable_total, String(revision.currency || ""))}</b></div><div><small>Outstanding</small><b>{money(detail.receivable.outstanding_amount, String(revision.currency || ""))}</b></div><div><small>Service period</small><b>{String(revision.service_period_label || "Not structured")}</b></div></div><StatusSet items={[["Invoice", invoice.status], ["Communication", detail.communications.state], ["Receivable", detail.receivable.state], ["Payment", detail.receivable.verified_paid_amount !== "0.00" ? "VERIFIED_PAYMENT" : "NONE"], ["Resolution", detail.receivable.resolved_non_cash_amount !== "0.00" ? "NON_CASH" : "NONE"]]} />
    <div className="billing-tab-strip" role="tablist" aria-label="Invoice sections"><a href="#overview">Overview</a><a href="#lines">Lines &amp; Milestones</a><a href="#preflight">Preflight</a><a href="#communication">Delivery &amp; Acknowledgment</a><a href="#payments">Payments</a><a href="#collections">Collections</a><a href="#activity">Evidence &amp; Activity</a></div>
    <div className="billing-workspace-grid"><Panel title="Overview" eyebrow="COMMERCIAL CONTEXT"><div className="billing-detail-list"><div><span>Contract</span><b>{String(contract?.contract_reference || "Unavailable")}</b></div><div><span>Project</span><b>{String(project?.project_name || project?.project_number || "Unavailable")}</b></div><div><span>Invoice date</span><b>{String(revision.invoice_date || "Not recorded")}</b></div><div><span>Due date</span><b>{String(revision.due_date || "Awaiting configured/verified event")}</b></div></div>{detail.artifact && <a className="button-primary" href={`/api/billing/invoices/${invoice.id}/download`} target="_blank" rel="noreferrer">Download issued PDF</a>}<TechnicalDetails><code>invoice_id={invoice.id}</code><code>revision_id={revision.id}</code><code>client_account_id={invoice.client_account_id || "—"}</code></TechnicalDetails></Panel><Panel title="Human lifecycle" eyebrow="PROTECTED ACTIONS"><p>Accept and Issue are deliberately separate. Issuing does not send the Invoice externally or settle accounting.</p><div className="billing-actions"><button className="button-secondary" title={detail.precheck.result !== "PASS" ? "Resolve every preflight blocker first" : undefined} disabled={busy || !capabilities.capabilities.can_accept_invoice || revision.status !== "DRAFT" || detail.precheck.result !== "PASS"} onClick={() => void accept()}>Accept draft</button><button className="button-primary" title={detail.precheck.result !== "PASS" ? "Resolve every preflight blocker first" : undefined} disabled={busy || !capabilities.capabilities.can_issue_invoice || revision.status !== "ACCEPTED_INTERNAL" || detail.precheck.result !== "PASS"} onClick={() => void issue()}>Issue invoice</button><button className="button-secondary" disabled={busy || !capabilities.capabilities.can_create_invoice} onClick={() => setCloneOpen((value) => !value)}>Clone previous invoice</button></div><small className="billing-action-help">{detail.precheck.result !== "PASS" ? "Protected actions are disabled until every deterministic preflight blocker is resolved." : revision.status === "DRAFT" ? "Accept is available after the preflight is clear." : revision.status === "ACCEPTED_INTERNAL" ? "Issue is available to an authorized human after preflight." : "Lifecycle actions are controlled by the canonical state."}</small>{message && <div className="billing-message" role="status">{message}</div>}{cloneOpen && <div className="billing-inline-form"><b>New structured service period</b><label>Start <input type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /></label><label>End <input type="date" value={periodEnd} onChange={(event) => setPeriodEnd(event.target.value)} /></label><button className="button-secondary" disabled={!periodStart || !periodEnd} onClick={() => void clone()}>Create new Draft</button></div>}</Panel></div>
    <Panel title="Lines & Milestones" eyebrow="CANONICAL LEDGER"><div className="billing-line-list">{detail.lines.map((line) => <div className="billing-line" key={line.id}><div><b>{line.description}</b><small>{String(line.line_role || "Charge")} · milestone {String(line.billing_milestone_id || "not linked")}</small></div><b>{money(line.calculated_line_amount, line.currency)}</b></div>)}</div></Panel>
    <Panel title="Preflight" eyebrow="BEFORE ACCEPT / ISSUE"><div className="billing-precheck-list">{detail.precheck.checks.map((check) => <div className="billing-precheck-row" key={check.code}><span className={check.status === "PASS" ? "billing-check-pass" : "billing-check-blocked"}>{check.status === "PASS" ? "✓" : "!"}</span><div><b>{humanize(check.code)}</b><p>{check.reason}</p></div></div>)}</div><small>Preflight is read-only and uses the same backend logic that protects Accept and Issue.</small></Panel>
    <Panel title="Delivery & Acknowledgment" eyebrow="COMMUNICATION EVIDENCE"><div className="billing-event-columns"><EventColumn title="Issued" events={detail.issue ? [detail.issue] : []} /><EventColumn title="Delivered" events={detail.communications.deliveries} /><EventColumn title="Acknowledged" events={detail.communications.acknowledgments} /></div><div className="billing-note"><b>State separation</b><span>Issued ≠ Delivered ≠ Acknowledged ≠ Paid. Each event requires its own evidence-backed record.</span></div></Panel>
    <div className="billing-workspace-grid"><Panel title="Payments" eyebrow="VERIFICATION / ALLOCATION"><p>Verified paid: {money(detail.receivable.verified_paid_amount, String(revision.currency || ""))} · Outstanding: {money(detail.receivable.outstanding_amount, String(revision.currency || ""))}</p>{detail.allocations.length ? detail.allocations.map((allocation, index) => <div className="billing-history-row" key={String(allocation.id || index)}><b>Allocated</b><span>{String(allocation.allocated_amount || "—")} {String(allocation.currency || revision.currency || "")}</span></div>) : <p className="muted">No verified allocation events recorded.</p>}</Panel><Panel title="Collections" eyebrow="FOLLOW-UP / RESOLUTION"><p>Follow-up changes collection work, not financial state. Non-cash resolution remains distinct from payment.</p>{detail.follow_ups.length ? detail.follow_ups.map((followUp, index) => <div className="billing-history-row" key={String(followUp.id || index)}><b>{String(followUp.channel || "Follow-up")}</b><span>{String(followUp.note || "No note")}</span></div>) : <p className="muted">No follow-up recorded.</p>}{detail.resolutions.map((resolution, index) => <div className="billing-history-row" key={String(resolution.id || index)}><b>Non-cash · {humanize(resolution.resolution_type)}</b><span>{String(resolution.amount || "—")} {String(resolution.currency || "")}</span></div>)}</Panel></div>
    <Panel title="Evidence & Activity" eyebrow="AUDIT / LINEAGE"><div className="billing-history-row"><b>Invoice draft created</b><span>{String(revision.created_at || "Recorded in canonical audit")}</span></div>{detail.issue && <div className="billing-history-row"><b>Issued PDF artifact</b><span>{String(detail.issue.official_invoice_ref || invoice.invoice_reference)} · template {String(detail.issue.template_version_id || "—")} · financial account {String(detail.issue.financial_account_version_id || "—")}</span></div>}{(detail as unknown as { references?: Array<Record<string, unknown>> }).references?.map((item, index) => <div className="billing-history-row" key={`reference-${index}`}><b>Reference · {String(item.reference_type || "")}</b><span>{String(item.value || "")} · {String(item.status || "")}</span></div>)}{(detail as unknown as { approvals?: Array<Record<string, unknown>> }).approvals?.map((item, index) => <div className="billing-history-row" key={`approval-${index}`}><b>Approval · {String(item.approval_type || "")}</b><span>{String(item.status || "")} · {String(item.approval_reference || "No reference")}</span></div>)}{detail.communications.deliveries.map((event, index) => <div className="billing-history-row" key={`delivery-${index}`}><b>Invoice delivered</b><span>{String(event.delivered_at || "Recorded")} · {String(event.channel || "channel unavailable")}</span></div>)}{detail.communications.acknowledgments.map((event, index) => <div className="billing-history-row" key={`ack-${index}`}><b>Acknowledgment recorded</b><span>{String(event.acknowledged_at || "Recorded")}</span></div>)}</Panel>
    {capabilities.unresolved_owner_decisions.map((item) => <PolicyUnresolved key={item.key} label={item.label} detail="The workspace does not fabricate a value or enable a protected operation from this unresolved policy." />)}
  </div>;
}

function EventColumn({ title, events }: { title: string; events: Array<Record<string, unknown>> }) { return <div className="billing-event-column"><h4>{title}</h4>{events.length ? events.map((event, index) => <div className="billing-event" key={String(event.id || index)}><b>{String(event.channel || event.status || "Recorded")}</b><small>{String(event.delivered_at || event.acknowledged_at || event.issued_at || "Timestamp unavailable")}</small><span>{String(event.delivery_reference || event.acknowledgment_reference || event.official_invoice_ref || "Evidence reference unavailable")}</span></div>) : <p className="muted">Not recorded</p>}</div>; }
