import { ReactNode, useMemo, useState } from "react";
import "./about.css";
import { AppLocale, useLocale } from "./i18n";

export type AboutStatus = "IMPLEMENTED" | "IMPLEMENTED_PROTOTYPE" | "FOUNDATION_ONLY" | "PLANNED_PENDING_SCOPE" | "EXCLUDED" | "NOT_APPLICABLE";

export function LtrTerm({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <bdi dir="ltr" className={`inline-ltr-term ${className}`.trim()}>{children}</bdi>;
}

/** Tokenizes plain mixed-direction copy so Arabic strings cannot create an unisolated Latin run. */
function BidiText({ children }: { children: ReactNode }) {
  if (typeof children !== "string") return <>{children}</>;
  const parts = children.split(/([A-Za-z][A-Za-z0-9]*(?:[ /_-][A-Za-z0-9]+)*)/g);
  return <>{parts.map((part, index) => /[A-Za-z]/.test(part) ? <LtrTerm key={`${part}-${index}`}>{part}</LtrTerm> : part)}</>;
}

const ar = {
  product: <LtrTerm>PermitOps</LtrTerm>,
  amec: <LtrTerm>AMEC</LtrTerm>,
  mvp: <LtrTerm>MVP</LtrTerm>,
  excel: <LtrTerm>Excel</LtrTerm>,
  synology: <LtrTerm>Synology</LtrTerm>,
  portal: <LtrTerm>Municipality Portal</LtrTerm>,
  workflow: <LtrTerm>Workflow</LtrTerm>,
  forms: <LtrTerm>Forms</LtrTerm>,
  package: <LtrTerm>Package</LtrTerm>,
  revision: <LtrTerm>Revision</LtrTerm>,
  precheck: <LtrTerm>Authority AI Precheck</LtrTerm>,
  readback: <LtrTerm>Read-back</LtrTerm>,
  stale: <LtrTerm>Stale</LtrTerm>,
  myWork: <LtrTerm>My Work</LtrTerm>,
  submit: <LtrTerm>Final Submit</LtrTerm>,
  evidence: <LtrTerm>Evidence</LtrTerm>,
  finding: <LtrTerm>Finding</LtrTerm>,
  rbac: <LtrTerm>RBAC</LtrTerm>,
  mfa: <LtrTerm>MFA</LtrTerm>,
};

type Feature = {
  id: string;
  group: string;
  en: { title: string; description: string };
  ar: { title: ReactNode; description: ReactNode };
  status: AboutStatus;
  evidence: string[];
  route?: string;
};

const features: Feature[] = [
  { id: "project-onboarding", group: "Project & source control", en: { title: "Project onboarding", description: "Connect a project to its identity, source locations, Excel context, and Municipality application." }, ar: { title: "تجهيز المشروع", description: <>بنربط المشروع ببياناته ومصادره و{ar.excel} وطلب البلدية.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Project model", "Project register", "canonical fixture"], route: "/permits" },
  { id: "source-linkage", group: "Project & source control", en: { title: "Synology and source linkage", description: "Keep controlled links to project folders and source locations without making them the system of record." }, ar: { title: <>ربط مصادر {ar.synology}</>, description: <>بنحافظ على روابط واضحة ومتحكم فيها لمجلدات المشروع ومصادر البيانات.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["ExternalSystemLink", "Synology adapter", "fixture check"] },
  { id: "document-registry", group: "Project & source control", en: { title: "Document registry and versions", description: "Register the logical document, revisions, and content hashes so the exact source version is known." }, ar: { title: "سجل المستندات والنسخ", description: <>النظام بيسجل المستند نفسه وكل {<LtrTerm>Version</LtrTerm>} ومعاه {<LtrTerm>Hash</LtrTerm>}.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Document/DocumentVersion", "Week 2 tests", "document API"] },
  { id: "ownership", group: "Project & source control", en: { title: "Owners, shares, and representation", description: "Represent multiple owners, ownership shares, and authorized representatives when the permit requires them." }, ar: { title: "المالكين ونِسَب الملكية", description: "النظام يقدر يتعامل مع أكتر من مالك والممثل أو التوكيل المعتمد." }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["PropertyOwnership", "Representation", "forms API"] },
  { id: "classification", group: "Document intelligence & verified data", en: { title: "Document classification", description: "Classify incoming documents into the controlled types needed by the workflow." }, ar: { title: "تصنيف المستندات", description: <>النظام بيصنّف المستندات حسب أنواع المستندات اللي {ar.workflow} محتاجها.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["document_intelligence", "classification endpoint", "Week 2 tests"] },
  { id: "extraction", group: "Document intelligence & verified data", en: { title: "Critical data extraction", description: "Extract permit-critical information with evidence and an explicit confidence state." }, ar: { title: "استخراج البيانات المهمة", description: <>بيستخرج البيانات ومع كل معلومة بيحتفظ بـ{ar.evidence} وحالة الثقة.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["FieldObservation", "extraction endpoint", "Golden Path v1"] },
  { id: "keyed-fallback", group: "Document intelligence & verified data", en: { title: "Controlled keyed-entry fallback", description: "When a document is not readable reliably, the workflow can require controlled human entry." }, ar: { title: "إدخال بشري متحكم فيه", description: "لو المستند مش واضح كفاية، النظام يطلب إدخال بشري بدل ما يفترض إن الاستخراج صحيح." }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["manual-observations API", "MANUAL_KEYED", "Week 2 tests"] },
  { id: "conflicts", group: "Document intelligence & verified data", en: { title: "Conflicts and human verification", description: "Compare sources, surface material inconsistencies, and let an authorized person confirm the value used by the workflow." }, ar: { title: "التعارضات والمراجعة البشرية", description: <>النظام بيقارن المصادر ويطلع التعارض، والشخص المخوّل بيثبت القيمة اللي {ar.workflow} هيكمل بيها.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Conflict", "VerifiedAssertion", "conflict API"], route: "/permits" },
  { id: "lineage", group: "Document intelligence & verified data", en: { title: "Verified facts and lineage", description: "Accepted facts are attributable, versioned, and traceable back to their source evidence." }, ar: { title: "البيانات المتراجعة والتتبّع", description: <>المعلومة المعتمدة معروف مين راجعها وممكن نرجع لـ{ar.evidence} اللي بتثبتها.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["VerifiedAssertion", "LineageEdge", "Lineage & validity console"], route: "/admin/lineage" },
  { id: "requirements", group: "Requirements, validity & readiness", en: { title: "Requirement evaluation", description: "Determine required, conditional, optional, human-decision, and not-applicable items for the permit scenario." }, ar: { title: "تقييم المتطلبات", description: <>النظام بيحدد إيه المطلوب وإيه المشروط وإيه محتاج قرار بشري.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["RequirementConfig", "requirements API", "Week 4–5 tests"], route: "/permits" },
  { id: "validity", group: "Requirements, validity & readiness", en: { title: "Validity and expiry", description: "Identify missing, expired, revoked, replaced, or otherwise invalid evidence." }, ar: { title: "الصلاحية والانتهاء", description: <>بيحدد الـ{<LtrTerm>Evidence</LtrTerm>} الناقص أو المنتهي أو اللي اتبدل وبقى غير صالح.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["ValidityRecord", "week8 service", "Week 8 tests"] },
  { id: "drawings", group: "Requirements, validity & readiness", en: { title: "Drawing metadata controls", description: "Run deterministic checks on configured drawing metadata and show PASS, FAIL, or NEEDS REVIEW." }, ar: { title: "ضوابط بيانات الرسومات", description: <>بيعمل {<LtrTerm>Checks</LtrTerm>} متفق عليها ويطلع {<LtrTerm>PASS</LtrTerm>} أو {<LtrTerm>FAIL</LtrTerm>} أو {<LtrTerm>NEEDS REVIEW</LtrTerm>}.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["DrawingMetadataControl", "control diagnostics", "acceptance rehearsal"] },
  { id: "readiness", group: "Requirements, validity & readiness", en: { title: "Package readiness", description: "Show whether the package is ready and list exact blockers, owners, and next actions." }, ar: { title: <>جاهزية الـ{ar.package}</>, description: <>شاشة الـ{<LtrTerm>Readiness</LtrTerm>} بتوضح الـ{<LtrTerm>Blockers</LtrTerm>} ومين مسؤول وإيه الخطوة اللي بعدها.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["evaluate_readiness", "PackageReadinessPage", "Golden Path v2"], route: "/permits" },
  { id: "human-gates", group: "Requirements, validity & readiness", en: { title: "Internal review and package approval", description: "Bind approval to the exact current package, source versions, and controlled state." }, ar: { title: "المراجعة واعتماد الـPackage", description: <>اعتماد الـ{ar.package} بيتربط بالنسخة الحالية وبالـ{<LtrTerm>Versions</LtrTerm>} اللي اتراجعت.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Approval", "package approval endpoint", "Week 10 gate"] },
  { id: "forms", group: "Forms, Excel & package control", en: { title: "Forms from verified facts", description: "Generate agreed forms from verified project information instead of retyping the same facts." }, ar: { title: <>تجهيز الـ{ar.forms} من البيانات المتراجعة</>, description: <>الـ{ar.forms} بتتجهز من بيانات المشروع اللي اتراجعت.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["RenderedForm", "render form API", "Week 4–5 tests"] },
  { id: "excel", group: "Forms, Excel & package control", en: { title: "Controlled Excel projection", description: "Update system-owned Excel fields from governed project state while preserving human-owned areas." }, ar: { title: <>إسقاط متحكم فيه على {ar.excel}</>, description: <>بيحدّث الخانات اللي النظام مسؤول عنها من غير ما يكتب فوق خانات المستخدم.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["ExcelProjection", "MockExcelAdapter", "canonical workbook"] },
  { id: "manifest", group: "Forms, Excel & package control", en: { title: "Exact package manifest", description: "Lock the document versions, hashes, categories, and approvals used in the current package." }, ar: { title: <>سجل محتويات الـ{ar.package}</>, description: <>الـ{<LtrTerm>Manifest</LtrTerm>} بيسجل بالضبط أنهي نسخ وتصنيفات وموافقات موجودة.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Package/AttachmentManifest", "manifest API", "Week 9 tests"] },
  { id: "attachments-grids", group: "Forms, Excel & package control", en: { title: "Attachment and repeating-grid control", description: "Map the right document versions to categories and validate supported Municipality rows and persistence." }, ar: { title: "ضبط المرفقات والـGrids", description: <>بيربط نسخ المستندات الصح، ويراجع الـ{<LtrTerm>Grids</LtrTerm>} والصفوف لما الـPortal يسمح.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["attachment manifest", "grid reconciliation", "Week 9 tests"], route: "/admin/attachments-grids" },
  { id: "interaction-modes", group: "Municipality preparation & reconciliation", en: { title: "Approved interaction modes", description: "Support the bounded Municipality path: simulator/API-style data, controlled preparation, or assisted human entry." }, ar: { title: "طرق التعامل المعتمدة", description: <>النظام يشتغل بالطريقة المعتمدة: {<LtrTerm>API</LtrTerm>} أو {<LtrTerm>Portal Pack</LtrTerm>} متحكم فيه أو إدخال بشري مساعد.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["MockMunicipalityAdapter", "MunicipalityPreparationPage", "no-write boundary"] },
  { id: "reconciliation", group: "Municipality preparation & reconciliation", en: { title: "Pre-write reconciliation and read-back", description: "Compare intended preparation with external state, then read back what the portal actually persisted." }, ar: { title: <>المقارنة قبل الكتابة والـ{ar.readback}</>, description: <>بيقارن الحالة المقصودة بالحالة الخارجية ويرجع يقرأ الـ{ar.portal} حفظ إيه فعلاً.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["portal snapshots", "reconciliation API", "Week 9 tests"] },
  { id: "takeover", group: "Municipality preparation & reconciliation", en: { title: "Safe human takeover", description: "Require external-state reconciliation before a controlled assisted workflow resumes." }, ar: { title: "تسلّم بشري آمن", description: "لو المستخدم استلم الخطوة بنفسه، الحالة الخارجية لازم تتراجع قبل ما الشغل يكمل." }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["attended session metadata", "takeover contract", "Week 11–12 evidence"] },
  { id: "precheck", group: "Authority review, submission & findings", en: { title: "Authority AI precheck capture", description: "Capture supported precheck results against the exact preparation revision." }, ar: { title: <>تسجيل {ar.precheck}</>, description: <>النظام بيسجل نتيجة الـ{ar.precheck} ويربطها بالـ{<LtrTerm>Preparation Revision</LtrTerm>} الصح.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["precheck capture", "ingest_precheck_findings", "Golden Path v2"] },
  { id: "findings", group: "Authority review, submission & findings", en: { title: "Findings, ownership, and closure evidence", description: "Turn authority or precheck comments into owned Findings with evidence, tasks, notifications, and controlled resolution." }, ar: { title: <>الـ{ar.finding} والمسؤولية وEvidence الإغلاق</>, description: <>الملاحظات بتتحول لـ{ar.finding} عليها مسؤول و{ar.evidence} وخطوة متابعة.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Finding/WorkflowTask/NotificationEvent", "Findings Console", "Week 7 tests"], route: "/issues" },
  { id: "human-submit", group: "Authority review, submission & findings", en: { title: "Human final submission boundary", description: "Prepare the final handoff while keeping the actual Municipality Submit action with an authorized human." }, ar: { title: <>التقديم النهائي بشري</>, description: <>الـ{ar.submit} للبلدية بيفضل مع شخص مخوّل؛ مفيش زرار تقديم آلي.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["SubmissionHandoff", "FINAL_SUBMITTER role", "zero machine-submit counter"] },
  { id: "monitoring", group: "Work management, monitoring & history", en: { title: "Status monitoring and no-change evidence", description: "Record supported monitoring checks and distinguish a real authority change from a no-change check." }, ar: { title: "متابعة الحالة وتسجيل عدم التغيير", description: <>بيسجل الـ{<LtrTerm>Monitoring</LtrTerm>} ويفرق بين تغيير حقيقي و{<LtrTerm>NO_CHANGE</LtrTerm>}.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["MonitoringRun", "PortalReadContract", "Week 11 tests"] },
  { id: "my-work", group: "Work management, monitoring & history", en: { title: "My Work and deterministic next action", description: "Show what needs attention, why it is blocked, who owns it, and what should happen next." }, ar: { title: <>الـ{ar.myWork} والخطوة اللي بعدها</>, description: <>بيوضح الشغل اللي محتاج تدخل، وليه واقف، ومين مسؤول عن الخطوة اللي بعدها.</> }, status: "IMPLEMENTED", evidence: ["MyWorkPage", "projectNextAction", "workflow-first tests"], route: "/work" },
  { id: "history", group: "Work management, monitoring & history", en: { title: "History, audit, lineage, and staleness", description: "Reconstruct versions, approvals, packages, authority interactions, findings, decisions, and material changes." }, ar: { title: "التاريخ والتدقيق والتتبّع", description: <>من الـ{<LtrTerm>History</LtrTerm>} نقدر نرجع للنسخ والموافقات والـ{ar.package} والـ{ar.finding}، ونعرف إمتى الـOutput بقى {ar.stale}.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["AuditEvent", "LineageEdge", "MaterialChangeEvent", "Week 8–14 tests"] },
  { id: "rbac", group: "Security, role & operational safety", en: { title: "Role-based access control", description: "Restrict actions according to role and authority, including preparer, verifier, approver, and final submitter separation." }, ar: { title: <>الصلاحيات حسب الـ{ar.rbac}</>, description: <>الصلاحيات والإجراءات بتتحدد حسب الـ{<LtrTerm>Role</LtrTerm>} والسلطة الفعلية.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["Role enum", "role selector", "role readiness matrix"] },
  { id: "mfa", group: "Security, role & operational safety", en: { title: "Attended authentication and MFA boundary", description: "Support attended sessions without storing OTPs as reusable credentials." }, ar: { title: <>التوثيق بحضور المستخدم و{ar.mfa}</>, description: <>بيتعامل مع الـ{ar.mfa} والـ{<LtrTerm>OTP</LtrTerm>} في Session بحضور المستخدم من غير تخزين Credentials.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["MFA session contract", "attended-session metadata", "safety counters"] },
  { id: "fail-closed", group: "Security, role & operational safety", en: { title: "Fail-closed behavior and environment separation", description: "When a consequential check cannot be proven, stop or require human action; keep synthetic and production boundaries explicit." }, ar: { title: "التوقف الآمن والفصل بين البيئات", description: "لو Check مهم ماقدرناش نثبته، النظام يقف أو يطلب تدخل شخص بدل ما يخمّن." }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["safe boundary banner", "G10 counters", "production decision evidence"] },
  { id: "four-assistants", group: "Broader AMEC vision", en: { title: "Four assistant operating model", description: "Shared task context and bounded assistant handoffs are present as a synthetic prototype; the expanded business workflows are not all complete." }, ar: { title: "نموذج الأربع مساعدات", description: <>فيه {<LtrTerm>Shared Queue</LtrTerm>} وتحويلات متحكم فيها في بيئة تجريبية، لكن مش كل الـWorkflows الموسعة مكتملة.</> }, status: "IMPLEMENTED_PROTOTYPE", evidence: ["UnifiedMyWorkPanel", "expansion/unified.py", "E7/E8 acceptance"], route: "/work" },
  { id: "expansion-foundation", group: "Broader AMEC vision", en: { title: "RFQ, quotation, contract, finance, and handover foundation", description: "Shared models, evidence, templates, and bounded APIs exist, but they do not constitute complete quotation, contract execution, invoice, or handover workflows." }, ar: { title: "أساس دورة AMEC الأوسع", description: <>فيه أساس للـ{<LtrTerm>RFQ</LtrTerm>} والـ{<LtrTerm>Quotation</LtrTerm>} والـ{<LtrTerm>Contract</LtrTerm>} والـ{<LtrTerm>Invoice</LtrTerm>} والـ{<LtrTerm>Handover</LtrTerm>}، لكن الـWorkflow الكامل لسه مش مكتمل.</> }, status: "FOUNDATION_ONLY", evidence: ["expansion_entities.py", "ExpansionFoundation", "E1 evidence"], route: "/admin/expansion-foundation" },
  { id: "live-authority", group: "Safety boundaries", en: { title: "Live Municipality submission", description: "Production authority writes, machine final submission, payments, signing, and certification are not authorized in this environment." }, ar: { title: "التقديم الحي للبلدية", description: <>التعامل الحي، والـ{ar.submit} الآلي، والدفع والتوقيع والشهادة مش متاحين في الـEnvironment الحالية.</> }, status: "EXCLUDED", evidence: ["README safety boundary", "G10 formal decision", "zero-tolerance counters"] },
];

const statusLabels: Record<AboutStatus, { en: string; ar: string }> = {
  IMPLEMENTED: { en: "Implemented", ar: "موجود" },
  IMPLEMENTED_PROTOTYPE: { en: "Implemented in prototype", ar: "موجود في الـPrototype" },
  FOUNDATION_ONLY: { en: "Foundation only", ar: "أساس فقط" },
  PLANNED_PENDING_SCOPE: { en: "Planned / pending scope", ar: "مخطط / لسه محتاج تحديد" },
  EXCLUDED: { en: "Not available here", ar: "مش متاح هنا" },
  NOT_APPLICABLE: { en: "Not applicable", ar: "مش منطبق" },
};

const lifecycle = [
  { en: ["Project & Sources", "Connect project identity, documents, Synology, Excel, drawings, and the Municipality application."], ar: [<>المشروع والمصادر</>, <>بنربط بيانات المشروع والمستندات و{ar.synology} و{ar.excel} والرسومات وطلب البلدية.</>] },
  { en: ["Verify Data", "Compare sources, surface conflicts, and let the right person confirm the facts used by the permit."], ar: [<>مراجعة البيانات</>, <>بنقارن المصادر ونوضح التعارض، وبعدها الشخص المخوّل يثبت البيانات.</>] },
  { en: ["Prepare Package", "Evaluate requirements, validity, drawings, forms, Excel, attachments, and readiness."], ar: [<>تجهيز الـPackage</>, <>بنراجع الـRequirements والـ{ar.forms} والصلاحية والرسومات والمرفقات.</>] },
  { en: ["Municipality Preparation", "Prepare fields, dropdowns, grids, and attachments through the approved interaction mode, then verify saved state."], ar: [<>تجهيز البلدية</>, <>بنجهز الـ{<LtrTerm>Fields</LtrTerm>} والـ{<LtrTerm>Dropdowns</LtrTerm>} والـ{<LtrTerm>Grids</LtrTerm>}، وبعدها نتأكد الـ{ar.portal} حفظ إيه.</>] },
  { en: ["Final Review & Human Submit", "Run final readiness checks and prepare the handoff. An authorized human performs the final submission."], ar: [<>المراجعة النهائية والتقديم البشري</>, <>بنعمل آخر مراجعة ونجهز الـ{<LtrTerm>Handoff</LtrTerm>}، لكن الـ{ar.submit} بيعمله شخص مخوّل.</>] },
  { en: ["Authority Review", "Track submission confirmation, authority status, supported precheck information, and official comments."], ar: [<>مراجعة الجهة</>, <>بنتابع حالة الطلب وأي {<LtrTerm>Precheck</LtrTerm>} متاح والـ{<LtrTerm>Comments</LtrTerm>} الرسمية.</>] },
  { en: ["Comments & Corrections", "Turn comments into owned Findings, track evidence and corrections, and create a new controlled revision when needed."], ar: [<>الملاحظات والتصحيح</>, <>بنحوّل الملاحظات لـ{ar.finding} عليها مسؤول، ونتابع التصحيح، ونعمل {ar.revision} جديدة لما نحتاج.</>] },
  { en: ["Ready / Closed", "Keep the complete history of versions, packages, approvals, prechecks, submission cycles, findings, and audit evidence."], ar: [<>جاهز / مقفول</>, <>بنحتفظ بتاريخ النسخ والـ{ar.package} والموافقات والـ{ar.precheck} والـ{ar.finding} والـ{<LtrTerm>Audit Evidence</LtrTerm>}.</>] },
];

const currentStatuses = ["IMPLEMENTED", "IMPLEMENTED_PROTOTYPE"];
const groups = [...new Set(features.filter((feature) => currentStatuses.includes(feature.status)).map((feature) => feature.group))];
const implementedCount = features.filter((feature) => currentStatuses.includes(feature.status)).length;

function StatusBadge({ status, lang }: { status: AboutStatus; lang: AppLocale }) {
  return <span className={`about-status about-status-${status.toLowerCase()}`}><BidiText>{statusLabels[status][lang === "ar-EG" ? "ar" : "en"]}</BidiText></span>;
}

function SectionHeading({ number, en, arTitle, lang }: { number: string; en: string; arTitle: ReactNode; lang: AppLocale }) {
  return <div className="about-section-heading"><span className="about-number">{number}</span><div><span className="eyebrow">{lang === "en" ? `SECTION ${number}` : `القسم ${number}`}</span><h2>{lang === "en" ? en : <BidiText>{arTitle}</BidiText>}</h2></div></div>;
}

export function AboutPermitOpsPage({ onNavigate }: { onNavigate: (page: string) => void }) {
  const { locale: lang, setLocale } = useLocale();
  const [openGroups, setOpenGroups] = useState<string[]>([groups[0]]);
  const rtl = lang === "ar-EG";
  const changeLanguage = (next: AppLocale) => setLocale(next);
  const toggleGroup = (group: string) => setOpenGroups((current) => current.includes(group) ? current.filter((item) => item !== group) : [...current, group]);
  const visibleFeatures = useMemo(() => features.filter((feature) => currentStatuses.includes(feature.status)), []);
  return <main className="about-page" lang={rtl ? "ar-EG" : "en"} dir={rtl ? "rtl" : "ltr"}>
    <div className="about-toolbar"><div><span className="eyebrow">{rtl ? "دليل التشغيل" : "OPERATING GUIDE"}</span><p>{rtl ? "شرح بسيط للمستخدمين الجدد" : "A business guide for first-time users"}</p></div><div className="about-toolbar-actions"><button className="about-back" onClick={() => onNavigate("my-work")}>{rtl ? <>الرجوع لـ{ar.myWork}</> : "← Back to My Work"}</button><div className="about-language" role="group" aria-label="Language"><button className={lang === "en" ? "active" : ""} onClick={() => changeLanguage("en")} aria-pressed={lang === "en"}>English</button><button className={lang === "ar-EG" ? "active" : ""} onClick={() => changeLanguage("ar-EG")} aria-pressed={lang === "ar-EG"}>العربي</button></div></div></div>
    <section className="about-hero"><div className="about-hero-copy"><span className="about-kicker">{rtl ? <BidiText>Permit workflow · AMEC</BidiText> : "PERMIT WORKFLOW · AMEC"}</span><h1>{rtl ? <>PermitOps بيساعد {ar.amec} تجهّز وتراجع وتتحكم وتتابع شغل التراخيص من أول تجهيز المشروع لحد مراجعة البلدية.</> : "PermitOps helps AMEC prepare, verify, control, and track permit work from project setup through Municipality review."}</h1><p className="about-lead">{rtl ? <>النظام بيربط المستندات وبيانات المشروع والـ{ar.forms} و{ar.excel} والموافقات وتجهيز الـ{ar.package} وشغل البلدية في {ar.workflow} واحد واضح — علشان الفريق يعرف إيه الصح، إيه الناقص، إيه اللي موقف الشغل، ومين مسؤول عن الخطوة اللي بعدها.</> : "It brings documents, project data, forms, Excel, approvals, package preparation, and Municipality work into one controlled workflow — so the team can see what is correct, what is missing, what is blocked, who owns the next action, and what needs to happen next."}</p><div className="about-control-callout"><span className="about-control-icon">✓</span><p>{rtl ? <>الـ{<LtrTerm>AI</LtrTerm>} بيساعد في قراءة المعلومات ومقارنتها وتجهيزها. لكن الـ{<LtrTerm>Controls</LtrTerm>} الواضحة والأشخاص المخوّلين بيفضلوا مسؤولين عن القرارات المهمة.</> : "AI helps read, compare, and prepare information. Deterministic controls and authorized people remain responsible for consequential decisions."}</p></div></div><div className="about-hero-visual" aria-label={rtl ? "مسار المعلومات من المصدر لحد التقديم" : "Information moves from source to controlled output"}><div className="about-visual-orbit"><span>01</span><b>{rtl ? "مصدر" : "SOURCE"}</b><small>{rtl ? <BidiText>Evidence</BidiText> : "Evidence"}</small></div><div className="about-visual-arrow">→</div><div className="about-visual-orbit accent"><span>02</span><b>{rtl ? "حقيقة متراجعة" : "VERIFIED FACT"}</b><small>{rtl ? <BidiText>Human check</BidiText> : "Human check"}</small></div><div className="about-visual-arrow">→</div><div className="about-visual-orbit dark"><span>03</span><b>{rtl ? "Output متحكم فيه" : "CONTROLLED OUTPUT"}</b><small>{rtl ? <BidiText>Ready to review</BidiText> : "Ready to review"}</small></div></div></section>

    <section className="about-section"><SectionHeading number="01" en="Why PermitOps exists" arTitle={<>ليه {ar.product} موجود؟</>} lang={lang}/><div className="about-why-grid"><article><span className="about-card-icon">01</span><h3>{rtl ? "مشروع واحد، مصادر كتير" : "One project, many sources"}</h3><p>{rtl ? <>بيانات المشروع ممكن تبقى موزعة بين عقود الملكية والرسومات والمستندات و{ar.synology} و{ar.excel} والإيميلات والـ{ar.portal}.</> : "Project information can be spread across title deeds, drawings, other documents, Synology folders, Excel, emails, and the Municipality portal."}</p><small>{rtl ? <>{ar.product} بيربط الصورة كلها من غير ما يفترض إن كل مصدر له نفس درجة الاعتماد.</> : "PermitOps connects the context without pretending every source is equally authoritative."}</small></article><article><span className="about-card-icon">02</span><h3>{rtl ? "منع البيانات الغلط أو القديمة" : "Prevent wrong or stale information"}</h3><p>{rtl ? <>{ar.product} بيقارن المصادر، يوضح التعارض، يتابع الـ{<LtrTerm>Versions</LtrTerm>}، ويمنع إن بيانات قديمة تكمل في الـ{ar.package} من غير مراجعة.</> : "PermitOps compares sources, shows conflicts, tracks versions, and prevents stale information from quietly continuing into a package."}</p><small>{rtl ? "التغيير المؤثر بيخلّي الشغل اللي بيعتمد عليه محتاج مراجعة تاني." : "Material changes make dependent work visible and revalidatable."}</small></article><article><span className="about-card-icon">03</span><h3>{rtl ? "خلي سير الشغل واضح" : "Make the workflow visible"}</h3><p>{rtl ? <>النظام بيوضح إيه الجاهز، إيه اللي موقف الشغل، مين مسؤول، وإيه المطلوب قبل ما الترخيص يتحرك.</> : "The system shows what is ready, what is blocked, who owns the next action, and what must happen before the permit can move forward."}</p><small>{rtl ? <>ابدأ من {ar.myWork} عشان تعرف الخطوة اللي بعدها.</> : "Start in My Work to see the next action."}</small></article></div></section>

    <section className="about-section about-flow-section"><SectionHeading number="02" en="How PermitOps works" arTitle={<>{ar.product} بيشتغل إزاي؟</>} lang={lang}/><p className="about-section-intro">{rtl ? <>من أول المصدر لحد تاريخ الإغلاق، كل مرحلة ليها حالة واضحة وقرار بشري لما يكون القرار مؤثر.</> : "From source information to closure history, every stage has a visible state and a human checkpoint when the decision matters."}</p><div className="about-lifecycle" aria-label={rtl ? "المراحل الثمانية لسير العمل" : "Eight lifecycle stages"}>{lifecycle.map(({ en, ar: arCopy }, index) => <article key={en[0] as string} className="about-lifecycle-step"><div className="about-step-number">{index + 1}</div><div><h3>{rtl ? <BidiText>{arCopy[0]}</BidiText> : en[0]}</h3><p>{rtl ? arCopy[1] : en[1]}</p></div>{index < lifecycle.length - 1 && <span className="about-flow-arrow" aria-hidden="true">→</span>}</article>)}</div><p className="about-sr-note">{rtl ? "الترتيب المنطقي للمراحل يفضل من 1 إلى 8 لقارئ الشاشة، حتى لو اتجاه العرض انعكس في العربي." : "The logical order remains 1 through 8 for screen readers, even when the visual direction changes in Arabic."}</p></section>

    <section className="about-section"><SectionHeading number="03" en="When the authority sends comments" arTitle="لما الجهة تبعت ملاحظات" lang={lang}/><div className="about-loop-grid"><div className="about-loop-card"><span className="eyebrow">{rtl ? "دورة التصحيح" : "CORRECTION LOOP"}</span><div className="about-loop"><b>{rtl ? "Authority Review" : "Authority review"}</b><i>↓</i><b>{rtl ? "Comments / Findings" : "Comments / findings"}</b><i>↓</i><b>{rtl ? "Correction" : "Correction"}</b><i>↓</i><b>{rtl ? "New Revision" : "New revision"}</b><i>↓</i><b>{rtl ? "Re-prepare / Recheck" : "Re-prepare / recheck"}</b><i>↓</i><b>{rtl ? "Human final review" : "Human final review"}</b></div></div><div className="about-loop-card precheck"><span className="eyebrow">{rtl ? "نقطة مراجعة خارجية" : "EXTERNAL CHECKPOINT"}</span><h3>{rtl ? <>الـ{ar.precheck}</> : "Authority AI precheck"}</h3><p>{rtl ? <>دي خطوة مراجعة خارجية قبل التقديم. هي ما بتستبدلش مراجعة {ar.amec} ولا الـ{ar.submit} البشري.</> : "The authority AI precheck is an external pre-submission checkpoint. It does not replace AMEC review or the final human submission."}</p><div className="about-decision"><span>YES</span><b>{rtl ? "مشكلة أساسية؟ صحّح واعمل Revision جديدة" : "Blocking finding? Correct and create a new revision."}</b></div><div className="about-decision pass"><span>NO</span><b>{rtl ? "مراجعة بشرية نهائية ثم تقديم بشري" : "Human final review, then human submit."}</b></div></div></div><div className="about-callout"><b>{rtl ? <>التغيير المؤثر ما بيستخباش في {ar.product}.</> : "Important changes do not disappear inside PermitOps."}</b><span>{rtl ? <>لو مصدر أو معلومة معتمدة اتغيرت، الـ{ar.package} والـ{ar.revision} والـ{ar.precheck} اللي بيعتمدوا عليها ممكن يتعلّموا {ar.stale} ولازم يتراجعوا.</> : "If a source or approved fact changes, dependent package, revision, and precheck work can become stale and must be revalidated."}</span></div></section>

    <section className="about-section about-features"><SectionHeading number="04" en="Capabilities available in the current MVP" arTitle={<>الإمكانيات الموجودة في الـ{ar.mvp} الحالي</>} lang={lang}/><div className="about-feature-summary"><div><strong>{implementedCount}</strong><span>{rtl ? <>إمكانية متاحة في الـ{ar.mvp} الحالي</> : "capabilities available in this prototype"}</span></div><p>{rtl ? "العدد محسوب من الـcatalog اللي حالته موجود أو موجود في Prototype. الأساس والمخطط مش داخلين في العدد." : "The count is calculated from the catalog entries marked implemented or implemented in prototype. Foundation and planned items are not counted."}</p></div><div className="about-feature-groups">{groups.map((group) => { const items = visibleFeatures.filter((feature) => feature.group === group); const isOpen = openGroups.includes(group); return <section className="about-feature-group" key={group}><button className="about-group-toggle" onClick={() => toggleGroup(group)} aria-expanded={isOpen}><span><span className="about-group-dot"/>{rtl ? <BidiText>{group === "Broader AMEC vision" ? "رؤية AMEC الأوسع" : group === "Safety boundaries" ? "حدود الأمان" : group}</BidiText> : group}</span><b>{items.length}</b><span aria-hidden="true">{isOpen ? "−" : "+"}</span></button>{isOpen && <div className="about-feature-list">{items.map((feature) => <article className="about-feature" key={feature.id}><div className="about-feature-top"><h3>{rtl ? <BidiText>{feature.ar.title}</BidiText> : feature.en.title}</h3><StatusBadge status={feature.status} lang={lang}/></div><p>{rtl ? <BidiText>{feature.ar.description}</BidiText> : feature.en.description}</p><small>{rtl ? "مبني على: " : "Evidence: "}{feature.evidence.join(" · ")}</small>{feature.route && (() => { const route = feature.route; return <button className="about-inline-link" onClick={() => onNavigate(route === "/work" ? "my-work" : route === "/permits" ? "permits" : route.startsWith("/admin/") ? route.slice(7) : route)}>{rtl ? "افتح الشاشة ←" : "Open screen →"}</button>; })()}</article>)}</div>}</section>; })}</div></section>

    <section className="about-section"><SectionHeading number="05" en="What users see in the app" arTitle="المستخدم بيشوف إيه في التطبيق؟" lang={lang}/><div className="about-stage-map">{lifecycle.map(({ en, ar: arCopy }, index) => <article key={en[0] as string}><span>{String(index + 1).padStart(2, "0")}</span><h3>{rtl ? <BidiText>{arCopy[0]}</BidiText> : en[0]}</h3><p>{rtl ? <BidiText>{arCopy[1]}</BidiText> : index === 0 ? "Project identity, source links, documents, Synology, Excel, and Municipality link." : index === 1 ? "Extracted fields, evidence, conflicts, and verified values." : index === 2 ? "Requirements, validity, forms, Excel, drawings, attachments, readiness, and reviews." : index === 3 ? "Portal sequence, fields, dropdowns, grids, attachments, reconciliation, and precheck." : index === 4 ? "Readiness, package approval, and submission handoff." : index === 5 ? "Submitted state, authority status, monitoring, and comments." : index === 6 ? "Findings, assignments, evidence, correction, closure, and resubmission." : "Revisions, packages, prechecks, submissions, audit, and lineage."}</p></article>)}</div></section>

    <section className="about-section about-data-section"><SectionHeading number="06" en="How one fact becomes controlled outputs" arTitle={<>إزاي معلومة واحدة تبقى <LtrTerm>Outputs</LtrTerm> متحكم فيها؟</>} lang={lang}/><div className="about-data-flow"><div><span>01</span><b>{rtl ? "SOURCE" : "SOURCE"}</b><p>{rtl ? "سند ملكية · Survey · Drawing · مستند معتمد · Excel" : "Title deed · survey · drawing · approved document · Excel"}</p></div><i>↓</i><div><span>02</span><b>{rtl ? "OBSERVATION" : "OBSERVATION"}</b><p>{rtl ? "المصدر بيقول إيه فعلاً" : "What the source actually says"}</p></div><i>↓</i><div><span>03</span><b>{rtl ? "EVIDENCE + COMPARISON" : "EVIDENCE + COMPARISON"}</b><p>{rtl ? "المعلومة جاية منين وهل المصادر متفقة" : "Where the value came from and whether sources agree"}</p></div><i>↓</i><div className="verified"><span>04</span><b>{rtl ? "VERIFIED FACT" : "VERIFIED FACT"}</b><p>{rtl ? "القيمة الحالية اللي اتأكدنا منها" : "The current accepted value"}</p></div><i>↓</i><div className="outputs"><span>05</span><b>{rtl ? "CONTROLLED OUTPUTS" : "CONTROLLED OUTPUTS"}</b><p>{rtl ? <>Form · {ar.excel} · {ar.package} / Manifest · Drawing QA · تجهيز البلدية</> : "Form · Excel · Package / manifest · Drawing QA · Municipality preparation"}</p></div></div><div className="about-callout"><b>{rtl ? "الـOutputs مش مصدر حقيقة جديد." : "Outputs do not become a separate source of truth."}</b><span>{rtl ? <>كل Output بيرجع للبيانات المتراجعة والـ{ar.evidence} اللي أنتجته.</> : "Every output remains traceable to the verified project facts and evidence that produced it."}</span></div></section>

    <section className="about-section about-architecture"><SectionHeading number="07" en="Simplified business architecture" arTitle="شكل النظام ببساطة" lang={lang}/><div className="about-architecture-layers"><div><span>01</span><b>{rtl ? <>مصادر شغل {ar.amec}</> : "AMEC work sources"}</b><small>{rtl ? "Documents · Synology · Excel · Municipality" : "Documents · Synology · Excel · Municipality"}</small></div><div><span>02</span><b>{rtl ? <> {ar.product} بيفهم ويراجع البيانات</> : "PermitOps understands and reconciles"}</b><small>{rtl ? "Observations · Evidence · Conflicts · Verified facts" : "Observations · Evidence · Conflicts · Verified facts"}</small></div><div><span>03</span><b>{rtl ? <BidiText>Workflow وOutputs متحكم فيها</BidiText> : "Controlled workflow and outputs"}</b><small>{rtl ? "Requirements · Forms · Package · Portal preparation" : "Requirements · Forms · Package · Portal preparation"}</small></div><div><span>04</span><b>{rtl ? "قرارات ومراجعات بشرية" : "Human decisions and reviews"}</b><small>{rtl ? "Verifier · Engineer · Approver · Final submitter" : "Verifier · Engineer · Approver · Final submitter"}</small></div><div><span>05</span><b>{rtl ? "Feedback Loop من الجهة" : "Authority feedback loop"}</b><small>{rtl ? "Precheck · Comments · Findings · Correction · History" : "Precheck · comments · findings · correction · history"}</small></div></div></section>

    <section className="about-section"><SectionHeading number="08" en="AI assists; people decide" arTitle={<>الـ<LtrTerm>AI</LtrTerm> بيساعد، والناس بتقرر</>} lang={lang}/><div className="about-ai-grid"><article className="about-ai-card assists"><span className="about-card-icon">AI</span><h3>{rtl ? "الـAI والبرمجيات ممكن تساعد في" : "AI and software can help with"}</h3><ul>{(rtl ? ["قراءة وتصنيف المستندات", "استخراج معلومات مع Evidence", "مقارنة المصادر وإظهار التعارض", "اقتراح وتجهيز Outputs متحكم فيها", "تجميع ملاحظات في Findings قابلة للمتابعة"] : ["Reading and classifying documents", "Extracting information with evidence", "Comparing sources and surfacing conflicts", "Preparing controlled outputs", "Turning supported comments into trackable findings"]).map((item) => <li key={item}>{item}</li>)}</ul></article><article className="about-ai-card decides"><span className="about-card-icon">H</span><h3>{rtl ? <BidiText>الناس والـControls لسه بيقرروا</BidiText> : "People and controls still decide"}</h3><ul>{(rtl ? ["القيمة المعتمدة لما المصادر تختلف", "القرار الهندسي المهني", "اعتماد الـPackage", "التصحيح المؤثر وإصدار Revision جديدة", "الـFinal Submit للبلدية"] : ["The accepted value when sources disagree", "Professional engineering decisions", "Package approval", "Material correction and a new revision", "The final Municipality submission"]).map((item) => <li key={item}>{item}</li>)}</ul></article></div></section>

    <section className="about-section"><SectionHeading number="09" en="Human roles and checkpoints" arTitle="أدوار الناس ونقط المراجعة" lang={lang}/><div className="about-roles-grid">{(rtl ? [["Permit Preparer", "يربط المصادر ويجهز الشغل"], ["Data Verifier", "يراجع ويثبت البيانات المهمة"], ["Responsible Engineer", "يقرر في الأمور المهنية والهندسية"], ["Package Approver", "يعتمد الـPackage الحالية"], ["Final Submitter", "يعمل التقديم النهائي بنفسه"]] : [["Permit Preparer", "Connects sources and prepares the work"], ["Data Verifier", "Reviews and confirms important facts"], ["Responsible Engineer", "Owns professional and engineering decisions"], ["Package Approver", "Approves the exact current package"], ["Final Submitter", "Performs the final submission personally"]]).map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h3>{rtl ? <BidiText>{title}</BidiText> : title}</h3><p>{rtl ? <BidiText>{body}</BidiText> : body}</p></article>)}</div></section>

    <section className="about-section about-broader"><SectionHeading number="10" en="The broader AMEC owner-session vision" arTitle="رؤية AMEC الأوسع" lang={lang}/><p className="about-section-intro">{rtl ? <>الـ<LtrTerm>Permit Core</LtrTerm> الحالي جزء من صورة أكبر من الـ{<LtrTerm>RFQ</LtrTerm>} لحد التسليم. بعض الأجزاء لها أساس أو Prototype، لكنها مش كلها Workflow مكتمل أو معتمد.</> : "The current permit core fits into a wider AMEC owner-session vision from RFQ through handover. Some parts have a foundation or prototype, but they are not all complete or approved workflows."}</p><div className="about-broader-flow">{(rtl ? [["RFQ / Tender / Inquiry", "أساس"], ["Quotation / Client acceptance", "أساس فقط"], ["Contract / Checklist", "أساس فقط"], ["Permit core", "موجود في Prototype"], ["Engineering / Finance / Handover", "مخطط / محتاج تحديد"]] : [["RFQ / Tender / Client inquiry", "Foundation"], ["Quotation / Client acceptance", "Foundation only"], ["Contract / Checklist", "Foundation only"], ["Permit core", "Implemented in prototype"], ["Engineering / Finance / Handover", "Planned / pending scope"]]).map(([title, status], index) => <article key={title}><span>0{index + 1}</span><h3>{rtl ? <BidiText>{title}</BidiText> : title}</h3><StatusBadge status={status === "Implemented in prototype" || status === "موجود في Prototype" ? "IMPLEMENTED_PROTOTYPE" : status.startsWith("Planned") || status.startsWith("مخطط") ? "PLANNED_PENDING_SCOPE" : "FOUNDATION_ONLY"} lang={lang}/></article>)}</div><div className="about-safety-strip">{rtl ? <>الـ{<LtrTerm>Quotation</LtrTerm>} والـ{<LtrTerm>Contract</LtrTerm>} والـ{<LtrTerm>Invoice</LtrTerm>} والـ{<LtrTerm>Handover</LtrTerm>} مش بيتعرضوا كإمكانيات Permit MVP مكتملة.</> : "Quotation, contract, invoice, and handover are not presented as complete Permit MVP capabilities."}</div></section>

    <section className="about-section"><SectionHeading number="11" en="What PermitOps intentionally does not do" arTitle="إيه اللي PermitOps مش بيعمله؟" lang={lang}/><div className="about-not-grid">{(rtl ? [["مفيش Final Submit آلي", "التقديم النهائي للبلدية بيعمله شخص مخوّل."], ["مفيش تغيير صامت", "التعارضات المهمة بتظهر للمراجعة."], ["مفيش اعتماد مهني آلي", "الـAI ما بيستبدلش المهندس المسؤول."], ["مفيش اعتماد تجاري آلي", "الـAI ما بيعتمدش السعر أو الشروط أو إصدار Quotation."], ["مفيش قيود محاسبية آلية", "دعم Invoice مش معناه ترحيل محاسبي."], ["مفيش AI Browser مفتوح", "التعامل الخارجي بيستخدم Operations محددة ومعتمدة."]] : [["No machine final submit", "PermitOps does not perform the final Municipality submission."], ["No silent critical overwrite", "Important conflicts are surfaced for review."], ["No autonomous professional approval", "AI does not replace the Responsible / Authorized Engineer."], ["No autonomous commercial authority", "AI does not authorize binding price, terms, or quotation release."], ["No automatic accounting posting", "Invoice support does not mean accounting entries are posted."], ["No generic browser agent", "External interaction uses bounded, approved operations."]]).map(([title, body]) => <article key={title}><span className="about-x">×</span><h3>{rtl ? <BidiText>{title}</BidiText> : title}</h3><p>{rtl ? <BidiText>{body}</BidiText> : body}</p></article>)}</div></section>

    <section className="about-section"><SectionHeading number="12" en="Quick glossary" arTitle="قاموس سريع" lang={lang}/><div className="about-glossary">{(rtl ? [["Evidence", "الدليل أو المصدر اللي بيثبت المعلومة."], ["Observation", "المعلومة زي ما ظهرت في مصدر معين قبل ما نعتمدها."], ["Verified Fact", "المعلومة الحالية اللي اتراجعت واتأكدنا منها."], ["Conflict", "لما مصدرين أو أكتر يقولوا قيم مختلفة."], ["Package", "مجموعة المستندات والـForms والمرفقات والحالة المعتمدة."], ["Revision", "نسخة جديدة متحكم فيها بعد تغيير مؤثر."], ["Finding", "ملاحظة عليها مسؤول وخطوة مطلوبة وEvidence للإغلاق لو مطلوب."], ["Stale", "Output أو اعتماد قديم لأن حاجة أساسية اتغيرت."]] : [["Evidence", "The source or proof that supports a value."], ["Observation", "What a source says before the value is accepted."], ["Verified fact", "The current accepted value used by the workflow."], ["Conflict", "Two or more sources disagree about the same value."], ["Package", "The controlled documents, forms, attachments, and state prepared for review."], ["Revision", "A new controlled version after a material change."], ["Finding", "A comment or problem with an owner, action, and closure evidence when required."], ["Stale", "An output or approval that is old because a material input changed."]]).map(([term, definition]) => <details key={term}><summary><LtrTerm>{term}</LtrTerm><span>+</span></summary><p>{rtl ? <BidiText>{definition}</BidiText> : definition}</p></details>)}</div></section>

    <section className="about-cta"><div><span className="about-kicker">{rtl ? "الخطوة اللي بعدها" : "NEXT STEP"}</span><h2>{rtl ? "جاهز تبدأ؟" : "Ready to work?"}</h2><p>{rtl ? <>روح على {ar.myWork} وشوف إيه اللي محتاج تدخل منك دلوقتي.</> : "Go to My Work to see what needs your attention now."}</p></div><div className="about-cta-actions"><button className="button-primary" onClick={() => onNavigate("my-work")}>{rtl ? <>افتح {ar.myWork}</> : "Open My Work"}</button><button className="button-secondary" onClick={() => onNavigate("permits")}>{rtl ? "شوف التراخيص" : "View Permits"}</button></div></section>
    <div className="about-environment"><span className="dot"/><b>{rtl ? "SYNTHETIC PROTOTYPE" : "SYNTHETIC PROTOTYPE"}</b><span>{rtl ? <>مفيش Production Portal Writes · التقديم النهائي بشري</> : "No production portal writes · Human submission required"}</span></div>
  </main>;
}
