import { useEffect, useMemo, useState } from "react";
import { api } from "./api";

type Role = "SYSTEM_ADMIN" | "OWNER_SPONSOR" | "COMMERCIAL_APPROVER" | "RESPONSIBLE_ENGINEER";
type SourceType = "TENDER_DOCUMENT" | "TENDER_EMAIL" | "TENDER_PHOTO" | "CLIENT_DATA";
const sourceTypes: Array<{ key: SourceType; label: string }> = [
  { key: "TENDER_EMAIL", label: "Tender Email" },
  { key: "TENDER_DOCUMENT", label: "Tender Document" },
  { key: "TENDER_PHOTO", label: "Tender Photo / Image" },
  { key: "CLIENT_DATA", label: "Client Information" },
];
const lifecycleLabels = ["Intake & Sources", "Engineering Preparation", "Commercial Review", "Client Response", "Contract Handoff"];
const sourceDisplay: Record<string, string> = { TENDER_EMAIL: "Tender Email", TENDER_DOCUMENT: "Tender Document", TENDER_PHOTO: "Tender Photo / Image", CLIENT_DATA: "Client Information" };
const roleLabel: Record<Role, string> = { SYSTEM_ADMIN: "Owner", OWNER_SPONSOR: "Owner", COMMERCIAL_APPROVER: "Business Development", RESPONSIBLE_ENGINEER: "Engineering" };
function headers(role: Role) { return { "X-Dev-Role": role }; }

export function BDProposalOwnerSessionPage({ role }: { role: Role }) {
  const [selected, setSelected] = useState<string | null>(null);
  const [newProposal, setNewProposal] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  return <div className="workflow-page bd-session">
    {!selected && !newProposal && !showSettings ? <ProposalList role={role} onOpen={setSelected} onNew={() => setNewProposal(true)} onSettings={() => setShowSettings(true)} /> : showSettings ? <ProposalInputs role={role} onBack={() => setShowSettings(false)} /> : <ProposalWorkbench role={role} proposalId={selected} onBack={() => { setSelected(null); setNewProposal(false); }} onCreated={setSelected} />}
  </div>;
}

function ProposalList({ role, onOpen, onNew, onSettings }: { role: Role; onOpen: (id: string) => void; onNew: () => void; onSettings: () => void }) {
  const [rows, setRows] = useState<any[]>([]); const [q, setQ] = useState(""); const [stage, setStage] = useState(""); const [error, setError] = useState("");
  const load = () => api<any>(`/api/bd/proposals?q=${encodeURIComponent(q)}${stage ? `&stage=${stage}` : ""}`, { headers: headers(role) }).then((data) => setRows(data.items || [])).catch((cause) => setError(cause instanceof Error ? cause.message : "Proposal list unavailable."));
  useEffect(() => { void load(); }, [role, q, stage]);
  return <>
    <div className="page-intro"><div><span className="eyebrow">BD · PROPOSALS</span><h2>Proposal Intake</h2><p>One Proposal identity from client inputs through Engineering, commercial review, and Contract Handoff.</p></div><div><span className="tag">{roleLabel[role]}</span><button className="text-button" onClick={onSettings}>Inputs &amp; Go-Live</button></div></div>
    {error && <div className="error-state" role="alert">{error}</div>}
    <section className="panel bd-list-panel"><div className="proposals-toolbar"><div className="filter-row"><input aria-label="Search proposals" placeholder="Search Proposal, Project Ref, Client…" value={q} onChange={(event) => setQ(event.target.value)} /><select aria-label="Filter stage" value={stage} onChange={(event) => setStage(event.target.value)}><option value="">All stages</option><option value="IN_REVIEW">In Review</option><option value="PROPOSAL_PREPARATION">Engineering Preparation</option><option value="PROPOSAL_HANDOVER">Ready for BD</option><option value="ACCEPTED">Accepted</option><option value="CONTRACT_HANDOVER">Contract Handoff</option></select></div>{role !== "RESPONSIBLE_ENGINEER" && <button className="button-primary" onClick={onNew}>＋ New Proposal</button>}</div>
      <div className="table-panel"><table><thead><tr><th>Proposal</th><th>Opportunity Ref</th><th>Client</th><th>Stage</th><th>Next action</th><th>Last Activity</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.proposal}</b><small className="proposal-row-sub">{row.proposal_reference}</small></td><td>{row.project_ref || "Provisional"}</td><td>{row.client}</td><td><span className="status status-under-review">{row.stage}</span></td><td>{row.validation?.blockers?.length ? "Review intake blockers" : row.stage_code === "IN_REVIEW" ? "Proceed to Engineering" : "Open Proposal"}</td><td>{row.last_activity ? new Date(row.last_activity).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "—"}</td><td><button className="text-button" onClick={() => onOpen(row.id)}>Open Proposal →</button></td></tr>)}{!rows.length && <tr><td colSpan={7}><div className="empty-state"><b>No Proposal records match the current filter.</b><p>Create a draft to begin the controlled source flow.</p></div></td></tr>}</tbody></table></div></section>
    <div className="proposal-sor-note"><span className="proposal-blue-dot" /><span>Dashboard is the canonical source for Proposal Template, Checklist, and Definitions. Proposal-specific evidence remains transactional here.</span></div>
  </>;
}

function ProposalInputs({ role, onBack }: { role: Role; onBack: () => void }) {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { api<any>("/api/bd/proposals/settings/go-live", { headers: headers(role) }).then((data) => setItems(data.items || [])).catch((cause) => setError(cause instanceof Error ? cause.message : "Inputs could not be loaded.")); }, [role]);
  const update = (key: string, raw: string) => setItems((current) => current.map((item) => item.key === key ? { ...item, value: { ...item.value, value: raw } } : item));
  const save = async () => { try { await api("/api/bd/proposals/settings/go-live", { method: "PUT", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ settings: Object.fromEntries(items.map((item) => [item.key, item.value])) }) }); setSaved(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Inputs could not be saved."); } };
  return <section className="panel route-detail-page"><div className="panel-head"><div><span className="eyebrow">BD · INPUTS &amp; GO-LIVE</span><h2>Operating decisions</h2><p>Safe defaults are explicit and remain pending until an Owner confirms them.</p></div><button className="text-button" onClick={onBack}>← Proposal list</button></div>{error && <div className="error-state" role="alert">{error}</div>}{saved && <div className="inline-message" role="status">Owner decisions persisted.</div>}<div className="bd-form-grid">{items.map((item) => <label key={item.key}>{item.key.replaceAll("_", " ")}<textarea value={item.value?.value || ""} onChange={(event) => update(item.key, event.target.value)} disabled={role === "RESPONSIBLE_ENGINEER"} /><small>{item.status} · {item.notes}</small></label>)}</div>{role !== "RESPONSIBLE_ENGINEER" && <button className="button-primary" onClick={() => void save()}>Save Owner decisions</button>}</section>;
}

function ProposalWorkbench({ role, proposalId, onBack, onCreated }: { role: Role; proposalId: string | null; onBack: () => void; onCreated: (id: string) => void }) {
  const [proposal, setProposal] = useState<any>(null); const creating = !proposalId; const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [createSource, setCreateSource] = useState<SourceType | null>(null);
  const [createForm, setCreateForm] = useState({ proposal_description: "", project_reference: "", client_name: "" });
  const load = () => proposalId ? api<any>(`/api/bd/proposals/${proposalId}`, { headers: headers(role) }).then(setProposal).catch((cause) => setError(cause instanceof Error ? cause.message : "Proposal workspace unavailable.")) : Promise.resolve();
  useEffect(() => { void load(); }, [proposalId, role]);
  const create = async () => { setError(""); if (!createForm.proposal_description.trim() || !createForm.client_name.trim()) { setError("Proposal Description and Client are required to create the draft."); return; } setBusy(true); try { const result = await api<any>("/api/bd/proposals", { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify(createForm) }); onCreated(result.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal draft could not be created."); } finally { setBusy(false); } };
  if (creating) return <section className="panel route-detail-page bd-create-panel"><div className="panel-head"><div><span className="eyebrow">BD · NEW PROPOSAL</span><h2>New Proposal Intake</h2><p>Create one Proposal context, then add one or more Tender &amp; Client Sources. Client List, Proposal Form, and Contract Form remain in their own contexts.</p></div><button className="text-button" onClick={onBack}>← Proposal list</button></div>{error && <div className="error-state" role="alert">{error}</div>}<div className="bd-form-grid"><label>Proposal Description<input aria-label="Proposal Description" value={createForm.proposal_description} onChange={(event) => setCreateForm({ ...createForm, proposal_description: event.target.value })} /></label><label>Commercial Client<input aria-label="Client" value={createForm.client_name} onChange={(event) => setCreateForm({ ...createForm, client_name: event.target.value })} /></label><label>Opportunity Ref (provisional)<input aria-label="Project Ref" value={createForm.project_reference} onChange={(event) => setCreateForm({ ...createForm, project_reference: event.target.value })} /></label></div><div className="proposal-intake-step"><h3>Start with a source (optional)</h3><div className="bd-source-grid">{sourceTypes.map((item) => <button type="button" key={item.key} className={`bd-source-card ${createSource === item.key ? "complete" : ""}`} onClick={() => setCreateSource(item.key)}><b>{item.label}</b><small>{createSource === item.key ? "Selected for this Proposal" : "Add after the draft is created"}</small></button>)}</div></div><button className="button-primary" onClick={() => void create()} disabled={busy}>{busy ? "Creating…" : createSource ? `Create Proposal from ${sourceDisplay[createSource]}` : "Create Proposal intake"}</button></section>;
  if (!proposal) return <section className="panel"><b>Loading Proposal workspace…</b></section>;
  return <ProposalWorkspaceDetail role={role} proposal={proposal} setProposal={setProposal} onBack={onBack} setMessage={setMessage} message={message} error={error} setError={setError} load={load} />;
}

function ProposalWorkspaceDetail({ role, proposal, setProposal, onBack, setMessage, message, error, setError }: any) {
  const readOnly = role === "RESPONSIBLE_ENGINEER"; const [fields, setFields] = useState({ ...(proposal.fields || {}) }); const [amec, setAmec] = useState(JSON.stringify(proposal.amec_input || {}, null, 2)); const [saving, setSaving] = useState(false); const [sourceBusy, setSourceBusy] = useState<string | null>(null); const [noteType, setNoteType] = useState("CALL_NOTE"); const [noteContent, setNoteContent] = useState(""); const [noteBusy, setNoteBusy] = useState(false); const validation = proposal.validation || { blockers: [], warnings: [] }; const forms = proposal.forms_v2 || {}; const readiness = proposal.intake_readiness || { ready: false, blockers: validation.blockers || [], warnings: validation.warnings || [] }; const [contactDraft, setContactDraft] = useState({ display_name: forms.proposal_contact?.display_name || fields.attn_contact || "", email: forms.proposal_contact?.email || fields.contact_email || "", mobile: forms.proposal_contact?.mobile || fields.mobile_no || "" }); const [siteDraft, setSiteDraft] = useState({ location_text: forms.site_context?.location_text || fields.location || "", plot_text: forms.site_context?.plot_text || "", area_value: forms.site_context?.area_value || "", area_unit: forms.site_context?.area_unit || "m2", area_kind: forms.site_context?.area_kind || "LEGACY_UNSPECIFIED", site_description: forms.site_context?.site_description || "" }); const [scopeDescription, setScopeDescription] = useState("");
  const update = (key: string, value: string) => setFields((current: any) => ({ ...current, [key]: value, provenance: { ...(current.provenance || {}), [key]: "manual" } }));
  const save = async () => { setSaving(true); setError(""); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}`, { method: "PATCH", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ fields, amec_input: JSON.parse(amec || "{}") }) }); setProposal(result); setMessage("Proposal fields and AMEC Input saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal fields could not be saved."); } finally { setSaving(false); } };
  const upload = async (sourceType: SourceType, file: File | null) => { if (!file) return; setSourceBusy(sourceType); setError(""); const form = new FormData(); form.append("source_type", sourceType); form.append("file", file); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/sources`, { method: "POST", headers: headers(role), body: form }); setProposal(result.proposal); setMessage(`${sourceType.replaceAll("_", " ")} registered and read-back verified.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Source evidence could not be registered."); } finally { setSourceBusy(null); } };
  const validate = async () => { const result = await api<any>(`/api/bd/proposals/${proposal.id}/validation`, { headers: headers(role) }); setProposal((current: any) => ({ ...current, validation: result })); };
  const saveV2 = async (path: string, payload: any, success: string) => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/${path}`, { method: path === "contact" || path === "site-context" ? "PUT" : "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setProposal(result); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal governance update failed."); } };
  const confirmRegulatory = async (intentId: string) => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/regulatory-scope/${intentId}/confirm`, { method: "POST", headers: headers(role) }); setProposal(result); setMessage("Regulatory scoping intent confirmed for Proposal planning only."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Regulatory scope could not be confirmed."); } };
  const refreshInputs = async () => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/expected-client-inputs/preview`, { method: "POST", headers: headers(role) }); setProposal(result); setMessage("Expected Client Inputs — Preliminary refreshed and policy-pinned."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Expected Client Inputs could not be refreshed."); } };
  const addNote = async () => { if (!noteContent.trim()) return; setNoteBusy(true); setError(""); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/notes`, { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ note_type: noteType, content: noteContent }) }); setProposal(result); setNoteContent(""); setMessage("Note saved as human-entered context; it is not verified external fact."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Note could not be saved."); } finally { setNoteBusy(false); } };
  const uploadSitePhoto = async (file: File | null) => { if (!file) return; const form = new FormData(); form.append("file", file); setError(""); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/site-photos`, { method: "POST", headers: headers(role), body: form }); setProposal(result); setMessage("Site / Project Photo registered separately from Tender Photo / Image."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Site photo could not be registered."); } };
  const proceed = async () => { setError(""); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/proceed`, { method: "POST", headers: headers(role) }); setProposal(result.proposal); setMessage("Proposal Intake completed. Engineering Proposal Preparation is now the next step."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proceed is blocked by intake readiness."); } };
  const accept = async () => { setError(""); try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/accept`, { method: "POST", headers: headers(role) }); setProposal(result); setMessage(`Revision ${result.current_revision.revision_number} accepted by a human operator.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Accept is blocked by validation."); } };
  const sourceByType = useMemo(() => Object.fromEntries((proposal.sources || []).map((item: any) => [item.source_type, item])), [proposal.sources]);
  return <>
    <div className="page-intro"><div><span className="eyebrow">PROPOSAL INTAKE</span><h2>{proposal.title}</h2><p>Proposal {proposal.proposal_reference} · {proposal.project_reference || "Opportunity Ref provisional"}</p><p className="muted">Current owner: {proposal.current_owner || "Business Development"} · Next: {proposal.next_action?.label || "Review Proposal"}</p></div><button className="text-button" onClick={onBack}>← Proposals</button></div>
    <div className="workflow-stepper opportunity-tabs" aria-label="Proposal lifecycle">{lifecycleLabels.map((label, index) => <div className={`workflow-step ${proposal.lifecycle?.[index]?.active ? "active" : ""}`} key={label}><span className="workflow-step-dot">{index + 1}</span><span>{label}</span></div>)}</div>
    {message && <div className="inline-message" role="status">{message}</div>}{error && <div className="error-state" role="alert">{error}</div>}
    <section className="panel bd-workspace-header"><div><small>Proposal</small><b>{proposal.proposal_reference}</b></div><div><small>Opportunity Ref</small><b>{proposal.project_reference || "Provisional"}</b></div><div><small>Stage</small><b>{proposal.stage_label}</b></div><div><small>Current owner</small><b>{proposal.current_owner || "Business Development"}</b></div><div><small>Revision</small><b>{proposal.current_revision ? `AMEC Accepted r${proposal.current_revision.revision_number}` : "Draft intake"}</b></div></section>
    <ProposalConfigurationPanel configuration={proposal.configuration} role={role} />
    <div className="bd-workspace-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">TENDER &amp; CLIENT SOURCES</span><h3>Source entry</h3></div><small>Received: {proposal.intake_readiness?.source_count || 0} · evidence is not verified fact</small></div><div className="bd-source-grid">{sourceTypes.map((item) => <label className={`bd-source-card ${sourceByType[item.key] ? "complete" : ""}`} key={item.key}><b>{item.label}</b><small>{sourceByType[item.key] ? `✓ Received · ${sourceByType[item.key].verification_state}` : "Available source type · not required unless configured"}</small>{!readOnly && <input type="file" aria-label={`Add ${item.label}`} onChange={(event) => void upload(item.key, event.target.files?.[0] || null)} disabled={sourceBusy === item.key} />}</label>)}</div><p className="muted">Source history, hashes, DocumentVersion links, and provenance remain available in Advanced / History.</p></section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">CLIENT &amp; CONTACTS</span><h3>Commercial Client and Proposal Contact</h3></div><small>Commercial contact is not an Applicant or legal signatory.</small></div><p><b>{forms.commercial_client?.display_name || fields.client_name || "Commercial Client not recorded"}</b>{forms.commercial_client?.canonical_party_id ? <span className="provenance-badge">Canonical Party linked</span> : <span className="provenance-badge warning">Party resolution pending</span>}</p><div className="bd-form-grid"><label>Proposal Contact<input value={contactDraft.display_name} onChange={(event) => setContactDraft({ ...contactDraft, display_name: event.target.value })} disabled={readOnly} /></label><label>Email<input value={contactDraft.email} onChange={(event) => setContactDraft({ ...contactDraft, email: event.target.value })} disabled={readOnly} /></label><label>Mobile<input value={contactDraft.mobile} onChange={(event) => setContactDraft({ ...contactDraft, mobile: event.target.value })} disabled={readOnly} /></label></div>{!readOnly && <button className="button-secondary" onClick={() => void saveV2("contact", contactDraft, "Proposal contact saved.")}>Save Proposal Contact</button>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">SITE / PROPERTY</span><h3>Site / Property context</h3></div><small>{forms.site_context?.status === "LINKED" ? "Linked canonical Property" : "Unresolved context is allowed in intake"}</small></div><div className="bd-form-grid"><label>Location<input value={siteDraft.location_text} onChange={(event) => setSiteDraft({ ...siteDraft, location_text: event.target.value })} disabled={readOnly} /></label><label>Plot / Property text<input value={siteDraft.plot_text} onChange={(event) => setSiteDraft({ ...siteDraft, plot_text: event.target.value })} disabled={readOnly} /></label><label>Area / quantity basis<input value={siteDraft.area_value} onChange={(event) => setSiteDraft({ ...siteDraft, area_value: event.target.value })} disabled={readOnly} /></label><label>Area kind<select value={siteDraft.area_kind} onChange={(event) => setSiteDraft({ ...siteDraft, area_kind: event.target.value })} disabled={readOnly}><option>LEGACY_UNSPECIFIED</option><option>PLOT_AREA</option><option>GFA</option><option>BUILT_UP_AREA</option><option>NET_AREA</option><option>APPROVED_AREA</option></select></label><label className="wide">Site description<textarea value={siteDraft.site_description} onChange={(event) => setSiteDraft({ ...siteDraft, site_description: event.target.value })} disabled={readOnly} /></label></div><p className="muted">{forms.site_context?.property ? `Linked Property · ${forms.site_context.property.pin || forms.site_context.property.plot_number}` : "No canonical Property has been fabricated from free text."}</p>{!readOnly && <button className="button-secondary" onClick={() => void saveV2("site-context", { ...siteDraft, area_value: siteDraft.area_value === "" ? null : Number(siteDraft.area_value), status: "UNRESOLVED" }, "Site / Property context saved.")}>Save Site / Property context</button>}<label className="site-photo-picker">Site / Project Photos<input type="file" accept="image/*" aria-label="Add Site or Project Photo" onChange={(event) => void uploadSitePhoto(event.target.files?.[0] || null)} disabled={readOnly} /></label>{proposal.site_photos?.length ? <small>{proposal.site_photos.length} site photo(s) registered · separate from Tender Photo / Image</small> : <small>No Site / Project Photos registered.</small>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">STAKEHOLDERS</span><h3>Known / Candidate Stakeholders</h3></div><small>Proposal intent only · no case-role assignment</small></div>{forms.stakeholders?.length ? <div className="bd-v2-list">{forms.stakeholders.map((item: any) => <div key={item.id}><b>{item.role_code.replaceAll("_", " ")}</b><span>{item.party?.name_en || item.display_snapshot || "Unknown"}</span><span className="provenance-badge">{item.status.replaceAll("_", " ")}</span></div>)}</div> : <p className="muted">No stakeholder intent rows recorded.</p>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">AMEC SERVICE SCOPE</span><h3>Structured scope + narrative SOW</h3></div><small>AMEC offering, discipline, and regulatory ServiceType remain distinct.</small></div>{forms.service_scope_items?.length ? <div className="bd-v2-list">{forms.service_scope_items.map((item: any) => <div key={item.id}><b>{item.included ? "Included" : "Excluded"}</b><span>{item.description}</span><small>{item.service_offering_code || "Service offering pending"} · {item.discipline_code || "Discipline pending"}</small></div>)}</div> : <p className="muted">No structured scope rows yet; the narrative SOW remains preserved below.</p>}{!readOnly && <div className="bd-inline-add"><input aria-label="New service scope item" placeholder="Add AMEC service scope item" value={scopeDescription} onChange={(event) => setScopeDescription(event.target.value)} /><button className="button-secondary" onClick={() => { if (scopeDescription.trim()) { void saveV2("scope-items", { description: scopeDescription, included: true, commercial_treatment: "AMEC_FEE" }, "AMEC service scope added."); setScopeDescription(""); } }}>Add scope item</button></div>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">REGULATORY SCOPING · COMMERCIAL PLANNING</span><h3>Regulatory Scoping</h3></div><small>Not an Authority submission status.</small></div>{forms.regulatory_scope_intents?.length ? <div className="bd-v2-list">{forms.regulatory_scope_intents.map((item: any) => <div key={item.id}><b>{item.external_body || "Body pending"}</b><span>{item.service_type || "Service pending"}{item.jurisdiction ? ` · ${item.jurisdiction}` : ""}</span><span className="provenance-badge">{item.status.replaceAll("_", " ")}</span>{!readOnly && item.status !== "HUMAN_CONFIRMED_FOR_PROPOSAL" && <button className="text-button" onClick={() => void confirmRegulatory(item.id)}>Confirm for Proposal</button>}</div>)}</div> : <p className="muted">Regulatory scope is currently unknown. Add a canonical intent when commercial planning supports it.</p>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">EXPECTED CLIENT INPUTS</span><h3>Expected Client Inputs — Preliminary</h3></div><button className="text-button" onClick={() => void refreshInputs()} disabled={readOnly}>Refresh preview</button></div>{forms.expected_client_inputs ? <><p><span className="provenance-badge">{forms.expected_client_inputs.status.replaceAll("_", " ")}</span> {forms.expected_client_inputs.result_items?.length || 0} preliminary item(s)</p><small className="muted">Policy versions and evaluation time are pinned in details; this is not an authority checklist.</small></> : <p className="muted">No preliminary client-input preview has been generated.</p>}</section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">CLIENT REQUEST</span><h3>What the client asked us to do</h3></div><small>Client request ≠ AMEC Scope · source/manual provenance retained</small></div><div className="bd-form-grid"><label>Commercial Client<input value={fields.client_name || ""} onChange={(event) => update("client_name", event.target.value)} disabled={readOnly} /></label><label>Proposal Contact<input value={fields.attn_contact || ""} onChange={(event) => update("attn_contact", event.target.value)} disabled={readOnly} /></label><label className="wide">Project / Proposal Description<input value={fields.project_description || ""} onChange={(event) => update("project_description", event.target.value)} disabled={readOnly} /></label><label className="wide">Client Requested Scope<textarea value={fields.client_scope_of_work || ""} onChange={(event) => update("client_scope_of_work", event.target.value)} disabled={readOnly} /></label><label>Client Budget / Budget Indication<input value={fields.client_budget || ""} onChange={(event) => update("client_budget", event.target.value)} disabled={readOnly} placeholder="Not supplied" /></label><label>Requested Timing / Deadline<input value={fields.requested_timing || ""} onChange={(event) => update("requested_timing", event.target.value)} disabled={readOnly} placeholder="Not supplied" /></label><label className="wide">Client exclusions / constraints<textarea value={fields.client_constraints || ""} onChange={(event) => update("client_constraints", event.target.value)} disabled={readOnly} /></label><label className="wide">Additional information<textarea value={fields.additional_information || ""} onChange={(event) => update("additional_information", event.target.value)} disabled={readOnly} /></label><label className="wide">AMEC Scope · Engineering Preparation<textarea value={fields.scope_of_work || fields.sow || ""} onChange={(event) => update("scope_of_work", event.target.value)} disabled={readOnly} /></label><label className="wide">Process of Work · Engineering Preparation<textarea value={fields.process_of_work || ""} onChange={(event) => update("process_of_work", event.target.value)} disabled={readOnly} /></label><label>AMEC Proposal Price<input value={fields.price || ""} onChange={(event) => update("price", event.target.value)} disabled={readOnly} placeholder="Not recorded" /></label><label>Currency<input value={fields.currency || "QAR"} onChange={(event) => update("currency", event.target.value)} disabled={readOnly} /></label><label>AMEC Commercial Duration<input value={fields.duration || fields.period || ""} onChange={(event) => update("duration", event.target.value)} disabled={readOnly} placeholder="Later commercial review" /></label></div>{!readOnly && <button className="button-secondary" onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save client request"}</button>}</section>
      <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">NOTES &amp; CLIENT CONVERSATIONS</span><h3>Human-entered context</h3></div><small>Notes remain unverified context unless explicitly verified or accepted as an assumption.</small></div>{proposal.notes?.length ? <div className="bd-v2-list">{proposal.notes.map((note: any) => <div key={note.id}><b>{note.note_type.replaceAll("_", " ")}</b><span>{note.content}</span><small>{note.entered_by} · {new Date(note.created_at).toLocaleString()} · {note.status.replaceAll("_", " ")}</small></div>)}</div> : <p className="muted">No client conversation notes recorded.</p>}{!readOnly && <div className="bd-inline-add"><select aria-label="Note type" value={noteType} onChange={(event) => setNoteType(event.target.value)}><option value="CALL_NOTE">Call Note</option><option value="MEETING_NOTE">Meeting Note</option><option value="CLIENT_CLARIFICATION">Client Clarification</option><option value="INTERNAL_INTAKE">Internal Intake Note</option></select><input aria-label="Note content" placeholder="Record the conversation or clarification" value={noteContent} onChange={(event) => setNoteContent(event.target.value)} /><button className="button-secondary" onClick={() => void addNote()} disabled={noteBusy}>{noteBusy ? "Saving…" : "Add note"}</button></div>}</section>
      <section className="panel intake-readiness-panel"><div className="panel-head"><div><span className="eyebrow">INTAKE READINESS</span><h3>{readiness.ready ? "Ready for Engineering" : "Complete intake before Engineering"}</h3></div><button className="text-button" onClick={() => void validate()}>Recheck</button></div>{(readiness.blockers || []).length ? <div className="bd-gap-list blocker">{readiness.blockers.map((item: any) => <span key={item.code}>⚠ {item.label}</span>)}</div> : <div className="bd-gap-list"><span>✓ Client context sufficient</span><span>✓ Source evidence received and verified</span><span>✓ Proposal description captured</span><span>✓ Reference state valid</span></div>}{(readiness.warnings || []).map((item: any) => <div className="bd-gap-list warning" key={item.code}><span>⚠ {item.label}</span></div>)}{proposal.stage === "IN_REVIEW" || proposal.stage === "RECEIVED" ? <button className="button-primary" onClick={() => void proceed()} disabled={readOnly || !readiness.ready}>Proceed to Engineering Preparation</button> : <p className="muted">Next owner: {proposal.next_actor || "Engineering"}. The same Proposal identity continues through preparation.</p>}</section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">AMEC INPUT</span><h3>Human AMEC input</h3></div><small>Separate from source evidence · AI assist disabled</small></div><textarea className="bd-amec-input" value={amec} onChange={(event) => setAmec(event.target.value)} disabled={readOnly} /><p className="muted">AI assist is disabled. No suggestion or autonomous acceptance is generated.</p>{!readOnly && <button className="button-secondary" onClick={() => void save()}>Save AMEC Input</button>}</section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">VALIDATION &amp; GAPS</span><h3>{validation.ready ? "Ready for human Accept" : "Action required"}</h3></div><button className="text-button" onClick={() => void validate()}>Revalidate</button></div>{validation.blockers?.length ? <div className="bd-gap-list blocker"><b>Blockers</b>{validation.blockers.map((item: any) => <span key={item.code}>• {item.label}</span>)}</div> : <div className="inline-message">No blockers.</div>}{validation.warnings?.length ? <div className="bd-gap-list warning"><b>Warnings</b>{validation.warnings.map((item: any) => <span key={item.code}>• {item.label}</span>)}</div> : null}<p className="muted">Template: {validation.template?.item ? `${validation.template.item.ref} v${validation.template.item.version}` : "unresolved"} · Checklist: {validation.checklist?.item ? `${validation.checklist.item.ref} v${validation.checklist.item.version}` : "unresolved"}</p></section>
      <section className="panel bd-review-panel"><div><span className="eyebrow">REVIEW / ACCEPT / OUTPUTS</span><h3>Human control boundary</h3><p>Accept freezes this exact Proposal state and current Dashboard versions into an immutable revision.</p></div>{!readOnly && <button className="button-primary" onClick={() => void accept()} disabled={!validation.ready}>Accept Proposal revision</button>}{proposal.current_revision && <div className="bd-output-links"><a className="text-button" href={`/api/bd/proposals/${proposal.id}/outputs/proposal`}>Download Proposal</a><a className="text-button" href={`/api/bd/proposals/${proposal.id}/outputs/checklist`}>Download Checklist</a><a className="text-button" href={`/api/bd/proposals/${proposal.id}/handoff/contract`}>View Contract eligibility</a></div>}</section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">HISTORY</span><h3>Accepted revision history</h3></div><small>Immutable snapshots retained</small></div>{proposal.revision_history?.length ? <div className="bd-history-list">{proposal.revision_history.map((item: any) => <div className="bd-history-row" key={item.id}><b>Revision {item.revision_number}</b><span>{item.accepted_by}</span><span>{new Date(item.accepted_at).toLocaleString()}</span><code>{item.content_hash.slice(0, 16)}…</code></div>)}</div> : <p className="muted">No accepted revisions yet.</p>}</section>
    </div>
  </>;
}

function ProposalConfigurationPanel({ configuration, role }: { configuration?: any; role: Role }) {
  const template = configuration?.proposal_template;
  const checklist = configuration?.proposal_checklist;
  const definitions = configuration?.definitions;
  const engineering = configuration?.engineering_references;
  const managedLink = (item?: any) => item?.master_content_id ? `/dashboard?content=${encodeURIComponent(item.master_content_id)}` : "/dashboard";
  const card = (item: any) => <div className="operator-block" key={item.label}><b>{item.label}</b><span>{item.status === "READY" ? `${item.ref} v${item.version} · Current version` : item.message || "Needs Owner confirmation"}</span>{item.status === "READY" && <small>Managed in Dashboard · {item.purpose?.replaceAll("_", " ")}</small>}{item.status !== "READY" && role !== "RESPONSIBLE_ENGINEER" && <a className="text-button" href={managedLink(item)}>Manage in Dashboard →</a>}</div>;
  return <section className="panel proposal-configuration-panel"><div className="panel-head"><div><span className="eyebrow">PROPOSAL CONFIGURATION</span><h3>Managed in Dashboard</h3></div><small>BD consumes governed content; it does not edit the global master.</small></div><div className="two-col">{card(template)}{card(checklist)}</div><div className="two-col"><div className="operator-block"><b>Definitions</b><span>{definitions?.count || 0} applicable semantic definition(s)</span><small>Definitions explain meaning; Proposal fields remain client-specific transaction values.</small><a className="text-button" href="/dashboard#definitions">View definitions in Dashboard →</a></div><div className="operator-block"><b>Engineering references</b><span>{engineering?.status === "DEFERRED" ? "Available during Engineering Preparation" : `${engineering?.items?.length || 0} current eligible reference(s)`}</span><small>Engineering Works are resolved by the backend for the preparation stage.</small>{engineering?.status === "RESOLVED" && <a className="text-button" href="/dashboard">View sources in Dashboard →</a>}</div></div>{configuration?.accepted_revision && <p className="inline-message">Accepted revision {configuration.accepted_revision.revision_number} remains pinned to {configuration.accepted_revision.proposal_template.ref} v{configuration.accepted_revision.proposal_template.version} and {configuration.accepted_revision.proposal_checklist.ref} v{configuration.accepted_revision.proposal_checklist.version}.</p>}<p className="muted">{configuration?.stage1_requiredness || "Dashboard configuration is separate from Proposal source evidence."}</p></section>;
}
