import { useEffect, useState } from "react";
import { api } from "./api";

type CompletionRow = { id: string; project_number?: string; project_name?: string; case_reference?: string; subject_type: string; stage: string; readiness: string };
type Workspace = { case: { id: string; case_reference: string; status: string }; construction_context: { construction_execution_id: string; work_state: string; context_hash: string }; readiness: { result: string; stage: string; blockers: { code: string; message: string }[] }; baselines: { id: string; baseline_ref: string; version_number: number; status: string }[]; as_built_revisions: { id: string; revision_code: string; approval_status: string }[]; building_snapshots: { id: string; snapshot_type: string; snapshot_ref: string }[]; variances: { id: string; field_key: string; status: string; professional_disposition?: string }[]; requirements: { id: string; status: string; applicability: string }[]; forms: { id: string; status: string }[]; packages: { id: string; state: string }[]; cycles: { id: string; cycle_number: number; status: string }[]; findings: { id: string; title: string; status: string }[]; outcomes: { id: string; outcome_type: string; external_identifier?: string }[] };
type Project = { id: string; project_number: string; project_name: string };
type Execution = { id: string; project_id: string; execution_ref: string; title: string; work_state: string };
const pretty = (value: string) => value.replaceAll("_", " ");

export function CompletionPage() {
  const [rows, setRows] = useState<CompletionRow[]>([]); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [executions, setExecutions] = useState<Execution[]>([]); const [selectedProject, setSelectedProject] = useState(""); const [selectedExecution, setSelectedExecution] = useState(""); const [error, setError] = useState("");
  const [path, setPath] = useState(window.location.pathname); const detailId = path.startsWith("/completion/") && path !== "/completion/new" ? path.split("/")[2] : ""; const isNew = path === "/completion/new";
  useEffect(() => { const syncRoute = () => { setPath(window.location.pathname); setWorkspace(null); }; window.addEventListener("popstate", syncRoute); return () => window.removeEventListener("popstate", syncRoute); }, []);
  const load = async () => { try { setError(""); if (detailId) setWorkspace(await api<Workspace>(`/api/completion/${detailId}`)); else if (!isNew) setRows(await api<CompletionRow[]>("/api/completion")); else { const [p, e] = await Promise.all([api<Project[]>("/api/projects"), api<Execution[]>("/api/construction")]); setProjects(p); setExecutions(e.filter((item) => !["NOT_STARTED", "WORK_ACTIVE"].includes(item.work_state))); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Completion data unavailable"); } };
  useEffect(() => { void load(); }, [detailId, isNew]);
  const navigate = (next: string) => { window.history.pushState({}, "", next); window.dispatchEvent(new PopStateEvent("popstate")); };
  const start = async () => { const project = projects.find((item) => item.id === selectedProject); if (!project || !selectedExecution) return; try { const result = await api<Workspace>("/api/completion/start", { method: "POST", body: JSON.stringify({ project_id: project.id, construction_execution_id: selectedExecution, subject_type: "Project", subject_id: project.id, idempotency_key: `ui-completion-${project.id}-${selectedExecution}` }) }); navigate(`/completion/${result.case.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Completion start failed"); } };
  if (detailId && workspace) return <CompletionWorkspace workspace={workspace} onBack={() => navigate("/completion")} />;
  if (isNew) return <div className="completion-page"><div className="completion-banner"><strong>Human-gated Completion / As-Built</strong><span>Construction never auto-creates a Completion case. Start is an explicit Owner action.</span></div><section className="panel completion-card"><span className="eyebrow">START COMPLETION</span><h2>Choose a completed construction scope</h2><label>Project<select value={selectedProject} onChange={(event) => { setSelectedProject(event.target.value); setSelectedExecution(""); }}><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.project_number} · {project.project_name}</option>)}</select></label><label>Construction execution<select value={selectedExecution} onChange={(event) => setSelectedExecution(event.target.value)}><option value="">Select execution</option>{executions.filter((item) => !selectedProject || item.project_id === selectedProject).map((execution) => <option key={execution.id} value={execution.id}>{execution.execution_ref} · {pretty(execution.work_state)}</option>)}</select></label><button className="button primary" disabled={!selectedProject || !selectedExecution} onClick={() => void start()}>Start Completion / As-Built</button>{error && <p className="error-copy">{error}</p>}</section></div>;
  return <div className="completion-page"><div className="completion-banner"><strong>Completion / As-Built</strong><span>As-Built upload, professional approval, authority Completion, Handover, and settlement are separate states.</span></div><div className="section-heading"><div><span className="eyebrow">OWNER WORKSPACE</span><h2>Completion scopes</h2></div><button className="button primary" onClick={() => navigate("/completion/new")}>Start Completion</button></div>{error && <p className="error-copy">{error}</p>}{rows.length === 0 ? <section className="panel completion-empty"><h3>No Completion cases</h3><p>Start a Completion / As-Built workflow from a completed Construction handoff.</p></section> : <div className="completion-list">{rows.map((row) => <button className="completion-list-item" key={row.id} onClick={() => navigate(`/completion/${row.id}`)}><span><strong>{row.case_reference || "Completion case"}</strong><small>{row.project_number} · {row.project_name}</small></span><span className="completion-stage">{pretty(row.stage)}</span><span className="completion-status">{pretty(row.readiness)}</span></button>)}</div>}</div>;
}

function CompletionWorkspace({ workspace, onBack }: { workspace: Workspace; onBack: () => void }) {
  const card = (title: string, value: string) => <section className="panel completion-section"><span className="eyebrow">{title}</span><strong>{value}</strong></section>;
  return <div className="completion-page"><button className="button ghost" onClick={onBack}>← Completion list</button><div className="completion-banner"><strong>Human checkpoints remain active</strong><span>Proceed advances to an eligible validated step; it never means Authority Approved.</span></div><section className="panel completion-overview"><div><span className="eyebrow">{workspace.case.case_reference}</span><h2>Completion / As-Built workspace</h2><p>Case {workspace.case.status} · {pretty(workspace.readiness.stage)}</p></div><span className="completion-status">{pretty(workspace.readiness.result)}</span></section><div className="completion-grid">{card("Construction handoff", pretty(workspace.construction_context.work_state))}{card("As-Built baseline", workspace.baselines.length ? `${workspace.baselines[0].baseline_ref} · ${pretty(workspace.baselines[0].status)}` : "Not created")}{card("Building snapshots", `${workspace.building_snapshots.length} pinned`)}{card("Requirements", `${workspace.requirements.length} case-specific`)}</div><div className="completion-grid">{card("As-Built engineering", `${workspace.as_built_revisions.length} revision(s)`)}{card("Variance review", `${workspace.variances.filter((item) => item.status !== "DISPOSITIONED").length} open`)}{card("Forms / reports", `${workspace.forms.length} form(s)`)}{card("Submission history", `${workspace.cycles.length} cycle(s)`)}</div><section className="panel completion-detail"><h3>Readiness blockers</h3>{workspace.readiness.blockers.length ? workspace.readiness.blockers.map((blocker) => <div className="completion-blocker" key={blocker.code}><strong>{pretty(blocker.code)}</strong><span>{blocker.message}</span></div>) : <p>No blockers recorded.</p>}<h3>Outcome</h3><p>{workspace.outcomes.length ? `Verified ${workspace.outcomes[0].outcome_type}` : "No verified Completion outcome"}. Handover writes: none.</p></section></div>;
}
