import { useEffect, useState } from "react";
import { api } from "./api";
import { Icon } from "./Icon";

type CompletionRow = { id: string; project_number?: string; project_name?: string; case_reference?: string; subject_type: string; stage: string; readiness: string };
type Workspace = { case: { id: string; case_reference: string; status: string; started_at?: string }; link?: { subject_type?: string; subject_id?: string }; construction_context: { construction_execution_id: string; work_state: string; context_hash: string; party_snapshot?: { party_id: string; role_code?: string; status?: string }[]; source_snapshot_json?: Record<string, unknown> }; readiness: { result: string; stage: string; blockers: { code: string; message: string }[] }; baselines: { id: string; baseline_ref: string; version_number: number; status: string; manifest_hash?: string }[]; as_built_revisions: { id: string; revision_code: string; approval_status: string; deliverable_id?: string }[]; building_assets?: { id: string; asset_ref: string; name: string; building_type?: string }[]; building_snapshots: { id: string; building_asset_id?: string; snapshot_type: string; snapshot_ref: string; version_number?: number; created_by?: string }[]; variances: { id: string; field_key: string; status: string; professional_disposition?: string; requires_design_change?: boolean }[]; requirements: { id: string; status: string; applicability: string; requirement_definition_id?: string }[]; forms: { id: string; status: string; form_code?: string }[]; packages: { id: string; state: string; manifest_hash?: string }[]; cycles: { id: string; cycle_number: number; status: string }[]; findings: { id: string; title: string; status: string; category?: string }[]; outcomes: { id: string; outcome_type: string; external_identifier?: string; status?: string }[] };
type Project = { id: string; project_number: string; project_name: string };
type Execution = { id: string; project_id: string; execution_ref: string; title: string; work_state: string };
const pretty = (value: string) => value.replaceAll("_", " ");

export function CompletionPage() {
  const [rows, setRows] = useState<CompletionRow[]>([]); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [executions, setExecutions] = useState<Execution[]>([]); const [selectedProject, setSelectedProject] = useState(""); const [selectedExecution, setSelectedExecution] = useState(""); const [error, setError] = useState("");
  const [path, setPath] = useState(window.location.pathname); const detailId = path.startsWith("/completion/") && path !== "/completion/new" ? path.split("/")[2] : ""; const isNew = path === "/completion/new";
  useEffect(() => { const syncRoute = () => { setPath(window.location.pathname); setWorkspace(null); }; window.addEventListener("popstate", syncRoute); return () => window.removeEventListener("popstate", syncRoute); }, []);
  const load = async () => { try { setError(""); if (detailId) setWorkspace(await api<Workspace>(`/api/completion/${detailId}`)); else if (!isNew) setRows(await api<CompletionRow[]>("/api/completion")); else { const [p, e] = await Promise.all([api<Project[]>("/api/projects"), api<Execution[]>("/api/construction")]); setProjects(p); setExecutions(e.filter((item) => !["NOT_STARTED", "WORK_ACTIVE"].includes(item.work_state))); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Completion data unavailable"); } };
  useEffect(() => { void load(); }, [detailId, isNew]);
  const navigate = (next: string) => { window.history.pushState({}, "", next); window.dispatchEvent(new PopStateEvent("popstate")); };
  const start = async () => { const project = projects.find((item) => item.id === selectedProject); if (!project || !selectedExecution) return; try { const result = await api<Workspace>("/api/completion/start", { method: "POST", body: JSON.stringify({ project_id: project.id, construction_execution_id: selectedExecution, subject_type: "Project", subject_id: project.id, idempotency_key: `ui-completion-${project.id}-${selectedExecution}` }) }); navigate(`/completion/${result.case.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Completion start failed"); } };
  if (detailId && workspace) return <CompletionWorkspace workspace={workspace} onBack={() => navigate("/completion")} onRefresh={() => void load()} />;
  if (isNew) return <div className="completion-page"><div className="completion-banner"><strong>Human-gated Completion / As-Built</strong><span>Construction never auto-creates a Completion case. Start is an explicit Owner action.</span></div><section className="panel completion-card"><span className="eyebrow">START COMPLETION</span><h2>Choose a completed construction scope</h2><label>Project<select value={selectedProject} onChange={(event) => { setSelectedProject(event.target.value); setSelectedExecution(""); }}><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.project_number} · {project.project_name}</option>)}</select></label><label>Construction execution<select value={selectedExecution} onChange={(event) => setSelectedExecution(event.target.value)}><option value="">Select execution</option>{executions.filter((item) => !selectedProject || item.project_id === selectedProject).map((execution) => <option key={execution.id} value={execution.id}>{execution.execution_ref} · {pretty(execution.work_state)}</option>)}</select></label><button className="button primary" disabled={!selectedProject || !selectedExecution} onClick={() => void start()}>Start Completion / As-Built</button>{error && <p className="error-copy">{error}</p>}</section></div>;
  return <div className="completion-page"><div className="completion-banner"><Icon name="shield" size={17} /><span>As-Built upload, professional approval, authority Completion, Handover, and settlement are separate states.</span></div><div className="section-heading"><div><span className="eyebrow">OWNER WORKSPACE</span><h2>Completion scopes</h2></div>{rows.length > 0 && <button className="button primary" onClick={() => navigate("/completion/new")}>Start Completion</button>}</div>{error && <p className="error-copy">{error}</p>}{rows.length === 0 ? <section className="panel completion-empty"><div className="empty-state-icon"><Icon name="empty" size={22} /></div><div><h3>No Completion cases</h3><p>Completion begins from an eligible completed Construction handoff. Once started, the canonical Completion / As-Built workspace appears here.</p></div><button className="button primary" onClick={() => navigate("/completion/new")}>Start Completion</button></section> : <div className="completion-list">{rows.map((row) => <button className="completion-list-item" key={row.id} onClick={() => navigate(`/completion/${row.id}`)}><span><strong>{row.case_reference || "Completion case"}</strong><small>{row.project_number} · {row.project_name}</small></span><span className="completion-stage">{pretty(row.stage)}</span><span className="completion-status">{pretty(row.readiness)}</span></button>)}</div>}</div>;
}

function CompletionWorkspace({ workspace, onBack, onRefresh }: { workspace: Workspace; onBack: () => void; onRefresh: () => void }) {
  const [active, setActive] = useState("overview");
  const [assetRef, setAssetRef] = useState("");
  const [assetName, setAssetName] = useState("");
  const [actionError, setActionError] = useState("");
  const assets = workspace.building_assets || [];
  const sections = [
    ["overview", "Overview"], ["handoff", "Construction Handoff"], ["parties", "Parties"],
    ["drawings", "As-Built Drawings"], ["building", "Building / Property"], ["variance", "Variance Review"],
    ["requirements", "Requirements / Evidence"], ["forms", "Forms"], ["reports", "Reports"],
    ["preparation", "Preparation / Precheck"], ["submission", "Submission History"],
    ["findings", "Authority Findings"], ["outcome", "Completion Outcome"], ["history", "History"],
  ];
  const card = (title: string, value: string) => <section className="panel completion-section"><span className="eyebrow">{title}</span><strong>{value}</strong></section>;
  const runAction = async (action: () => Promise<unknown>) => { try { setActionError(""); await action(); onRefresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Completion action failed"); } };
  const addAsset = () => runAction(async () => { if (!assetRef || !assetName) return; await api(`/api/completion/${workspace.case.id}/building-assets`, { method: "POST", body: JSON.stringify({ asset_ref: assetRef, name: assetName }) }); setAssetRef(""); setAssetName(""); });
  const addSnapshot = (assetId: string) => runAction(() => api(`/api/completion/${workspace.case.id}/building-snapshots`, { method: "POST", body: JSON.stringify({ building_asset_id: assetId, snapshot_type: "AS_BUILT", verified_by: "HUMAN_ENGINEERING_REVIEW" }) }));
  const renderSection = () => {
    if (active === "overview") return <><div className="completion-grid">{card("Construction handoff", pretty(workspace.construction_context.work_state))}{card("As-Built baseline", workspace.baselines.length ? `${workspace.baselines[0].baseline_ref} · ${pretty(workspace.baselines[0].status)}` : "Not created")}{card("Building snapshots", `${workspace.building_snapshots.length} pinned`)}{card("Requirements", `${workspace.requirements.length} case-specific`)}</div><div className="completion-grid">{card("As-Built engineering", `${workspace.as_built_revisions.length} revision(s)`)}{card("Variance review", `${workspace.variances.filter((item) => item.status !== "DISPOSITIONED").length} open`)}{card("Forms / reports", `${workspace.forms.length} form(s)`)}{card("Submission history", `${workspace.cycles.length} cycle(s)`)}</div><section className="panel completion-detail"><h3>Readiness blockers</h3>{workspace.readiness.blockers.length ? workspace.readiness.blockers.map((blocker) => <div className="completion-blocker" key={blocker.code}><strong>{pretty(blocker.code)}</strong><span>{blocker.message}</span></div>) : <p>No blockers recorded.</p>}<h3>Next safe actions</h3><p>Accept means approve the specific AsBuiltBaseline or report in context. Proceed means move to Preparation lock, precheck, or human submit authorization. It never means Authority Approved.</p></section></>;
    if (active === "handoff") return <section className="panel completion-detail"><h3>Construction Handoff</h3><p>Read-only context from execution <code>{workspace.construction_context.construction_execution_id}</code>.</p><dl className="completion-facts"><dt>Work state</dt><dd>{pretty(workspace.construction_context.work_state)}</dd><dt>Context hash</dt><dd>{workspace.construction_context.context_hash}</dd><dt>Open issues</dt><dd>{String((workspace.construction_context.source_snapshot_json?.open_issue_ids as unknown[] | undefined)?.length || 0)}</dd><dt>Open obligations</dt><dd>{String((workspace.construction_context.source_snapshot_json?.open_obligation_ids as unknown[] | undefined)?.length || 0)}</dd></dl></section>;
    if (active === "parties") return <section className="panel completion-detail"><h3>Parties and scoped roles</h3>{(workspace.construction_context.party_snapshot || []).length ? (workspace.construction_context.party_snapshot || []).map((party) => <div className="completion-row" key={party.party_id}><strong>{party.role_code || "Scoped party"}</strong><span>{party.party_id} · {party.status || "ACTIVE"}</span></div>) : <p>No party assignments were carried into this handoff.</p>}</section>;
    if (active === "drawings") return <section className="panel completion-detail"><h3>As-Built Drawings</h3><p>Uploaded and reviewed engineering revisions remain distinct from professional approval and authority outcome.</p>{workspace.as_built_revisions.length ? workspace.as_built_revisions.map((revision) => <div className="completion-row" key={revision.id}><strong>{revision.revision_code}</strong><span>{pretty(revision.approval_status)} · {revision.deliverable_id || revision.id}</span></div>) : <p>No As-Built revision has been registered.</p>}</section>;
    if (active === "building") return <><section className="panel completion-detail"><h3>Building / Property</h3><p>Building assets and immutable snapshots are scoped to this project.</p><div className="completion-inline-form"><input aria-label="Asset reference" placeholder="Asset reference" value={assetRef} onChange={(event) => setAssetRef(event.target.value)} /><input aria-label="Asset name" placeholder="Building name" value={assetName} onChange={(event) => setAssetName(event.target.value)} /><button className="button primary" onClick={addAsset}>Add building asset</button></div>{assets.map((asset) => <div className="completion-row" key={asset.id}><span><strong>{asset.asset_ref}</strong> · {asset.name}</span><button className="button ghost" onClick={() => addSnapshot(asset.id)}>Record AS_BUILT snapshot</button></div>)}</section><section className="panel completion-detail"><h3>Snapshot ledger</h3>{workspace.building_snapshots.length ? workspace.building_snapshots.map((snapshot) => <div className="completion-row" key={snapshot.id}><strong>{snapshot.snapshot_ref}</strong><span>{pretty(snapshot.snapshot_type)} · v{snapshot.version_number || 1} · immutable</span></div>) : <p>No snapshots recorded.</p>}</section></>;
    if (active === "variance") return <section className="panel completion-detail"><h3>Variance Review</h3><p>A difference is not automatically a violation. Professional disposition and any DesignChangeRequest or authority modification remain human decisions.</p>{workspace.variances.length ? workspace.variances.map((variance) => <div className="completion-row" key={variance.id}><strong>{variance.field_key}</strong><span>{pretty(variance.status)} · {variance.professional_disposition ? pretty(variance.professional_disposition) : "Awaiting professional disposition"}</span></div>) : <p>No comparison variances recorded.</p>}</section>;
    if (active === "requirements") return <section className="panel completion-detail"><h3>Requirements / Evidence</h3>{workspace.requirements.length ? workspace.requirements.map((requirement) => <div className="completion-row" key={requirement.id}><strong>{requirement.requirement_definition_id || requirement.id}</strong><span>{pretty(requirement.status)} · {pretty(requirement.applicability)}</span></div>) : <p>Requirements are not initialized for this Completion case. NO_POLICY does not invent requirements.</p>}</section>;
    if (active === "forms") return <section className="panel completion-detail"><h3>Forms</h3>{workspace.forms.length ? workspace.forms.map((form) => <div className="completion-row" key={form.id}><strong>{form.form_code || form.id}</strong><span>{pretty(form.status)}</span></div>) : <p>No Completion Form instance. Authority-only fields remain blank until a governed source and human entry exist.</p>}</section>;
    if (active === "reports") return <section className="panel completion-detail"><h3>Reports</h3><p>Reports are generated artifacts, not canonical truth. This workspace exposes report readiness only after source evidence and approvals are present.</p><div className="completion-row"><strong>Readiness report</strong><span>{workspace.baselines.length ? "Baseline context available" : "Waiting for approved AsBuiltBaseline"}</span></div></section>;
    if (active === "preparation") return <section className="panel completion-detail"><h3>Preparation / Precheck</h3>{workspace.packages.length ? workspace.packages.map((pkg) => <div className="completion-row" key={pkg.id}><strong>Package {pkg.id}</strong><span>{pretty(pkg.state)}{pkg.manifest_hash ? ` · ${pkg.manifest_hash}` : ""}</span></div>) : <p>Preparation is unavailable until an approved AsBuiltBaseline exists. Lock pins the exact baseline and does not follow later revisions.</p>}<div className="completion-row"><strong>Precheck</strong><span>{pretty(workspace.readiness.result)} · human review required</span></div></section>;
    if (active === "submission") return <section className="panel completion-detail"><h3>Submission History</h3>{workspace.cycles.length ? workspace.cycles.map((cycle) => <div className="completion-row" key={cycle.id}><strong>Cycle {cycle.cycle_number}</strong><span>{pretty(cycle.status)}</span></div>) : <p>No SubmissionCycle exists. Authorization and external confirmation are separate idempotent actions.</p>}</section>;
    if (active === "findings") return <section className="panel completion-detail"><h3>Authority Findings</h3>{workspace.findings.length ? workspace.findings.map((finding) => <div className="completion-row" key={finding.id}><strong>{finding.title}</strong><span>{pretty(finding.status)} · {finding.category || "OTHER"}</span></div>) : <p>No Completion-specific finding copy exists; findings remain canonical AuthorityCaseFinding records.</p>}</section>;
    if (active === "outcome") return <section className="panel completion-detail"><h3>Completion Outcome</h3>{workspace.outcomes.length ? workspace.outcomes.map((outcome) => <div className="completion-row" key={outcome.id}><strong>{pretty(outcome.outcome_type)}</strong><span>{pretty(outcome.status || "VERIFIED")} · {outcome.external_identifier || "external reference recorded"}</span></div>) : <p>No verified Completion outcome. A report, file, or internal state cannot infer a certificate.</p>}<div className="completion-row"><strong>Handover</strong><span>No HandoverPackage is created by Completion.</span></div></section>;
    return <section className="panel completion-detail"><h3>History</h3><div className="completion-row"><strong>Case opened</strong><span>{workspace.case.started_at || "Recorded in audit history"}</span></div><div className="completion-row"><strong>Readiness stage</strong><span>{pretty(workspace.readiness.stage)} · {pretty(workspace.readiness.result)}</span></div><div className="completion-row"><strong>Baseline revisions</strong><span>{workspace.baselines.length} immutable record(s)</span></div></section>;
  };
  return <div className="completion-page"><button className="button ghost" onClick={onBack}><Icon name="arrow-left" size={14} /> Completion list</button><div className="completion-banner"><strong>Human checkpoints remain active</strong><span>Proceed advances to an eligible validated step; it never means Authority Approved.</span></div><section className="panel completion-overview"><div><span className="eyebrow">{workspace.case.case_reference}</span><h2>Completion / As-Built workspace</h2><p>Case {workspace.case.status} · {pretty(workspace.readiness.stage)} · {workspace.link?.subject_type || "Project"}</p></div><span className="completion-status">{pretty(workspace.readiness.result)}</span></section><nav className="completion-tabs" aria-label="Completion workspace sections">{sections.map(([id, label]) => <button key={id} className={`completion-tab ${active === id ? "active" : ""}`} onClick={() => setActive(id)}>{label}</button>)}</nav>{actionError && <p className="error-copy">{actionError}</p>}{renderSection()}</div>;
}
