import { useEffect, useState } from "react";
import { api } from "./api";
import { Icon } from "./Icon";

type PackageRow = { id: string; package_ref: string; project_id: string; service_engagement_id: string; status: string; current_revision_id?: string };
type Workspace = { package: PackageRow; revision?: { id: string; revision_number: number; status: string; contract_revision_id: string }; readiness?: { state: string; digital_ready: boolean; physical_ready: boolean; checks_json: { kind: string; ready: boolean; medium?: string }[] }; items: { id: string; label: string; status: string; required_renditions_json: string[]; available_renditions_json: string[] }[]; requirements: { id: string; medium: string; copy_count: number; acknowledgement_required: boolean }[]; distributions: { id: string; status: string; medium: string; delivery_reference?: string }[]; receipts: { id: string; received_by_ref: string }[]; participants: { id: string; participant_ref: string; participant_role: string }[]; punch: { id: string; remark: string; status: string; blocking: boolean }[]; acceptance?: { acceptance_status: string; evidence_reference?: string }; axes: Record<string, string> };
const pretty = (value: string) => value.replaceAll("_", " ");

export function HandoverPage() {
  const [path, setPath] = useState(window.location.pathname);
  const [rows, setRows] = useState<PackageRow[]>([]);
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [error, setError] = useState("");
  const detailId = path.startsWith("/handover/") ? path.split("/")[2] : "";
  const navigate = (next: string) => { window.history.pushState({}, "", next); window.dispatchEvent(new PopStateEvent("popstate")); };
  const load = async () => { try { setError(""); if (detailId) setWorkspace(await api<Workspace>(`/api/handover/${detailId}`)); else setRows((await api<{ items: PackageRow[] }>("/api/handover")).items); } catch (cause) { setError(cause instanceof Error ? cause.message : "Handover data unavailable"); } };
  useEffect(() => { const sync = () => { setPath(window.location.pathname); setWorkspace(null); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  useEffect(() => { void load(); }, [detailId]);
  if (detailId && workspace) return <HandoverWorkspace workspace={workspace} onBack={() => navigate("/handover")} onRefresh={() => void load()} />;
  return <div className="handover-page"><div className="handover-banner"><strong>Handover / Admin Closeout</strong><span>Service-scoped, human-authorized, evidence-backed closure. No portal writes or automatic project closure.</span></div><div className="section-heading"><div><span className="eyebrow">OWNER WORKSPACE</span><h2>Handover packages</h2><p>Package readiness, physical custody, external acceptance, service scope closure, and downstream closeout axes remain separate.</p></div></div>{error && <p className="error-copy">{error}</p>}{rows.length ? <div className="handover-list">{rows.map((row) => <button className="handover-list-item" key={row.id} onClick={() => navigate(`/handover/${row.id}`)}><span><strong>{row.package_ref}</strong><small>Project {row.project_id} · Service {row.service_engagement_id}</small></span><span className="handover-status">{pretty(row.status)}</span><span className="handover-status">Open workspace <Icon name="arrow-up-right" size={14} /></span></button>)}</div> : <section className="panel handover-empty"><h3>No HandoverPackage exists</h3><p>Handover starts only from an exact finalized ContractRevision and ServiceEngagement scope. Completion does not create a package automatically.</p><span className="handover-token">HANDOVER_FORM_SOURCE_AND_POLICY_REVIEW_REQUIRED</span></section>}</div>;
}

function HandoverWorkspace({ workspace, onBack, onRefresh }: { workspace: Workspace; onBack: () => void; onRefresh: () => void }) {
  const [active, setActive] = useState("overview");
  const [actionError, setActionError] = useState("");
  const sections = [["overview", "Overview"], ["service", "Service Scope"], ["manifest", "Manifest"], ["physical", "Physical Media"], ["participants", "Participants"], ["punch", "Punch & Remarks"], ["distribution", "Distribution"], ["acceptance", "Acceptance"], ["service-close", "Service Close"], ["contract", "Contract / Admin Close"], ["financial", "Financial Settlement"], ["regulatory", "Regulatory Closeout"], ["archive", "Project Archive"], ["history", "History"]];
  const action = async (path: string, body?: unknown) => { try { setActionError(""); await api(path, { method: "POST", body: body ? JSON.stringify(body) : undefined }); onRefresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Human action could not be recorded"); } };
  const card = (title: string, value: string) => <section className="panel handover-section"><span className="eyebrow">{title}</span><strong>{value}</strong></section>;
  const render = () => {
    if (active === "overview") return <><div className="handover-grid">{card("Package", workspace.package.package_ref)}{card("Revision", workspace.revision ? `HP${workspace.revision.revision_number} · ${pretty(workspace.revision.status)}` : "Not initialized")}{card("Readiness", workspace.readiness ? pretty(workspace.readiness.state) : "Not assessed")}{card("Project auto-close", "Never")}</div><section className="panel handover-detail"><h3>Human gates</h3><p>Release, distribution, receipt, external acceptance, service closure, contract administration, financial settlement, regulatory assessment, and project archive are distinct events.</p>{workspace.readiness?.checks_json.map((check, index) => <div className="handover-row" key={`${check.kind}-${index}`}><strong>{pretty(check.kind)}</strong><span>{check.ready ? "Ready" : "Needs review"}{check.medium ? ` · ${check.medium}` : ""}</span></div>)}</section></>;
    if (active === "service") return <section className="panel handover-detail"><h3>Exact service scope</h3><p>ServiceEngagement <code>{workspace.package.service_engagement_id}</code> under project <code>{workspace.package.project_id}</code>. Contract lineage is pinned by the exact ContractRevision <code>{workspace.revision?.contract_revision_id || "—"}</code>.</p><div className="handover-row"><strong>Service axis</strong><span>{pretty(workspace.axes.service_scope || "NEEDS_REVIEW")}</span></div></section>;
    if (active === "manifest") return <section className="panel handover-detail"><h3>Immutable manifest and renditions</h3>{workspace.items.length ? workspace.items.map((item) => <div className="handover-row" key={item.id}><strong>{item.label}</strong><span>{pretty(item.status)} · required {item.required_renditions_json.join(", ") || "none"} · available {item.available_renditions_json.join(", ") || "none"}</span></div>) : <p>No manifest items. A blank source handover form cannot satisfy this gate.</p>}</section>;
    if (active === "physical" || active === "distribution") return <section className="panel handover-detail"><h3>Physical / digital distribution</h3>{workspace.requirements.map((item) => <div className="handover-row" key={item.id}><strong>{item.medium}</strong><span>{item.copy_count} copy · acknowledgement {item.acknowledgement_required ? "required" : "not required"}</span></div>)}{workspace.distributions.map((item) => <div className="handover-row" key={item.id}><strong>Delivery {item.medium}</strong><span>{pretty(item.status)} · {item.delivery_reference || "no reference"}</span></div>)}<p>Delivery is not receipt. Physical custody is not inferred from a digital render.</p></section>;
    if (active === "participants") return <section className="panel handover-detail"><h3>Scoped participants</h3>{workspace.participants.length ? workspace.participants.map((item) => <div className="handover-row" key={item.id}><strong>{item.participant_role}</strong><span>{item.participant_ref}</span></div>) : <p>No participant snapshot has been pinned.</p>}</section>;
    if (active === "punch") return <section className="panel handover-detail"><h3>Handover punch and remarks</h3>{workspace.punch.length ? workspace.punch.map((item) => <div className="handover-row" key={item.id}><strong>{item.blocking ? "Blocking" : "Remark"}</strong><span>{item.remark} · {pretty(item.status)}</span></div>) : <p>No HandoverPunchItem records.</p>}</section>;
    if (active === "acceptance") return <section className="panel handover-detail"><h3>External acceptance</h3><div className="handover-row"><strong>Acceptance</strong><span>{workspace.acceptance ? pretty(workspace.acceptance.acceptance_status) : "Not recorded"}</span></div><div className="handover-row"><strong>Receipts</strong><span>{workspace.receipts.length} receipt(s); receipt is not acceptance</span></div></section>;
    if (active === "service-close") return <section className="panel handover-detail"><h3>Service Scope Closure</h3><p>Explicit human close for this ServiceEngagement only. Other services on the same Contract may remain active.</p><button className="button primary" onClick={() => void action(`/api/handover/${workspace.package.id}/service-close`)}>Record service-scope close</button></section>;
    if (active === "contract") return <section className="panel handover-detail"><h3>Contract Administrative Closure</h3><p>Blocked until every scoped ServiceEngagement is closed. It does not settle invoices or archive the project.</p><button className="button primary" onClick={() => void action(`/api/handover/${workspace.package.id}/contract-admin-close`)}>Record contract admin close</button></section>;
    if (active === "financial") return <section className="panel handover-detail"><h3>Financial Settlement</h3><p>Billing remains read-only here. Invoice Paid, zero receivable, and settlement are not interchangeable states.</p><button className="button ghost" onClick={() => void action(`/api/handover/projects/${workspace.package.project_id}/financial-settlement`, { basis: "OWNER_REVIEW" })}>Record human settlement</button></section>;
    if (active === "regulatory") return <section className="panel handover-detail"><h3>Regulatory Closeout Assessment</h3><p>Assessment is derived from case evidence and never mutates AuthorityCase state. A Completion Certificate is not a universal close signal.</p><div className="handover-row"><strong>Axis</strong><span>{pretty(workspace.axes.regulatory || "NEEDS_REVIEW")}</span></div></section>;
    if (active === "archive") return <section className="panel handover-detail"><h3>Project Closeout / Archive</h3><p>Archive is an explicit, non-destructive human event. Synology/SOR properties and raw paths are preserved.</p><div className="handover-row"><strong>Archive axis</strong><span>{pretty(workspace.axes.archive || "NOT_ARCHIVED")}</span></div></section>;
    return <section className="panel handover-detail"><h3>Immutable event history</h3><p>Each revision, distribution, receipt, acceptance, closeout assessment, and authorization is retained as an auditable event.</p></section>;
  };
  return <div className="handover-page"><button className="button ghost" onClick={onBack}><Icon name="arrow-left" size={14} /> Handover packages</button><div className="handover-banner"><strong>Human checkpoints remain active</strong><span>Evidence-backed state only. No auto-sign, auto-stamp, portal submission, or project archive.</span></div><section className="panel handover-overview"><div><span className="eyebrow">{workspace.package.package_ref}</span><h2>Handover / Admin Closeout workspace</h2><p>Service {workspace.package.service_engagement_id} · Project {workspace.package.project_id}</p></div><span className="handover-status">{pretty(workspace.package.status)}</span></section><nav className="handover-tabs" aria-label="Handover workspace sections">{sections.map(([id, label]) => <button key={id} className={`handover-tab ${active === id ? "active" : ""}`} onClick={() => setActive(id)}>{label}</button>)}</nav>{actionError && <p className="error-copy">{actionError}</p>}{render()}</div>;
}
