import { useEffect, useMemo, useState } from "react";
import { api } from "./api";

type Project = { number: number; name: string; state: string; folder_count: number; file_count: number };
type Entry = { id: string; path: string; name: string; is_directory: boolean; size: number; modified_ns: number; content_type: string };

const roleHeaders = (role: string) => ({ "X-Dev-Role": role });
const formatSize = (size: number) => size < 1024 ? `${size} B` : size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`;

export function ProposalSourceWorkspace({ role = "OWNER_SPONSOR", onBack }: { role?: string; onBack?: () => void }) {
  const [projects, setProjects] = useState<Project[]>([]); const [selected, setSelected] = useState(454); const [entries, setEntries] = useState<Entry[]>([]); const [activeFolder, setActiveFolder] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [preview, setPreview] = useState(""); const [loading, setLoading] = useState(false);
  const loadProjects = () => api<any>("/api/proposals/sources/2026/projects", { headers: roleHeaders(role) }).then((data) => setProjects(data.projects || [])).catch((cause) => setError(cause instanceof Error ? cause.message : "Source projects unavailable."));
  const loadTree = () => { setLoading(true); setPreview(""); setActiveFolder(""); api<any>(`/api/proposals/sources/2026/projects/${selected}/tree`, { headers: roleHeaders(role) }).then((data) => setEntries(data.entries || [])).catch((cause) => setError(cause instanceof Error ? cause.message : "Source tree unavailable.")).finally(() => setLoading(false)); };
  useEffect(() => { void loadProjects(); }, [role]); useEffect(() => { void loadTree(); }, [selected]);
  const sync = async () => { try { const data = await api<any>("/api/proposals/sources/2026/sync", { method: "POST", headers: roleHeaders(role) }); setMessage(`Sync complete: ${data.runs?.map((run: any) => `${run.project_number}: ${run.captured_count} new, ${run.unchanged_count} unchanged`).join(" · ")}`); await loadProjects(); await loadTree(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Sync failed."); } };
  const files = useMemo(() => entries.filter((entry) => !entry.is_directory && (!activeFolder || entry.path.startsWith(`${activeFolder}/`))), [entries, activeFolder]);
  const folders = useMemo(() => entries.filter((entry) => entry.is_directory), [entries]);
  const openFile = async (entry: Entry) => { try { const response = await fetch(`/api/proposals/sources/2026/projects/${selected}/files/${entry.id}/content`, { headers: roleHeaders(role) }); if (!response.ok) throw new Error(await response.text()); const blob = await response.blob(); if (entry.content_type.startsWith("image/") || entry.content_type === "application/pdf") setPreview(URL.createObjectURL(blob)); else { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = entry.name; link.click(); } } catch (cause) { setError(cause instanceof Error ? cause.message : "File could not be opened."); } };
  const download = (entry: Entry) => { const link = document.createElement("a"); link.href = `/api/proposals/sources/2026/projects/${selected}/files/${entry.id}/download`; link.download = entry.name; link.click(); };
  return <section className="panel proposal-source-workspace" aria-label="Proposal source workspace"><div className="panel-head"><div><span className="eyebrow">PROPOSAL · SOURCE WORKSPACE</span><h3>Synology source browser</h3><p className="muted">Tenders &gt; 1- Proposal &gt; 2026 · exact source names and read-only capture</p></div>{onBack && <button className="text-button" onClick={onBack}>Back</button>}</div>{error && <div className="error-state" role="alert">{error}<button className="text-button" onClick={() => { setError(""); void loadTree(); }}>Retry</button></div>}{message && <div className="inline-message" role="status">{message}</div>}<div className="source-workspace-toolbar"><button className="button-primary" onClick={() => void sync()}>Sync now</button><span className="muted">Read-only source · writes: 0</span></div><div className="source-workspace-projects" role="tablist" aria-label="Source projects">{projects.map((project) => <button key={project.number} role="tab" aria-selected={selected === project.number} className={selected === project.number ? "active" : ""} onClick={() => setSelected(project.number)}><b>{project.number} · {project.name.replace(/^\d+\s*-\s*/, "")}</b><small>{project.state} · {project.file_count} files</small></button>)}</div><div className="source-breadcrumb">Tenders <span>›</span> 1- Proposal <span>›</span> 2026 <span>›</span> <b>{projects.find((project) => project.number === selected)?.name || `${selected}`}</b></div>{loading ? <p className="muted">Loading source tree…</p> : <div className="source-tree"><div className="source-tree-folders"><button className={`source-folder ${!activeFolder ? "active" : ""}`} onClick={() => setActiveFolder("")}><b>▾ {projects.find((project) => project.number === selected)?.name || "Project root"}</b><small>{entries.filter((entry) => !entry.is_directory && !entry.path.includes("/" )).length} root files</small></button>{folders.map((entry) => <button className={`source-folder ${activeFolder === entry.path ? "active" : ""}`} key={entry.id} onClick={() => setActiveFolder(entry.path)}><b>▾ {entry.name}</b><small>{entries.filter((child) => child.path.startsWith(`${entry.path}/`)).length} items</small></button>)}</div><div className="source-file-list">{files.map((entry) => <div className="source-file" key={entry.id}><div><b>{entry.name}</b><small>{entry.path} · {formatSize(entry.size)} · {entry.content_type}</small></div><div><button className="text-button" onClick={() => void openFile(entry)}>View</button><button className="text-button" onClick={() => download(entry)}>Download</button></div></div>)}</div></div>}{preview && <div className="source-preview"><div className="panel-head"><h4>Source preview</h4><button className="text-button" onClick={() => setPreview("")}>Close</button></div><iframe title="Source file preview" src={preview} /></div>}</section>;
}
