import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { IssueFocusBanner, type Persona as IssuePersona } from "./PersonaIssuesNotifications";

type Project = { id: string; project_number: string; project_name: string };
type Persona = "SYSTEM_ADMIN" | "COMMERCIAL_APPROVER" | "RESPONSIBLE_ENGINEER";
type ActionKey = "CLIENT_LIST" | "PROPOSAL_FORM" | "CONTRACT_FORM" | "NEW_PROPOSAL" | "PERMIT_INITIATION";
type Register = "proposals" | "contracts";

const sourceActions: Array<{ key: ActionKey; label: string; helper: string; semantic: string }> = [
  { key: "CLIENT_LIST", label: "Client List", helper: "Manual upload", semantic: "CLIENT_SOURCE" },
  { key: "PROPOSAL_FORM", label: "Proposal Form", helper: "Manual upload", semantic: "PROPOSAL_SOURCE" },
  { key: "CONTRACT_FORM", label: "Contract Form", helper: "Manual upload", semantic: "CONTRACT_SOURCE" },
];
const kpiOrder = ["OPEN_PROPOSALS", "OPEN_CONTRACTS", "PROPOSAL_HANDOVER", "CONTRACT_HANDOVER", "PROPOSALS_IN_PROCESS", "CONTRACTS_IN_PROCESS"];
const roleLabels: Record<Persona, string> = { SYSTEM_ADMIN: "Owner", COMMERCIAL_APPROVER: "Business Development", RESPONSIBLE_ENGINEER: "Engineering" };
const issuePersona = (persona: Persona): IssuePersona => persona === "COMMERCIAL_APPROVER" ? "BUSINESS_DEVELOPMENT" : persona === "RESPONSIBLE_ENGINEER" ? "ENGINEERING" : "OWNER";

const proposalRowFields = ["id", "record_type", "proposal_id", "contract_id", "proposal_description", "project_id", "project_reference", "project_name", "proposal_status", "contract_status", "current_stage", "status", "amount", "last_activity", "source_count", "source_types", "reference_state", "proposal_fields", "next_action", "allowed_actions", "related_contract_id", "contract_action_eligible", "contract_action_label", "permit_application_id"];
const contractRowFields = ["id", "record_type", "contract_description", "contract_reference", "status", "contract_status", "related_proposal_id", "proposal_id", "related_proposal", "project_id", "project_reference", "project_name", "amount", "proposal_amount", "contract_amount", "last_activity", "end_date", "permit_count", "permit_id", "permit_application_id", "permit_action_eligible", "permit_action_label", "permit_action", "proposal_status", "next_action"];
const nullableRowFields = new Set(["contract_id", "project_id", "contract_status", "amount", "related_contract_id", "permit_application_id", "related_proposal_id", "proposal_id", "proposal_amount", "contract_amount", "end_date", "permit_id", "proposal_status"]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function requireField(record: Record<string, unknown>, field: string, path: string, nullable = false) {
  if (!(field in record) || record[field] === undefined || (!nullable && record[field] === null)) throw new Error(`The register response is incomplete: ${path}.${field}`);
}

function validateRow(row: unknown, path: string, fields: string[]) {
  if (!isRecord(row)) throw new Error(`The register response is invalid: ${path} must be an object`);
  fields.forEach((field) => requireField(row, field, path, nullableRowFields.has(field)));
  if (typeof row.id !== "string" || typeof row.record_type !== "string") throw new Error(`The register response is invalid: ${path}.id/record_type`);
  if (typeof row.last_activity !== "string" || (row.record_type === "PROPOSAL_WORKSPACE" && (typeof row.source_count !== "number" || !Array.isArray(row.source_types))) || (row.record_type === "CONTRACT" && (typeof row.permit_count !== "number" || typeof row.permit_action_eligible !== "boolean"))) throw new Error(`The register response has an invalid type: ${path}`);
}

export function validateProposalsMainPayload(payload: unknown): Record<string, any> {
  if (!isRecord(payload)) throw new Error("The register response is invalid: expected a JSON object");
  ["rows", "proposals", "contracts", "contract_rows", "clients", "filters", "kpis", "filter_predicates", "persona", "view", "sor", "lineage_model", "synthetic_only"].forEach((field) => requireField(payload, field, "response"));
  if (payload.view !== "proposals" && payload.view !== "contracts") throw new Error("The register response has an invalid view");
  if (typeof payload.synthetic_only !== "boolean" || typeof payload.lineage_model !== "string" || !isRecord(payload.sor)) throw new Error("The register response has invalid release metadata");
  for (const [field, expected] of [["rows", true], ["proposals", true], ["contracts", true], ["contract_rows", true], ["clients", true], ["filters", true]] as const) if (!Array.isArray(payload[field])) throw new Error(`The register response is invalid: response.${field} must be an array`);
  const kpis = payload.kpis;
  if (!isRecord(kpis)) throw new Error("The register response is invalid: response.kpis must be an object");
  for (const key of kpiOrder) {
    requireField(kpis, key, "response.kpis");
    const kpi = kpis[key];
    if (!isRecord(kpi) || typeof kpi.label !== "string" || typeof kpi.count !== "number" || !Number.isInteger(kpi.count) || kpi.count < 0 || !Array.isArray(kpi.states) || !kpi.states.every((state) => typeof state === "string") || (kpi.entity !== "proposal" && kpi.entity !== "contract")) throw new Error(`The register response has an invalid KPI: response.kpis.${key}`);
  }
  (payload.proposals as unknown[]).forEach((row, index) => validateRow(row, `response.proposals[${index}]`, proposalRowFields));
  (payload.contracts as unknown[]).forEach((row, index) => validateRow(row, `response.contracts[${index}]`, contractRowFields));
  (payload.rows as unknown[]).forEach((row, index) => validateRow(row, `response.rows[${index}]`, payload.view === "proposals" ? proposalRowFields : contractRowFields));
  if (!isRecord(payload.persona) || !Array.isArray(payload.persona.allowed_actions) || !Array.isArray(payload.persona.source_actions) || typeof payload.persona.amount_visible !== "boolean") throw new Error("The register response is invalid: response.persona");
  return payload;
}

export function ProposalsContractsPage({ projects, persona, openRecord }: { projects: Project[]; persona: Persona; openRecord: (projectId: string) => void }) {
  const initialView = new URLSearchParams(window.location.search).get("view") === "contracts" ? "contracts" : "proposals";
  const [routePath, setRoutePath] = useState(() => window.location.pathname);
  useEffect(() => { const syncRoute = () => setRoutePath(window.location.pathname); window.addEventListener("popstate", syncRoute); return () => window.removeEventListener("popstate", syncRoute); }, []);
  const [view, setView] = useState<Register>(initialView);
  const [data, setData] = useState<any>(null);
  const [filter, setFilter] = useState("ALL");
  const [modal, setModal] = useState<{ action: ActionKey; projectId?: string; contractId?: string; proposalId?: string } | null>(null);
  const [message, setMessage] = useState("");
  const [dataError, setDataError] = useState("");
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    setDataError("");
    return api<unknown>(`/api/proposals-main?persona=${persona}&view=${view}`).then(validateProposalsMainPayload).then(setData).catch((error) => { setData(null); setDataError(error instanceof Error ? error.message : "The register response could not be validated."); }).finally(() => setLoading(false));
  };
  useEffect(() => { void load(); }, [persona, view]);
  const navigateRoute = (route: string) => { window.history.pushState({}, "", route); window.dispatchEvent(new PopStateEvent("popstate")); };
  const backToRegister = () => navigateRoute("/proposals-contracts?view=proposals");
  const routeProposalId = routePath.match(/^\/proposals\/([^/]+)$/)?.[1] || null;
  const routePreparationId = routePath.match(/^\/proposals\/([^/]+)\/preparation$/)?.[1] || null;
  const routeContractId = routePath.match(/^\/contracts\/([^/]+)$/)?.[1] || null;
  const routeNew = routePath === "/proposals/new";
  const allowed = (data?.persona?.allowed_actions || []) as ActionKey[];
  const visibleActions = sourceActions.filter((item) => allowed.includes(item.key));
  const rows = (data?.rows || []) as any[];
  const filteredRows = useMemo(() => rows.filter((row) => {
    if (filter === "ALL") return true;
    if (filter === "NEEDS_ACTION") return view === "proposals" ? ["RECEIVED", "PROPOSAL_HANDOVER"].includes(row.proposal_status) || ["DRAFT", "CONTRACT_IN_PROGRESS"].includes(row.contract_status) : ["DRAFT", "CONTRACT_IN_PROGRESS", "CONTRACT_HANDOVER"].includes(row.contract_status);
    if (filter === "IN_REVIEW") return view === "proposals" ? ["IN_REVIEW", "QUOTATION_IN_PROGRESS", "COMMERCIAL_REVIEW", "PROPOSAL_HANDOVER"].includes(row.proposal_status) : ["CONTRACT_IN_PROGRESS", "CONTRACT_HANDOVER"].includes(row.contract_status);
    if (filter === "READY_CLOSED") return ["READY", "CLOSED", "ACCEPTED", "PROJECT_BOOTSTRAPPED"].includes(view === "proposals" ? row.proposal_status : row.contract_status);
    const kpi = data?.kpis?.[filter];
    return kpi ? kpi.states.includes(view === "proposals" ? row.proposal_status : row.contract_status) : true;
  }), [rows, filter, data, view]);
  const changeView = (next: Register) => { setView(next); setFilter("ALL"); window.history.replaceState({}, "", `/proposals-contracts?view=${next}`); };

  if (routeNew) return <NewProposalInline persona={persona} onBack={backToRegister} navigateRoute={navigateRoute} />;
  if (routePreparationId) return <div className="workflow-page proposals-main route-detail-page"><IssueFocusBanner persona={issuePersona(persona)} /><ProposalPreparationInline proposalId={routePreparationId} persona={persona} onClose={backToRegister} /></div>;
  if (routeProposalId) return <div className="workflow-page proposals-main route-detail-page"><IssueFocusBanner persona={issuePersona(persona)} /><ProposalDetailInline proposalId={routeProposalId} persona={persona} projects={projects} onBack={backToRegister} navigateRoute={navigateRoute} /></div>;
  if (routeContractId) return <div className="workflow-page proposals-main route-detail-page"><IssueFocusBanner persona={issuePersona(persona)} /><ContractDetailInline contractId={routeContractId} persona={persona} onBack={backToRegister} navigateRoute={navigateRoute} /></div>;

  if (loading && !data) return <div className="workflow-page proposals-main"><section className="panel"><b>Loading Proposals &amp; Contracts…</b></section></div>;
  if (dataError) return <div className="workflow-page proposals-main"><section className="panel error-state" role="alert"><h2>Proposals &amp; Contracts could not be loaded</h2><p>{dataError}</p><button className="button-primary" onClick={() => void load()}>Retry</button></section></div>;

  return <div className="workflow-page proposals-main">
    <div className="page-intro proposals-main-intro"><div><span className="eyebrow">AMEC · COMMERCIAL WORKFLOW</span><h2>Proposals &amp; Contracts</h2><p>Owner-directed commercial records with explicit downstream Permit lineage.</p></div><span className="tag">{roleLabels[persona]}</span></div>
    {message && <div className="inline-message">{message}</div>}
    <div className="proposal-action-row" aria-label="Manual source actions">
      {visibleActions.map((item) => <button key={item.key} className="proposal-orange-action" title="Choose a source and save it to the validated project record." onClick={() => { setMessage(""); setModal({ action: item.key }); }}><span>{item.label}</span><small>{item.helper}</small></button>)}
    </div>
    <div className="proposal-kpi-grid">{kpiOrder.map((key) => { const kpi = data.kpis[key]; return <button key={key} className={`proposal-kpi ${filter === key ? "selected" : ""}`} onClick={() => setFilter(filter === key ? "ALL" : key)}><span>{kpi.label}</span><strong>{kpi.count}</strong><small>System-derived · click to filter</small></button>; })}</div>
    <section className="panel proposals-table-panel">
      <div className="proposals-register-tabs" role="tablist" aria-label="Commercial registers"><button role="tab" aria-selected={view === "proposals"} className={view === "proposals" ? "active" : ""} onClick={() => changeView("proposals")}>Proposals</button><button role="tab" aria-selected={view === "contracts"} className={view === "contracts" ? "active" : ""} onClick={() => changeView("contracts")}>Contracts</button><span className="register-url">/proposals-contracts?view={view}</span></div>
      <div className="proposals-toolbar"><div className="filter-row">{(data?.filters || []).map((item: any) => <button key={item.key} className={`filter ${filter === item.key ? "active" : ""}`} onClick={() => setFilter(item.key)}>{item.label}</button>)}</div>{allowed.includes("NEW_PROPOSAL") && <button className="button-secondary proposal-new-button" onClick={() => setModal({ action: "NEW_PROPOSAL" })}>＋ New Proposal</button>}</div>
      <div className="table-panel">{view === "proposals" ? <ProposalTable rows={filteredRows} amountVisible={data.persona.amount_visible} onOpen={openRecord} onContract={(row) => setModal({ action: "CONTRACT_FORM", projectId: row.project_id, contractId: row.contract_id || undefined, proposalId: row.proposal_id })} canTransition={allowed.includes("CONTRACT_FORM")} /> : <ContractTable rows={filteredRows} amountVisible={data.persona.amount_visible} onOpen={openRecord} onPermit={(row) => row.permit_application_id ? openRecord(row.project_id) : setModal({ action: "PERMIT_INITIATION", projectId: row.project_id, contractId: row.contract_id, proposalId: row.proposal_id })} canTransition={allowed.includes("PERMIT_INITIATION")} />}</div>
    </section>
    <div className="proposal-sor-note"><span className="proposal-blue-dot"/><span>Blue shows system state. Orange actions are human-controlled source selection and transitions. Legitimate downstream Permit workflow remains in the Permit Workspace.</span></div>
    {modal && <ManualUploadModal action={modal.action} projects={projects} persona={persona} preselected={modal} onClose={() => setModal(null)} onComplete={(result) => { setModal(null); setMessage(`${result.source_filename} registered in ${result.semantic_class.replaceAll("_", " ")} · read-back verified.`); void load(); }} />}
  </div>;
}

function ProposalTable({ rows, amountVisible, onOpen, onContract, canTransition }: { rows: any[]; amountVisible: boolean; onOpen: (id: string) => void; onContract: (row: any) => void; canTransition: boolean }) {
  const colSpan = amountVisible ? 7 : 6;
  return <table><thead><tr><th>Proposal / Proposal Description</th><th>Project Ref.</th><th>Stage / Status</th>{amountVisible && <th>Amount</th>}<th>Last Activity</th><th>Actions</th><th>Contract</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.proposal_description}</b><small className="proposal-row-sub">{row.proposal_reference}</small></td><td><b>{row.project_reference}</b><small className="proposal-row-sub">{row.project_name}</small></td><td><span className="status status-under-review">{row.current_stage}</span></td>{amountVisible && <td>{row.amount || "—"}</td>}<td>{new Date(row.last_activity).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</td><td><button className="text-button" onClick={() => row.project_id && onOpen(row.project_id)}>Open →</button></td><td>{canTransition && row.contract_action_eligible ? <button className="proposal-context-action" onClick={() => onContract(row)}>{row.contract_action_label || "Contract"}</button> : <span className="muted" title="A validated project and quotation are required.">Not available</span>}</td></tr>)}{!rows.length && <tr><td colSpan={colSpan}><div className="empty-state"><b>No proposals match this view.</b><p>Proposal state and the KPI strip use the same register records.</p></div></td></tr>}</tbody></table>;
}

function ContractTable({ rows, amountVisible, onOpen, onPermit, canTransition }: { rows: any[]; amountVisible: boolean; onOpen: (id: string) => void; onPermit: (row: any) => void; canTransition: boolean }) {
  const colSpan = amountVisible ? 8 : 7;
  return <table><thead><tr><th>Contract Description</th><th>Contract Reference</th><th>Related Proposal</th><th>Amount</th><th>Last Activity</th><th>End Date</th><th>Actions</th><th>Permit</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.contract_description}</b><small className="proposal-row-sub">{row.project_name}</small></td><td><b>{row.contract_reference}</b></td><td><button className="text-button" onClick={() => row.project_id && onOpen(row.project_id)}>{row.related_proposal}</button></td><td>{amountVisible ? row.amount || "—" : "—"}</td><td>{new Date(row.last_activity).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</td><td>{row.end_date ? new Date(row.end_date).toLocaleDateString() : "—"}</td><td><button className="text-button" onClick={() => row.project_id && onOpen(row.project_id)}>Open →</button></td><td>{canTransition && row.permit_action_eligible ? <button className="proposal-context-action" onClick={() => onPermit(row)}>{row.permit_action_label || "Permit"}</button> : <span className="muted" title="A same-project contract and proposal lineage are required.">Not available</span>}</td></tr>)}{!rows.length && <tr><td colSpan={colSpan}><div className="empty-state"><b>No contracts match this view.</b><p>Contract state and the KPI strip use the same register records.</p></div></td></tr>}</tbody></table>;
}

function ManualUploadModal({ action, projects, persona, preselected, onClose, onComplete }: { action: ActionKey; projects: Project[]; persona: Persona; preselected?: { projectId?: string; contractId?: string; proposalId?: string }; onClose: () => void; onComplete: (result: any) => void }) {
  const sourceMetadata = sourceActions.find((item) => item.key === action);
  const metadata: { label: string; semantic: string; copy: string } = action === "PERMIT_INITIATION" ? { label: "Permit", semantic: "PERMIT_SOURCE", copy: "Select the controlled initiation source for the downstream Permit workflow." } : sourceMetadata ? { label: sourceMetadata.label, semantic: sourceMetadata.semantic, copy: "Choose the source yourself. The source is registered only after read-back verification." } : { label: "New Proposal", semantic: "OPPORTUNITY_SOURCE", copy: "Choose the source yourself. The proposal is registered only after read-back verification." };
  const [projectId, setProjectId] = useState(preselected?.projectId || ""); const [file, setFile] = useState<File | null>(null); const [revision, setRevision] = useState(""); const [description, setDescription] = useState(""); const [state, setState] = useState("SELECTED"); const [error, setError] = useState("");
  const project = projects.find((item) => item.id === projectId);
  const submit = async () => { setError(""); if (!projectId) { setError("Select a project before upload."); return; } if (!file) { setError("Manual file selection is required."); return; } if (action === "NEW_PROPOSAL" && !description.trim()) { setError("Proposal description is required."); return; } setState("VALIDATING"); const form = new FormData(); form.append("action", action); form.append("project_id", projectId); form.append("project_reference", project?.project_number || ""); form.append("file", file); form.append("source_revision", revision); form.append("proposal_description", description); form.append("actor", `${persona.toLowerCase()}@amec.synthetic`); form.append("actor_role", persona); if (preselected?.contractId) form.append("contract_id", preselected.contractId); if (preselected?.proposalId) form.append("proposal_id", preselected.proposalId); form.append("idempotency_key", `${projectId}:${action}:${preselected?.contractId || ""}:${file.name}:${file.size}:${file.lastModified}:${revision}`); try { setState("PUSHING_TO_SYSTEM_OF_RECORD"); const result = await api<any>("/api/proposals-main/intake", { method: "POST", body: form }); setState("VERIFYING"); if (result.verification_state !== "READ_BACK_VERIFIED") throw new Error("Source is not verified in the system of record."); setState("REGISTERED"); onComplete(result); } catch (err) { setState("FAILED"); setError(err instanceof Error ? err.message : "Upload failed. Retry required."); } };
  return <div className="proposal-modal-backdrop" role="presentation"><section className="proposal-upload-modal" role="dialog" aria-modal="true" aria-labelledby="manual-upload-title"><div className="panel-head"><div><span className="eyebrow">HUMAN INPUT / UPLOAD</span><h3 id="manual-upload-title">{metadata.label}</h3></div><button className="text-button" onClick={onClose}>Close</button></div><p className="proposal-modal-copy">{metadata.copy}</p><label>Project<select value={projectId} disabled={Boolean(preselected?.projectId)} onChange={(event) => setProjectId(event.target.value)}><option value="">Select project…</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.project_number} · {item.project_name}</option>)}</select></label><label>Project Reference<input readOnly value={project?.project_number || "Resolved after project selection"}/></label>{action === "NEW_PROPOSAL" && <label>Proposal Description<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="e.g. West Bay commercial fit-out inquiry"/></label>}<label>File<input type="file" onChange={(event) => setFile(event.target.files?.[0] || null)}/><small>Manual file selection is required. No source is generated by this screen.</small></label><label>Revision / Document Date<input value={revision} onChange={(event) => setRevision(event.target.value)} placeholder="Optional revision or date"/></label><div className="proposal-destination"><b>System of Record</b><span>{project ? `${project.project_number} · ${metadata.semantic.replaceAll("_", " ")}` : "Select a project to resolve destination"}</span><small>Configured project folder · {metadata.semantic.replaceAll("_", " ")}</small></div>{state !== "SELECTED" && <div className={`proposal-upload-state ${state === "FAILED" ? "failed" : ""}`}><b>{state.replaceAll("_", " ")}</b><span>{state === "FAILED" ? error : "File state is controlled; completion follows verification."}</span></div>}{error && state === "SELECTED" && <div className="proposal-form-error">{error}</div>}<div className="proposal-modal-actions"><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" onClick={submit} disabled={["VALIDATING", "PUSHING_TO_SYSTEM_OF_RECORD", "VERIFYING"].includes(state)}>Upload to Project Record</button></div></section></div>;
}

const readable = (value: unknown) => String(value || "Not recorded").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function ProposalDetailInline({ proposalId, persona, projects, onBack, navigateRoute }: { proposalId: string; persona: Persona; projects: Project[]; onBack: () => void; navigateRoute: (route: string) => void }) {
  const [detail, setDetail] = useState<any>(null); const [error, setError] = useState("");
  const load = () => { setError(""); setDetail(null); api<any>(`/api/proposals-main/proposals/${proposalId}`).then(setDetail).catch((cause) => setError(cause instanceof Error ? cause.message : "Proposal detail unavailable.")); };
  useEffect(() => { load(); }, [proposalId]);
  if (error) return <section className="panel proposal-detail-panel" role="alert"><button className="text-button" onClick={onBack}>← Proposals &amp; Contracts</button><h2>Proposal detail unavailable</h2><p>{error}</p><button className="button-secondary" onClick={load}>Retry</button></section>;
  if (!detail) return <section className="panel proposal-detail-panel"><b>Loading Proposal detail…</b></section>;
  const proposal = detail.proposal || {};
  const contracts = detail.contracts || (detail.contract ? [detail.contract] : []);
  return <section className="panel proposal-detail-panel"><div className="panel-head"><div><span className="eyebrow">PROPOSAL DETAIL · {roleLabels[persona]}</span><h2>{proposal.proposal_description || proposal.id || proposalId}</h2><p>{proposal.project_reference || "Project reference pending"} · {readable(proposal.proposal_status)}</p></div><button className="text-button" onClick={onBack}>← Proposals &amp; Contracts</button></div><div className="detail-status-grid"><div><small>Status</small><b>{readable(proposal.proposal_status)}</b></div><div><small>Next action</small><b>{proposal.next_action?.label || "Review record"}</b></div><div><small>Client</small><b>{detail.client ? "Linked" : "Information needed"}</b></div><div><small>Current sources</small><b>{proposal.source_count ?? detail.sources?.length ?? 0}</b></div></div><div className="preparation-grid"><div><h3>Proposal fields</h3>{Object.entries(detail.fields || {}).map(([key, value]) => <div className="detail-field" key={key}><small>{readable(key)}</small><b>{String(value || "Not recorded")}</b></div>)}<h3>Related Contract(s)</h3>{contracts.length ? contracts.map((item: any) => <button className="detail-field detail-link" key={item.id} onClick={() => navigateRoute(`/contracts/${item.id}`)}><b>{item.reference || item.contract_reference || item.id}</b><span>{readable(item.status)}</span></button>) : <p>No Contract is linked to this Proposal.</p>}</div><div><h3>Source evidence</h3>{(detail.sources || []).map((source: any) => <div className="preparation-source" key={source.id}><span>✓</span><div><b>{readable(source.artifact_class || source.semantic_class || "Source")}</b><small>{source.filename || source.path || "Recorded source"} · {source.verification_status === "READ_BACK_VERIFIED" ? "Verified" : readable(source.verification_status || "Recorded")}</small></div></div>)}<h3>Linked Issues &amp; history</h3><p>{detail.issues?.length || 0} linked issue(s) · {detail.history?.length || 0} audit event(s) retained.</p></div></div>{proposal.reference_state === "PROVISIONAL" && <div className="promotion-strip"><b>Canonical Project context</b><span>Reconcile retained sources once the canonical Project Reference exists.</span><select defaultValue=""><option value="">Select canonical Project…</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.project_number} · {project.project_name}</option>)}</select></div>}<div className="detail-actions">{proposal.next_action?.code === "VIEW_CONTRACT" && proposal.related_contract_id && <button className="proposal-orange-link" onClick={() => navigateRoute(`/contracts/${proposal.related_contract_id}`)}>View Contract</button>}</div></section>;
}

function ContractDetailInline({ contractId, persona, onBack, navigateRoute }: { contractId: string; persona: Persona; onBack: () => void; navigateRoute: (route: string) => void }) {
  const [detail, setDetail] = useState<any>(null); const [error, setError] = useState("");
  const load = () => { setError(""); setDetail(null); api<any>(`/api/proposals-main/contracts/${contractId}`).then(setDetail).catch((cause) => setError(cause instanceof Error ? cause.message : "Contract detail unavailable.")); };
  useEffect(() => { load(); }, [contractId]);
  if (error) return <section className="panel contract-detail-panel" role="alert"><button className="text-button" onClick={onBack}>← Proposals &amp; Contracts</button><h2>Contract detail unavailable</h2><p>{error}</p><button className="button-secondary" onClick={load}>Retry</button></section>;
  if (!detail) return <section className="panel contract-detail-panel"><b>Loading Contract detail…</b></section>;
  const contract = detail.contract || {};
  const reference = contract.reference || contract.contract_reference || contract.id || contractId;
  return <section className="panel contract-detail-panel"><div className="panel-head"><div><span className="eyebrow">CONTRACT DETAIL · {roleLabels[persona]}</span><h2>{reference}</h2><p>{readable(contract.status)} · {detail.project?.reference || "Project reference pending"}</p></div><button className="text-button" onClick={onBack}>← Proposals &amp; Contracts</button></div><div className="detail-status-grid"><div><small>Related Proposal</small>{detail.proposal?.id ? <button className="text-button" onClick={() => navigateRoute(`/proposals/${detail.proposal.id}`)}>{detail.proposal.reference || detail.proposal.proposal_reference || detail.proposal.id}</button> : <b>Not linked</b>}</div><div><small>Amount</small><b>{contract.amount || "Not recorded"}</b></div><div><small>End date</small><b>{contract.end_date ? new Date(contract.end_date).toLocaleDateString() : "Not recorded"}</b></div><div><small>Next action</small><b>{detail.next_action?.label || "Review record"}</b></div></div><div className="preparation-grid"><div><h3>Contract revisions</h3>{(detail.revisions || []).length ? detail.revisions.map((revision: any) => <div className="detail-field" key={revision.id}><b>Revision {revision.revision_number}</b><span>{readable(revision.status)}</span></div>) : <p>No Contract revision is recorded.</p>}<h3>Project context</h3><div className="detail-field"><b>{detail.project?.reference || "Not recorded"}</b><span>{detail.project?.name || "Project context pending"}</span></div></div><div><h3>Commercial handoff</h3><div className="detail-field"><small>Linked Proposal</small><b>{detail.proposal?.reference || detail.proposal?.proposal_reference || "Not linked"}</b></div><div className="detail-field"><small>Permit handoff</small><b>{detail.permits?.length ? `${detail.permits.length} linked Permit record(s)` : "No downstream Permit linked"}</b></div><h3>Source provenance</h3>{(detail.sources || []).map((source: any) => <div className="preparation-source" key={source.id}><span>✓</span><div><b>{readable(source.artifact_class || "Source")}</b><small>{source.verification_status === "READ_BACK_VERIFIED" ? "Verified" : readable(source.verification_status || "Recorded")}</small></div></div>)}<h3>Linked Issues &amp; history</h3><p>{detail.issues?.length || 0} linked issue(s) · {detail.history?.length || 0} audit event(s) retained.</p></div></div><div className="detail-actions">{detail.proposal?.id && <button className="text-button" onClick={() => navigateRoute(`/proposals/${detail.proposal.id}`)}>View Related Proposal</button>}</div></section>;
}

function ProposalPreparationInline({ proposalId, persona, onClose }: { proposalId: string; persona: Persona; onClose: () => void }) {
  const [detail, setDetail] = useState<any>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { api<any>(`/api/proposals-main/proposals/${proposalId}`).then(setDetail).catch((cause) => setError(cause instanceof Error ? cause.message : "Proposal preparation unavailable.")); }, [proposalId]);
  const engineering = persona === "RESPONSIBLE_ENGINEER" || persona === "SYSTEM_ADMIN";
  const readyForBd = async () => { if (busy) return; setBusy(true); setMessage(""); setError(""); try { await api(`/api/proposals-main/proposals/${proposalId}/engineering-ready`, { method: "POST", headers: { "X-Dev-Role": persona } }); setMessage("Engineering returned this Proposal to Business Development for commercial review."); setDetail(await api<any>(`/api/proposals-main/proposals/${proposalId}`)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Engineering handoff is blocked."); } finally { setBusy(false); } };
  if (error) return <section className="panel proposal-preparation-panel" role="alert"><button className="text-button" onClick={onClose}>← Proposals &amp; Contracts</button><h2>Proposal preparation unavailable</h2><p>{error}</p></section>;
  if (!detail) return <section className="panel proposal-preparation-panel"><b>Loading Proposal Preparation…</b></section>;
  return <section className="panel proposal-preparation-panel"><div className="panel-head"><div><span className="eyebrow">PROPOSAL PREPARATION · {roleLabels[persona]}</span><h3>Proposal Preparation</h3><p>{detail.proposal?.proposal_description} · {detail.proposal?.project_reference}</p></div><button className="text-button" onClick={onClose}>Close</button></div>{message && <div className="inline-message" role="status">{message}</div>}<div className="preparation-grid"><div><h3>Inputs &amp; Sources</h3>{(detail.sources || []).map((source: any) => <div className="preparation-source" key={source.id}><span>✓</span><div><b>{readable(source.semantic_class || source.artifact_class || "Source")}</b><small>{source.filename || source.path || "Recorded source"} · {source.verification_status === "READ_BACK_VERIFIED" ? "Verified" : readable(source.verification_status || "Recorded")}</small></div></div>)}</div><div><h3>Technical preparation</h3>{Object.entries(detail.fields || {}).slice(0, 6).map(([key, value]) => <div className="detail-field" key={key}><small>{readable(key)}</small><b>{String(value || "Not recorded")}</b></div>)}</div></div><div className="preparation-handoff"><span>{engineering ? "Engineering owns technical preparation; return the Proposal to Business Development when the technical decision is complete." : "Context only: Engineering owns technical preparation. Business Development may review the persisted scope and handoff state."}</span>{engineering && <button className="button-primary" onClick={readyForBd} disabled={busy || detail.proposal?.proposal_status !== "PROPOSAL_PREPARATION"}>{busy ? "Returning…" : "Ready for BD"}</button>}</div></section>;
}

function NewProposalInline({ persona, onBack, navigateRoute }: { persona: Persona; onBack: () => void; navigateRoute: (route: string) => void }) {
  const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (persona === "RESPONSIBLE_ENGINEER") return <section className="panel route-detail-page access-restricted-card" role="status"><span className="eyebrow">NEW PROPOSAL</span><h2>New Proposal intake is handled by Business Development.</h2><p>Engineering owns Proposal Preparation and technical handoff after a Proposal exists.</p><button className="button-primary" onClick={onBack}>Back to Proposals &amp; Contracts</button></section>;
  const submit = async () => { setError(""); if (!description.trim()) { setError("Enter a Proposal Description."); return; } if (!file) { setError("Add at least one Proposal source."); return; } setBusy(true); const form = new FormData(); form.append("action", "TENDER_DOCUMENT"); form.append("file", file); form.append("proposal_description", description.trim()); form.append("create_new_proposal", "true"); form.append("actor", `${persona.toLowerCase()}@amec.synthetic`); form.append("actor_role", persona); form.append("idempotency_key", `new-proposal:${file.name}:${file.size}:${file.lastModified}`); try { const result = await api<any>("/api/proposals-main/intake", { method: "POST", body: form }); navigateRoute(`/proposals/${result.opportunity_id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal could not be created. Retry required."); } finally { setBusy(false); } };
  return <div className="workflow-page proposals-main route-detail-page route-new-proposal"><div className="page-intro proposals-main-intro"><div><span className="eyebrow">AMEC · PROPOSAL INTAKE</span><h2>New Proposal</h2><p>Start a Proposal from tender and client information. Source evidence is retained under a controlled provisional Proposal Reference until a canonical Project Reference is available.</p></div><span className="tag">{roleLabels[persona]}</span></div><section className="panel proposal-intake-page-panel"><section className="proposal-intake-step"><h3>1. Proposal details</h3><label>Proposal Description<input aria-label="Proposal Description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Client inquiry or tender description" /></label></section><section className="proposal-intake-step"><h3>2. Source evidence</h3><p className="proposal-intake-hint">Choose a tender or client source and save it after read-back verification.</p><div className="source-intake-grid">{["Tender Email", "Tender Document", "Tender Photo / Image", "Client Information"].map((label) => <label className="source-intake-secondary" key={label}><b>{label}</b><input type="file" aria-label={`${label} source file`} onChange={(event) => setFile(event.target.files?.[0] || null)} /><small>Manual source selection · retained with provenance</small></label>)}</div></section>{error && <div className="proposal-form-error" role="alert">{error}</div>}<div className="proposal-modal-actions"><button className="button-secondary" onClick={onBack}>Back to Proposals &amp; Contracts</button><button className="button-primary proposal-orange-submit" onClick={submit} disabled={busy}>{busy ? "Creating Proposal…" : "Create Proposal & Save Sources"}</button></div></section></div>;
}
