import { useEffect, useMemo, useState } from "react";
import { api } from "./api";

type Role = "SYSTEM_ADMIN" | "OWNER_SPONSOR" | "COMMERCIAL_APPROVER" | "RESPONSIBLE_ENGINEER";
type SourceType = "TENDER_DOCUMENT" | "TENDER_EMAIL" | "TENDER_PHOTO" | "CLIENT_DATA";

const sourceTypes: Array<{ key: SourceType; label: string }> = [
  { key: "TENDER_EMAIL", label: "Tender Email" },
  { key: "TENDER_DOCUMENT", label: "Tender Document" },
  { key: "TENDER_PHOTO", label: "Tender Photo / Image" },
  { key: "CLIENT_DATA", label: "Client Information" },
];
const sourceDisplay: Record<string, string> = {
  TENDER_EMAIL: "Tender Email",
  TENDER_DOCUMENT: "Tender Document",
  TENDER_PHOTO: "Tender Photo / Image",
  CLIENT_DATA: "Client Information",
};
const stageSteps = [
  { key: "IN_REVIEW", label: "Intake & Sources" },
  { key: "PROPOSAL_PREPARATION", label: "Engineering Preparation" },
  { key: "COMMERCIAL_REVIEW", label: "Commercial Review" },
  { key: "CLIENT_RESPONSE_PENDING", label: "Client Response" },
  { key: "CONTRACT_HANDOVER", label: "Contract Handoff" },
];
const stageRank: Record<string, number> = {
  RECEIVED: 0,
  IN_REVIEW: 0,
  PROPOSAL_PREPARATION: 1,
  PROPOSAL_HANDOVER: 2,
  READY_FOR_QUOTATION: 2,
  COMMERCIAL_REVIEW: 2,
  QUOTATION_IN_PROGRESS: 2,
  CLIENT_RESPONSE_PENDING: 3,
  ACCEPTED: 3,
  CONTRACT_HANDOVER: 4,
  CLOSED: 5,
};
const stageLabel: Record<string, string> = Object.fromEntries(stageSteps.map((step) => [step.key, step.label]));
const ownerRoles = new Set<Role>(["SYSTEM_ADMIN", "OWNER_SPONSOR", "COMMERCIAL_APPROVER"]);
const engineeringRoles = new Set<Role>(["SYSTEM_ADMIN", "OWNER_SPONSOR", "RESPONSIBLE_ENGINEER"]);
const clientKeys = ["client_name", "attn_contact", "contact_email", "mobile_no", "project_description", "client_scope_of_work", "client_budget", "requested_timing", "client_constraints", "additional_information"];
const engineeringKeys = ["service_scope", "scope_of_work", "sow", "process_of_work", "technical_assumptions", "technical_deliverables", "engineering_references", "regulatory_scoping", "expected_client_inputs"];
const commercialKeys = ["price", "currency", "duration", "period", "payment_terms", "proposal_validity", "inclusions", "exclusions", "breakdown"];

const asRecord = (value: unknown): Record<string, any> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {};
const asList = (value: unknown): any[] => Array.isArray(value) ? value : [];
const safeText = (value: unknown, fallback = "Not recorded"): string => {
  if (value === null || value === undefined || value === "") return fallback;
  if (Array.isArray(value)) return value.length ? value.join(", ") : fallback;
  if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([key, item]) => `${key.replaceAll("_", " ")}: ${String(item)}`).join(" · ") || fallback;
  return String(value);
};
const amountText = (value: unknown, currency?: unknown): string => {
  const raw = safeText(value, "Fee pending");
  const code = safeText(currency, "");
  return code && !raw.toUpperCase().includes(code.toUpperCase()) ? `${code} ${raw}` : raw;
};
const areaKindText = (value: unknown): string => ({ GROSS: "Gross area", NET: "Net area", PLOT: "Plot area", BUILT_UP: "Built-up area", OTHER: "Other area", LEGACY_UNSPECIFIED: "Not specified" } as Record<string, string>)[String(value || "")] || "Not specified";
const stageState = (current: string, step: string): "past" | "current" | "future" => {
  const currentRank = stageRank[current] ?? 0;
  const stepRank = stageRank[step] ?? 0;
  return stepRank < currentRank ? "past" : stepRank === currentRank ? "current" : "future";
};
const inputValue = (fields: Record<string, any>, key: string): string => {
  const value = fields[key];
  return Array.isArray(value) ? value.join(", ") : value === undefined || value === null ? "" : String(value);
};

export function ProposalWorkspaceStageAware({ role, proposal, setProposal, onBack, setMessage, message, error, setError }: any) {
  const fields = asRecord(proposal.fields);
  const forms = asRecord(proposal.forms_v2);
  const validation = asRecord(proposal.validation);
  const readiness = asRecord(proposal.intake_readiness);
  const gate = asRecord(proposal.stage_gate);
  const currentStage = String(proposal.stage || "IN_REVIEW");
  const currentRank = stageRank[currentStage] ?? 0;
  const canEditClient = ownerRoles.has(role);
  const canEditEngineering = engineeringRoles.has(role);
  const canEditCommercial = ownerRoles.has(role);
  const intakeCurrent = currentRank === 0;
  const engineeringCurrent = currentRank === 1;
  const commercialCurrent = currentRank === 2;
  const responseCurrent = currentRank === 3;
  const canEditClientStage = canEditClient && intakeCurrent;
  const canEditEngineeringStage = canEditEngineering && engineeringCurrent;
  const accepted = currentStage === "ACCEPTED" || Boolean(proposal.outputs?.available);
  const informationChanged = currentStage === "ACCEPTED" && Boolean(proposal.hardening?.current_information_changed || asList(proposal.hardening?.active_staleness).length > 0);
  const initialDraft = { ...fields, client_constraints: fields.client_constraints ?? fields.client_exclusions ?? fields.exclusions };
  const [draft, setDraft] = useState<Record<string, any>>(initialDraft);
  const [contact, setContact] = useState({ display_name: forms.proposal_contact?.display_name || inputValue(fields, "attn_contact"), email: forms.proposal_contact?.email || inputValue(fields, "contact_email"), mobile: forms.proposal_contact?.mobile || inputValue(fields, "mobile_no") });
  const [site, setSite] = useState({ location_text: forms.site_context?.location_text || inputValue(fields, "location"), plot_text: forms.site_context?.plot_text || "", area_value: forms.site_context?.area_value || "", area_unit: forms.site_context?.area_unit || "m2", area_kind: forms.site_context?.area_kind || "LEGACY_UNSPECIFIED", site_description: forms.site_context?.site_description || "" });
  const [stakeholderRole, setStakeholderRole] = useState("OWNER");
  const [stakeholderName, setStakeholderName] = useState("");
  const [sourceType, setSourceType] = useState<SourceType | null>(null);
  const [sourceFile, setSourceFile] = useState<File | null>(null);
  const [saving, setSaving] = useState(false);
  const [noteType, setNoteType] = useState("CALL_NOTE");
  const [noteContent, setNoteContent] = useState("");
  const [responseType, setResponseType] = useState("");
  const [responseNotes, setResponseNotes] = useState("");
  const [outcome, setOutcome] = useState("");
  const [unknownText, setUnknownText] = useState("");
  const [conflictText, setConflictText] = useState("");

  useEffect(() => setDraft(initialDraft), [proposal.updated_at]);
  const sourceByType = useMemo(() => Object.fromEntries(asList(proposal.sources).map((item: any) => [item.source_type, item])), [proposal.sources]);
  const setField = (key: string, value: any) => setDraft((current) => ({ ...current, [key]: value }));
  const saveFields = async (keys: string[], success: string) => {
    setSaving(true); setError("");
    try {
      const selected = Object.fromEntries(keys.filter((key) => draft[key] !== undefined).map((key) => [key, draft[key]]));
      const result = await api<any>(`/api/bd/proposals/${proposal.id}`, { method: "PATCH", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ fields: selected, expected_updated_at: proposal.updated_at }) });
      setProposal(result); setMessage(success);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal fields could not be saved; reload and retry."); } finally { setSaving(false); }
  };
  const saveV2 = async (path: string, payload: any, success: string) => {
    try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/${path}`, { method: path === "contact" || path === "site-context" ? "PUT" : "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setProposal(result); setMessage(success); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal governance update failed."); }
  };
  const uploadSource = async () => {
    if (!sourceType || !sourceFile) return;
    const form = new FormData(); form.append("source_type", sourceType); form.append("file", sourceFile);
    try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/sources`, { method: "POST", headers: headers(role), body: form }); setProposal(result.proposal); setSourceType(null); setSourceFile(null); setMessage(`${sourceDisplay[sourceType]} registered and read-back verified.`); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Source evidence could not be registered."); }
  };
  const proceed = async () => {
    try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/proceed`, { method: "POST", headers: headers(role) }); setProposal(result.proposal); setMessage("Intake completed. Engineering Preparation is now the current stage."); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Proceed is blocked by Intake readiness."); }
  };
  const engineeringReady = async () => {
    try { const result = await api<any>(`/api/proposals-main/proposals/${proposal.id}/engineering-ready`, { method: "POST", headers: headers(role) }); setProposal(result.proposal || result); setMessage("Engineering Preparation completed. Commercial Review is now the next stage."); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Engineering handoff is blocked."); }
  };
  const validate = async () => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/validation`, { headers: headers(role) }); setProposal((current: any) => ({ ...current, validation: result })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Readiness could not be refreshed."); } };
  const accept = async () => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/accept`, { method: "POST", headers: headers(role) }); setProposal(result); setMessage(`Revision ${result.current_revision.revision_number} accepted by a human operator.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Accept is blocked by validation or stage."); } };
  const recordResponse = async () => { if (!responseType) return; try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/client-responses`, { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ response_type: responseType, notes: responseNotes, idempotency_key: `workspace-response-${proposal.id}-${responseType}` }) }); setProposal(result.proposal); setResponseType(""); setMessage(`Client Response ${responseType.replaceAll("_", " ")} recorded with human evidence.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Client Response could not be recorded."); } };
  const recordOutcome = async () => { if (!outcome) return; try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/commercial-outcome`, { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ outcome, reason: "Recorded through Proposal workspace" }) }); setProposal(result.proposal); setOutcome(""); setMessage(`Commercial outcome ${outcome} recorded separately from stage closure.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Commercial outcome could not be recorded."); } };
  const createRevision = async () => { try { const result = await api<any>(`/api/bd/proposals/${proposal.id}/revisions`, { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ reason: "Current information changed after acceptance" }) }); setProposal(result.proposal); setMessage(`Working Proposal revision R${result.revision.revision_number} created from accepted history.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Proposal revision could not be created."); } };
  const addNote = async () => { if (!noteContent.trim()) return; const result = await api<any>(`/api/bd/proposals/${proposal.id}/notes`, { method: "POST", headers: { ...headers(role), "Content-Type": "application/json" }, body: JSON.stringify({ note_type: noteType, content: noteContent }) }); setProposal(result); setNoteContent(""); setMessage("Note saved as human-entered context."); };
  const addStakeholder = async () => { if (!stakeholderName.trim()) return; await saveV2("stakeholders", { role_code: stakeholderRole, display_snapshot: stakeholderName, status: "CANDIDATE" }, "Stakeholder recorded; Party identity remains separate."); setStakeholderName(""); };
  const addUnknown = async () => { if (!unknownText.trim()) return; await saveV2("unknowns", { category: "COMMERCIAL", statement: unknownText, materiality: "MATERIAL" }, "Unknown recorded as distinct unresolved information."); setUnknownText(""); };
  const addConflict = async () => { if (!conflictText.trim()) return; await saveV2("conflicts", { field_code: "OWNER_REVIEW", source_a: "Source A", value_a: conflictText, source_b: "Source B", value_b: "Needs comparison", materiality: "MATERIAL" }, "Conflict recorded without silently choosing a winner."); setConflictText(""); };
  const field = (key: string, label: string, editable: boolean, multiline = false) => <label key={key}>{label}{multiline ? <textarea value={inputValue(draft, key)} disabled={!editable} onChange={(event) => setField(key, event.target.value)} /> : <input value={inputValue(draft, key)} disabled={!editable} onChange={(event) => setField(key, event.target.value)} />}</label>;
  const sectionClass = (key: string) => `panel bd-v2-section stage-section stage-${stageState(currentStage, key)}`;
  const gateState = String(gate.intake?.state || (readiness.ready ? "COMPLETED" : "INCOMPLETE"));
  const gateMessage = gateState === "RECONCILIATION_REQUIRED" ? "Upstream Intake reconciliation required" : gateState === "COMPLETED" ? "Intake complete" : "Complete Intake before Engineering Preparation";
  const amecNotes = Object.entries(asRecord(proposal.amec_input)).filter(([, value]) => value !== null && value !== "");

  return <>
    <div className="page-intro"><div><span className="eyebrow">BD · PROPOSAL CENTER</span><h2>{proposal.title}</h2><p>{proposal.proposal_reference} · {proposal.project_reference || "Provisional opportunity reference"}</p><p className="muted">Stage: {stageLabel[currentStage] || currentStage} · Current owner: {proposal.current_owner || "Business Development"} · {proposal.current_revision ? `Accepted revision R${proposal.current_revision.revision_number}` : "Draft Proposal · Working revision"}</p></div><button className="text-button" onClick={onBack}>← Proposals</button></div>
    {message && <div className="inline-message" role="status">{message}</div>}{error && <div className="error-state" role="alert">{error}</div>}
    <nav className="workflow-stepper opportunity-tabs" aria-label="Proposal lifecycle">{stageSteps.map((step) => { const state = stageState(currentStage, step.key); return <a key={step.key} href={`#proposal-${step.key.toLowerCase()}`} className={`workflow-step ${state}`} aria-current={state === "current" ? "step" : undefined}><span>{state === "past" ? "✓" : state === "current" ? "●" : "○"}</span>{step.label}</a>; })}</nav>
    <div className="bd-owner-nav" aria-label="Proposal sections"><a href="#proposal-client">Client Request</a><a href="#proposal-engineering">Engineering</a><a href="#proposal-commercial">Commercial</a><a href="#proposal-review">Review &amp; Outputs</a><a href="#proposal-history">History</a></div>

    <section id="proposal-client" className={sectionClass("IN_REVIEW")}><div className="panel-head"><div><span className="eyebrow">CLIENT REQUEST</span><h3>Client &amp; contacts</h3></div><span className="stage-badge">{stageState(currentStage, "IN_REVIEW") === "past" ? "Read-only source context" : "Current intake"}</span></div><p className="muted">Client-provided and BD-captured context. AMEC interpretation is recorded in Engineering Preparation.</p><div className="bd-form-grid">{field("client_name", "Client", canEditClientStage)}{field("project_description", "Project / Proposal Description", canEditClientStage, true)}{field("client_scope_of_work", "Client Requested Scope", canEditClientStage, true)}{field("client_budget", "Client Budget", canEditClientStage)}{field("requested_timing", "Requested Timing", canEditClientStage)}{field("client_constraints", "Client Constraints / Exclusions", canEditClientStage, true)}{field("additional_information", "Additional Information", canEditClientStage, true)}</div><div className="bd-form-grid"><label>Proposal Contact<input value={contact.display_name} disabled={!canEditClientStage} onChange={(event) => setContact({ ...contact, display_name: event.target.value })} /></label><label>Contact Email<input value={contact.email} disabled={!canEditClientStage} onChange={(event) => setContact({ ...contact, email: event.target.value })} /></label><label>Mobile<input value={contact.mobile} disabled={!canEditClientStage} onChange={(event) => setContact({ ...contact, mobile: event.target.value })} /></label></div>{canEditClientStage ? <div className="bd-action-row"><button className="button-secondary" onClick={() => void saveFields(clientKeys, "Client Request saved.")} disabled={saving}>Save Client Request</button><button className="button-secondary" onClick={() => void saveV2("contact", contact, "Proposal Contact saved.")}>Save Contact</button></div> : <p className="muted">Client Request is preserved as a read-only snapshot after Intake handoff.</p>}</section>

    <section className={sectionClass("IN_REVIEW")}><div className="panel-head"><div><span className="eyebrow">CLIENT &amp; PROPERTY</span><h3>Site / Property context</h3></div><span className="stage-badge">{stageState(currentStage, "IN_REVIEW") === "past" ? "Read-only context" : "Intake context"}</span></div><div className="bd-form-grid">{field("location", "Location", canEditClientStage)}<label>Plot / property reference<input value={site.plot_text} disabled={!canEditClientStage} onChange={(event) => setSite({ ...site, plot_text: event.target.value })} /></label><label>Area value<input value={site.area_value} disabled={!canEditClientStage} onChange={(event) => setSite({ ...site, area_value: event.target.value })} /></label><label>Area unit<input value={site.area_unit} disabled={!canEditClientStage} onChange={(event) => setSite({ ...site, area_unit: event.target.value })} /></label><label>Area kind<select value={site.area_kind} disabled={!canEditClientStage} onChange={(event) => setSite({ ...site, area_kind: event.target.value })}><option value="LEGACY_UNSPECIFIED">Not specified</option><option value="GROSS">Gross area</option><option value="NET">Net area</option><option value="PLOT">Plot area</option><option value="BUILT_UP">Built-up area</option><option value="OTHER">Other area</option></select></label><label>Site description<textarea value={site.site_description} disabled={!canEditClientStage} onChange={(event) => setSite({ ...site, site_description: event.target.value })} /></label></div>{canEditClientStage ? <button className="button-secondary" onClick={() => void saveV2("site-context", site, "Site / Property context saved.")}>Save Site / Property Context</button> : <p className="muted">Area basis: {site.area_value ? `${site.area_value} ${site.area_unit} · ${areaKindText(site.area_kind)}` : "Not recorded"}.</p>}</section>

    <section className={sectionClass("IN_REVIEW")}><div className="panel-head"><div><span className="eyebrow">STAKEHOLDERS</span><h3>Stakeholders</h3></div><span className="stage-badge">One unified presentation</span></div><p className="muted">Known, expected, candidate, and unresolved parties are shown together. Party master identity remains separate from Proposal context.</p>{asList(forms.stakeholders).length ? <div className="bd-v2-list">{asList(forms.stakeholders).map((item: any) => <div key={item.id}><b>{safeText(item.role_code, "Stakeholder")}</b><span>{safeText(item.display_snapshot || item.name)}</span><small>{safeText(item.status, "Status unavailable")}</small></div>)}</div> : <p className="muted">No stakeholders recorded yet.</p>}{canEditClient && intakeCurrent && <div className="bd-inline-add"><select aria-label="Stakeholder role" value={stakeholderRole} onChange={(event) => setStakeholderRole(event.target.value)}><option value="OWNER">Owner / Sponsor</option><option value="CLIENT">Client</option><option value="CONSULTANT">Consultant</option><option value="AUTHORITY">Authority contact</option><option value="OTHER">Other</option></select><input aria-label="Stakeholder name" placeholder="Name or organization" value={stakeholderName} onChange={(event) => setStakeholderName(event.target.value)} /><button className="button-secondary" onClick={() => void addStakeholder()}>Add stakeholder</button></div>}</section>

    <section id="proposal-sources" className={sectionClass("IN_REVIEW")}><div className="panel-head"><div><span className="eyebrow">SOURCES</span><h3>Source evidence</h3></div><small>{asList(proposal.sources).length} source record(s) · immutable snapshots retained</small></div><div className="bd-source-grid">{sourceTypes.map((item) => <div className={`bd-source-card ${sourceByType[item.key] ? "complete" : ""}`} key={item.key}><b>{item.label}</b><small>{sourceByType[item.key] ? `${sourceByType[item.key].verification_state || "Verified"} · source retained` : "Not yet received"}</small></div>)}</div>{canEditClientStage && <details className="bd-source-add"><summary>＋ Add source</summary><div className="bd-inline-add"><select aria-label="Source type" value={sourceType || ""} onChange={(event) => setSourceType((event.target.value || null) as SourceType | null)}><option value="">Select source family</option>{sourceTypes.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><input aria-label="Source file" type="file" onChange={(event) => setSourceFile(event.target.files?.[0] || null)} /><button className="button-secondary" onClick={() => void uploadSource()} disabled={!sourceType || !sourceFile}>Register source</button></div></details>}</section>

    <section id="proposal-engineering" className={sectionClass("PROPOSAL_PREPARATION")}><div className="panel-head"><div><span className="eyebrow">ENGINEERING PREPARATION</span><h3>AMEC technical preparation</h3></div><span className="stage-badge">{engineeringCurrent ? "Current · Engineering" : stageState(currentStage, "PROPOSAL_PREPARATION")}</span></div><p className="muted">AMEC interpretation, technical assumptions, regulatory scoping, and expected client inputs. This section does not overwrite the Client Request.</p><div className="bd-form-grid">{field("service_scope", "AMEC Service Scope", canEditEngineeringStage, true)}{field("scope_of_work", "AMEC Scope of Work", canEditEngineeringStage, true)}{field("sow", "Engineering Work / Process", canEditEngineeringStage, true)}{field("process_of_work", "Process of Work", canEditEngineeringStage, true)}{field("technical_assumptions", "Technical Assumptions", canEditEngineeringStage, true)}{field("technical_deliverables", "Engineering Deliverables", canEditEngineeringStage, true)}{field("engineering_references", "Engineering References", canEditEngineeringStage, true)}{field("regulatory_scoping", "Regulatory Scoping", canEditEngineeringStage, true)}{field("expected_client_inputs", "Expected Client Inputs", canEditEngineeringStage, true)}</div><div className="bd-v2-list"><div><b>Proposal Form · existing Proposal context</b><span>{asList(forms.proposal_form).length ? `${asList(forms.proposal_form).length} verified Proposal Form source(s)` : "No Proposal Form source recorded"}</span><small>Proposal Form remains a source-backed context, not a duplicate acceptance surface.</small></div><div><b>Regulatory Scoping</b><span>{asList(forms.regulatory_scope_intents).length ? `${asList(forms.regulatory_scope_intents).length} preliminary intent(s)` : "No preliminary regulatory intent recorded"}</span><small>Planning intent only · no AuthorityCase is created here.</small></div><div><b>Expected Client Inputs — Preliminary</b><span>{safeText(forms.expected_client_inputs?.status, "Preview unavailable")}</span><small>Policy-driven preview; final requirements remain downstream.</small></div></div>{engineeringCurrent && canEditEngineeringStage ? <div className="bd-action-row"><button className="button-secondary" onClick={() => void saveFields(engineeringKeys, "Engineering Preparation saved.")} disabled={saving}>Save Engineering Preparation</button><button className="button-primary" onClick={() => void engineeringReady()}>Mark Engineering Ready for Commercial Review</button></div> : <p className="muted">Engineering fields are {stageState(currentStage, "PROPOSAL_PREPARATION") === "past" ? "preserved as a read-only handoff snapshot" : "locked until Intake is complete"}.</p>}</section>

    <section id="proposal-commercial" className={sectionClass("COMMERCIAL_REVIEW")}><div className="panel-head"><div><span className="eyebrow">COMMERCIAL REVIEW</span><h3>Commercial Proposal</h3></div><span className="stage-badge">{commercialCurrent ? "Current · Business Development" : stageState(currentStage, "COMMERCIAL_REVIEW")}</span></div><p className="muted">Commercial values are separate from Engineering and remain editable only for the commercial owner roles.</p><div className="bd-form-grid">{field("price", "AMEC Fee", canEditCommercial && commercialCurrent)}{field("currency", "Currency", canEditCommercial && commercialCurrent)}{field("duration", "Commercial Duration", canEditCommercial && commercialCurrent)}{field("payment_terms", "Payment Terms", canEditCommercial && commercialCurrent, true)}{field("proposal_validity", "Proposal Validity", canEditCommercial && commercialCurrent)}{field("inclusions", "Inclusions", canEditCommercial && commercialCurrent, true)}{field("exclusions", "Commercial Exclusions", canEditCommercial && commercialCurrent, true)}{field("breakdown", "Commercial Breakdown", canEditCommercial && commercialCurrent, true)}</div><div className="bd-summary-grid"><div><b>Fee preview</b><p>{amountText(fields.price || draft.price, fields.currency || draft.currency)} · {safeText(fields.duration || draft.duration || fields.period, "Duration pending")}</p></div><div><b>Policy status</b><p>{proposal.configuration?.commercial_policy || "Owner policy/content pending"}</p></div></div>{commercialCurrent && canEditCommercial ? <button className="button-secondary" onClick={() => void saveFields(commercialKeys, "Commercial Review saved.")} disabled={saving}>Save Commercial Review</button> : <p className="muted">Commercial controls are locked until the Proposal reaches Commercial Review.</p>}</section>
    <section className="panel proposal-configuration-panel"><div className="panel-head"><div><span className="eyebrow">DASHBOARD CONFIGURATION</span><h3>Managed in Dashboard</h3></div><small>Proposal consumes governed content; it does not edit the global master.</small></div><div className="two-col"><div className="operator-block"><b>Proposal Template</b><span>{proposal.configuration?.proposal_template?.status === "READY" ? `${proposal.configuration.proposal_template.ref} v${proposal.configuration.proposal_template.version} · Current version` : "Requirement unresolved"}</span><small>Status: {proposal.configuration?.proposal_template?.status || "UNAVAILABLE"}</small></div><div className="operator-block"><b>Proposal Checklist</b><span>{proposal.configuration?.proposal_checklist?.status === "READY" ? `${proposal.configuration.proposal_checklist.ref} v${proposal.configuration.proposal_checklist.version} · Current version` : "Requirement unresolved"}</span><small>Status: {proposal.configuration?.proposal_checklist?.status || "UNAVAILABLE"}</small></div></div><div className="two-col"><div className="operator-block"><b>Definitions</b><span>{proposal.configuration?.definitions?.count || 0} applicable definition(s)</span><small>Meaning is governed in Dashboard.</small></div><div className="operator-block"><b>Engineering references</b><span>{proposal.configuration?.engineering_references?.status === "DEFERRED" ? "Available during Engineering Preparation" : `${proposal.configuration?.engineering_references?.items?.length || 0} eligible reference(s)`}</span><small>Resolved by the backend for the current stage.</small></div></div>{proposal.current_revision && <p className="inline-message">Accepted revision R{proposal.current_revision.revision_number} remains pinned to the accepted Dashboard versions.</p>}</section>

    <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">DECISION CONTEXT &amp; NOTES</span><h3>Decision context</h3></div><small>Assumptions, unknowns, conflicts, and conversations remain distinct records.</small></div><div className="bd-v2-list">{asList(forms.assumptions).map((item: any) => <div key={item.id}><b>Assumption · {safeText(item.materiality)}</b><span>{safeText(item.statement)}</span><small>{safeText(item.status)}</small></div>)}{asList(proposal.hardening?.unknowns).map((item: any) => <div key={item.id}><b>Unknown · {safeText(item.materiality)}</b><span>{safeText(item.statement)}</span><small>{safeText(item.status)}</small></div>)}{asList(proposal.hardening?.conflicts).map((item: any) => <div key={item.id}><b>Conflict · {safeText(item.field_code)}</b><span>{safeText(item.value_a)} · {safeText(item.value_b)}</span><small>{safeText(item.status)}</small></div>)}</div>{!asList(forms.assumptions).length && !asList(proposal.hardening?.unknowns).length && !asList(proposal.hardening?.conflicts).length && <p className="muted">No assumptions, unknowns, or conflicts recorded.</p>}{canEditClient && <div className="bd-inline-add"><input aria-label="New Proposal unknown" placeholder="Add unresolved unknown" value={unknownText} onChange={(event) => setUnknownText(event.target.value)} /><button className="button-secondary" onClick={() => void addUnknown()}>Add unknown</button><input aria-label="New Proposal conflict" placeholder="Add source conflict summary" value={conflictText} onChange={(event) => setConflictText(event.target.value)} /><button className="button-secondary" onClick={() => void addConflict()}>Add conflict</button></div>}<div className="bd-v2-list">{asList(proposal.notes).map((note: any) => <div key={note.id}><b>{safeText(note.note_type, "Note")}</b><span>{safeText(note.content)}</span><small>{safeText(note.entered_by)} · {note.created_at ? new Date(note.created_at).toLocaleString() : "Date unavailable"}</small></div>)}</div>{canEditClient && <div className="bd-inline-add"><select aria-label="Note type" value={noteType} onChange={(event) => setNoteType(event.target.value)}><option value="CALL_NOTE">Call Note</option><option value="MEETING_NOTE">Meeting Note</option><option value="CLIENT_CLARIFICATION">Client Clarification</option></select><input aria-label="Note content" placeholder="Record a conversation or clarification" value={noteContent} onChange={(event) => setNoteContent(event.target.value)} /><button className="button-secondary" onClick={() => void addNote()}>Add note</button></div>}</section>

    <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">AMEC INTERNAL NOTES</span><h3>AMEC Input</h3></div><small>Internal AMEC context is retained for audit; raw JSON is not shown in the Owner workspace.</small></div>{amecNotes.length ? <div className="bd-v2-list">{amecNotes.map(([key, value]) => <div key={key}><b>{key.replaceAll("_", " ")}</b><span>{safeText(value)}</span><small>AMEC internal note</small></div>)}</div> : <p className="muted">No AMEC internal notes recorded.</p>}</section>

    <section className="panel intake-readiness-panel"><div className="panel-head"><div><span className="eyebrow">CURRENT STAGE READINESS</span><h3>{engineeringCurrent ? "Engineering Preparation Readiness" : intakeCurrent ? "Intake Readiness" : "Readiness & handoff"}</h3></div><button className="text-button" onClick={() => void validate()}>Recheck</button></div><p className={gateState === "RECONCILIATION_REQUIRED" ? "warning-copy" : "muted"}>{gateMessage}</p>{gateState === "RECONCILIATION_REQUIRED" && <div className="bd-gap-list blocker">{asList(gate.intake?.blockers || readiness.blockers).map((item: any) => <span key={item.code || item.label}>⚠ {item.label || item}</span>)}<button className="button-secondary" onClick={() => document.getElementById("proposal-client")?.scrollIntoView({ behavior: "smooth" })}>Review Intake</button></div>}{asList(validation.blockers).length ? <div className="bd-gap-list blocker">{asList(validation.blockers).map((item: any) => <span key={item.code}>⚠ {item.label}</span>)}</div> : <div className="bd-gap-list"><span>✓ Proposal identity retained</span><span>✓ Source evidence and stage history remain auditable</span></div>}{intakeCurrent && <button className="button-primary" onClick={() => void proceed()} disabled={!readiness.ready || !canEditClient}>Proceed to Engineering Preparation</button>}{engineeringCurrent && <p className="muted">Engineering is the current owner. Commercial Review remains locked until Engineering handoff is recorded.</p>}</section>

    <section id="proposal-review" className={`panel bd-accept-review-panel ${currentRank >= 2 ? "stage-current" : "stage-future"}`}><div className="panel-head"><div><span className="eyebrow">REVIEW / AUTHORITY</span><h3>Proposal Review / Authority</h3></div><span className="stage-badge">{currentRank >= 2 ? "Available for commercial review" : "Locked preview"}</span></div><p className="muted">Human commercial Proposal authority is separate from government authority and does not create an AuthorityCase.</p><div className="bd-summary-grid"><div><b>Client / Contact</b><p>{safeText(forms.commercial_client?.display_name || fields.client_name)} · {safeText(forms.proposal_contact?.display_name || fields.attn_contact, "Contact pending")}</p></div><div><b>Site / Property</b><p>{safeText(forms.site_context?.location_text || fields.location)} · {site.area_value ? `${site.area_value} ${site.area_unit} · ${areaKindText(site.area_kind)}` : "Area basis pending"}</p></div><div><b>AMEC Scope / Regulatory</b><p>{safeText(fields.scope_of_work || fields.sow, "Scope pending")} · {asList(forms.regulatory_scope_intents).length} preliminary intent(s)</p></div><div><b>Commercial</b><p>{amountText(fields.price, fields.currency)} · {safeText(fields.duration || fields.period, "Duration pending")}</p></div><div><b>Authority status</b><p>{proposal.authority?.status_label || "Review status not available"}</p></div><div><b>Dashboard configuration</b><p>Template {validation.template?.item ? `v${validation.template.item.version}` : "unresolved"} · Checklist {validation.checklist?.item ? `v${validation.checklist.item.version}` : "unresolved"}</p></div></div>{currentRank < 2 && <p className="muted">Review and Authority actions unlock after Engineering handoff and Commercial Review.</p>}</section>

    <section className="panel"><div className="panel-head"><div><span className="eyebrow">READINESS CONSOLIDATION</span><h3>{currentRank >= 2 ? (validation.ready ? "Ready for human Accept" : "Action required") : "Final acceptance readiness"}</h3></div><button className="text-button" onClick={() => void validate()}>Revalidate</button></div>{currentRank < 2 ? <p className="muted">Final acceptance readiness is preview-only until the Proposal reaches Commercial Review.</p> : asList(validation.blockers).length ? <div className="bd-gap-list blocker">{asList(validation.blockers).map((item: any) => <span key={item.code}>⚠ {item.label}</span>)}</div> : <div className="inline-message">No blocking item.</div>}{asList(validation.warnings).map((item: any) => <div className="bd-gap-list warning" key={item.code}>⚠ {item.label}</div>)}</section>

    <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">CLIENT RESPONSE</span><h3>Client Response</h3></div><span className="stage-badge">{responseCurrent ? "Current action" : "Locked until accepted review"}</span></div>{asList(proposal.hardening?.client_responses).length ? <div className="bd-v2-list">{asList(proposal.hardening.client_responses).map((item: any) => <div key={item.id}><b>{safeText(item.response_type)}</b><span>{safeText(item.notes)}</span><small>{safeText(item.recorded_by)} · {item.recorded_at ? new Date(item.recorded_at).toLocaleString() : "Date unavailable"}</small></div>)}</div> : <p className="muted">No external Client Response recorded.</p>}{responseCurrent && canEditClient ? <div className="bd-inline-add"><select aria-label="Client Response type" value={responseType} onChange={(event) => setResponseType(event.target.value)}><option value="">Select response…</option><option value="ACCEPTED">Accepted</option><option value="DECLINED">Declined</option><option value="CHANGE_REQUESTED">Change requested</option><option value="EXPIRED">Expired</option><option value="WITHDRAWN">Withdrawn</option></select><input aria-label="Client Response evidence notes" placeholder="Evidence / notes / source" value={responseNotes} onChange={(event) => setResponseNotes(event.target.value)} /><button className="button-secondary" onClick={() => void recordResponse()} disabled={!responseType}>Record response</button></div> : <p className="muted">Client Response controls are locked until the accepted Proposal revision reaches this stage.</p>}</section>

    <section className="panel bd-v2-section"><div className="panel-head"><div><span className="eyebrow">COMMERCIAL OUTCOME</span><h3>Commercial Outcome</h3></div><span className="stage-badge">{responseCurrent ? "Available after Client Response" : "Locked until Client Response"}</span></div><p>{proposal.hardening?.commercial_outcome ? `${safeText(proposal.hardening.commercial_outcome.outcome)} · ${safeText(proposal.hardening.commercial_outcome.reason)}` : "No commercial outcome recorded."}</p>{responseCurrent && canEditCommercial ? <div className="bd-inline-add"><select aria-label="Commercial outcome" value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="">Select outcome…</option><option value="WON">Won</option><option value="LOST">Lost</option><option value="WITHDRAWN">Withdrawn</option><option value="EXPIRED">Expired</option><option value="CONVERTED">Converted</option><option value="SUPERSEDED">Superseded</option></select><button className="button-secondary" onClick={() => void recordOutcome()} disabled={!outcome}>Record outcome</button></div> : <p className="muted">Commercial outcome controls are locked until Client Response is recorded.</p>}</section>

    <section className={`panel bd-review-panel ${currentRank >= 2 ? "stage-current" : "stage-future"}`}><div><span className="eyebrow">PROPOSAL ACCEPTANCE &amp; OUTPUTS</span><h3>Human Accept → Proposal and Checklist outputs</h3><p>{accepted ? "This Proposal has an immutable accepted revision." : "Not yet available. Acceptance remains a human decision after Commercial Review."}</p></div>{currentRank >= 2 && !accepted && canEditCommercial && <button className="button-primary" onClick={() => void accept()} disabled={!validation.ready || proposal.authority?.status === "BLOCKED"}>Accept Proposal</button>}{currentRank < 2 && <button className="button-secondary" disabled>Accept Proposal · locked until Commercial Review</button>}<div className="bd-output-links">{proposal.outputs?.available ? <><a className="text-button" download={proposal.outputs.proposal?.filename} href={`/api/bd/proposals/${proposal.id}/outputs/proposal`}>Proposal Download</a><a className="text-button" download={proposal.outputs.checklist?.filename} href={`/api/bd/proposals/${proposal.id}/outputs/checklist`}>Checklist Download</a><a className="text-button" href={`/api/bd/proposals/${proposal.id}/handoff/contract`}>View Contract eligibility</a></> : <span className="muted">Outputs become available only after human Accept.</span>}</div></section>

    <section id="proposal-history" className="panel"><div className="panel-head"><div><span className="eyebrow">WORK · ISSUES · NOTIFICATIONS · HISTORY</span><h3>Proposal history and lineage</h3></div><small>{asList(proposal.stage_history).length} stage event(s) · {asList(proposal.revision_history).length} accepted revision(s)</small></div>{informationChanged && <div className="inline-message">Current information has changed since this Proposal was accepted.</div>}{informationChanged && canEditCommercial && <button className="button-secondary" onClick={() => void createRevision()}>Create new Proposal revision</button>}{asList(proposal.stage_history).length ? <div className="bd-history-list">{asList(proposal.stage_history).map((item: any, index: number) => <div className="bd-history-row" key={`${item.event_type}-${item.occurred_at}-${index}`}><b>{safeText(item.event_type)}</b><span>{safeText(item.actor)}</span><span>{item.occurred_at ? new Date(item.occurred_at).toLocaleString() : "Date unavailable"}</span><code>{safeText(item.correlation_id, "correlation unavailable")}</code></div>)}</div> : <p className="muted">No stage history recorded yet.</p>}</section>
  </>;
}

function headers(role: Role) { return { "X-Dev-Role": role }; }
