import { useEffect, useState, type ReactNode } from "react";
import { api } from "./api";

export function ArtifactStatusBadge({ status }: { status: string }) { return <span className="tag">{status}</span>; }
export function TemplateVersionBadge({ version }: { version?: string }) { return <span className="tag">TEMPLATE {version || "SYNTHETIC"}</span>; }
export function HumanAuthorityBadge() { return <span className="tag warning">HUMAN AUTHORITY REQUIRED</span>; }
export function SafeDefaultBanner({ children = "Synthetic prototype · no external writes · human send/submission required" }: { children?: ReactNode }) { return <div className="synthetic-note unified-safe-banner">{children}</div>; }
export function PrototypeOnlyBanner() { return <SafeDefaultBanner>PROTOTYPE-ONLY RUNTIME · STAGE 2 DISPOSITION UNDECIDED</SafeDefaultBanner>; }
export function EvidenceSourcePanel({ sources = [] }: { sources?: string[] }) { return <div className="evidence-source-panel"><b>Evidence sources</b><small>{sources.length ? sources.join(" · ") : "Shared governed context; synthetic evidence"}</small></div>; }
export function CommunicationStatusBadge({ status }: { status: string }) { return <span className={`status status-${String(status).toLowerCase().replaceAll("_", "-")}`}>{status}</span>; }
export function CapabilityStatusBadge({ status = "CANDIDATE_OR_DRAFT" }: { status?: string }) { return <span className="tag">{status}</span>; }
export function ArtifactPreview({ artifact }: { artifact: any }) { return <div className="artifact-preview"><div><b>{artifact?.artifact_type || "Rendered artifact"}</b><ArtifactStatusBadge status={artifact?.status || "RENDERED"} /></div><small>Content hash: {artifact?.content_hash || "synthetic"}</small><EvidenceSourcePanel sources={artifact?.source_revision_ids} /></div>; }
export function StaleArtifactWarning() { return <div className="stale-warning">STALE OUTPUT · re-render and re-review before use</div>; }
export function CommunicationDraftPanel({ draft }: { draft: any }) { return <div className="communication-draft-panel"><div><b>{draft?.subject || "Communication draft"}</b><CommunicationStatusBadge status={draft?.status || "HUMAN_REVIEW"} /></div><small>{draft?.body || "Synthetic draft body"}</small><HumanAuthorityBadge /></div>; }

const assistantLabels: Record<string, string> = { BD_ASSISTANT: "Business Development", ADMIN_ASSISTANT: "Owner", ENGINEERING_REVIEW_ASSISTANT: "Engineering", PROJECT_PERMIT_COORDINATION_ASSISTANT: "Owner" };
const summaryLabels: Record<string, string> = { action_required: "Action Required", reviews_waiting: "Reviews Waiting", blocked_work: "Blocked Work", authority_changes: "Authority Changes", communication_drafts: "Communication Drafts", delivery_failures: "Delivery Failures" };

export function UnifiedMyWorkPanel() {
  const [data, setData] = useState<any>(null); const [assistant, setAssistant] = useState(""); const [role, setRole] = useState("");
  useEffect(() => { const query = new URLSearchParams(); if (assistant) query.set("assistant_id", assistant); if (role) query.set("role", role); api<any>(`/api/my-work${query.toString() ? `?${query}` : ""}`).then(setData).catch(() => setData(null)); }, [assistant, role]);
  if (!data) return <section className="panel unified-work-panel"><PrototypeOnlyBanner /><p>Unified assistant work is unavailable until the backend is running.</p></section>;
  return <section className="panel unified-work-panel">
    <div className="panel-head"><div><span className="eyebrow">E7 · SHARED PERSONA EXPERIENCE</span><h3>AMEC Work across shared operating context</h3></div><div className="unified-controls"><select aria-label="Work persona lens" className="unified-filter" value={assistant} onChange={e => setAssistant(e.target.value)}><option value="">All personas</option>{(data.assistant_ids || []).map((id: string) => <option key={id} value={id}>{assistantLabels[id] || id}</option>)}</select><select aria-label="Queue owner" className="unified-filter" value={role} onChange={e => setRole(e.target.value)}><option value="">All owner roles</option><option value="COMMERCIAL_APPROVER">Business Development</option><option value="AUTHORIZED_ENGINEER">Engineering</option><option value="ADMIN_PROJECT_COORDINATOR">Owner</option></select></div></div>
    <SafeDefaultBanner>DEMO AS · SYNTHETIC ONLY · three personas share one governed queue · human-controlled send required</SafeDefaultBanner><div className="unified-summary-grid">{Object.entries(data.summary || {}).map(([key, value]) => <div key={key}><span>{summaryLabels[key] || key.replaceAll("_", " ")}</span><strong>{String(value)}</strong></div>)}</div>
    <div className="unified-task-list">{(data.items || []).slice(0, 20).map((item: any) => <article className="unified-task" key={item.id} data-testid={`unified-task-${item.id}`}><div><span className="eyebrow">{assistantLabels[item.assistant_id] || item.assistant_id}</span><b>{item.title}</b><small>Source family: WorkflowTask · {item.context_type || "SHARED_CONTEXT"} · {item.owner?.role || item.owner_role} · {item.status}</small><small>NextAction: {item.next_action_details?.label || item.next_action} · {item.next_action_details?.reason || "Deterministic shared-state action"}</small><EvidenceSourcePanel sources={item.evidence_summary?.source_revision_ids || ["shared context"]} /></div><div>{item.blocking && <ArtifactStatusBadge status="BLOCKED" />}<HumanAuthorityBadge /><a className="button-secondary" href={item.next_action_details?.deep_link || item.deep_link || `/work/${item.context_id || item.id}`}>Open work</a></div></article>)}{!(data.items || []).length && <p className="muted">No unified tasks are currently visible.</p>}</div>
    <div className="unified-secondary-panels"><div><b>Issues by source family</b>{(data.issues || []).slice(0, 4).map((issue: any) => <small key={issue.id}>{issue.source_type || issue.entity_type || "SYSTEM_BLOCK"} · {issue.title || issue.reason || issue.status}</small>)}</div><div><b>Communication drafts</b>{(data.communications || []).slice(0, 4).map((draft: any) => <small key={draft.id}>{draft.communication_type || "DRAFT"} · {draft.status} · Human-controlled send</small>)}</div></div>
  </section>;
}
