import { useEffect, useState } from "react";
import { api } from "./api";
import "./week9.css";

const badge = (value?: string) => <span className={`status status-${String(value || "UNKNOWN").toLowerCase().replaceAll("_", "-")}`}>{value || "UNKNOWN"}</span>;

export function AttachmentGridPage() {
  const [projects, setProjects] = useState<any[]>([]); const [projectId, setProjectId] = useState(""); const [revisionId, setRevisionId] = useState(""); const [manifest, setManifest] = useState<any>(null); const [grids, setGrids] = useState<any>(null); const [fingerprint, setFingerprint] = useState<any>(null); const [message, setMessage] = useState("");
  const load = async (id = projectId) => { if (!id) return; try { const packageState = await api<any>(`/api/projects/${id}/package`); const rid = packageState.package?.preparation_revision_id; setRevisionId(rid || ""); if (!rid) return; const [m, g, f] = await Promise.all([api<any>(`/api/preparation-revisions/${rid}/attachment-manifest`), api<any>(`/api/preparation-revisions/${rid}/grids/BUILDING_FLOOR_UNIT/intent`), api<any>(`/api/preparation-revisions/${rid}/portal-structure-fingerprint?scope=ATTACHMENT_TREE`)]); setManifest(m); setGrids(g); setFingerprint(f); } catch (e: any) { setMessage(e.message); } };
  useEffect(() => { api<any[]>("/api/projects").then(x => { setProjects(x); if (x[0]) setProjectId(x[0].id); }).catch(e => setMessage(e.message)); }, []);
  useEffect(() => { if (projectId) load(projectId); }, [projectId]);
  const drift = async () => { if (!revisionId) return; try { const x = await api<any>(`/api/preparation-revisions/${revisionId}/portal-structure-fingerprint/capture`, { method: "POST", body: JSON.stringify({ scope: "ATTACHMENT_TREE", observed_structure: { categories: [{ code: "UNEXPECTED_SYNTHETIC_CATEGORY" }] } }) }); setFingerprint({ fingerprints: [x.fingerprint] }); setMessage("Structure drift recorded; assisted fallback active."); } catch (e: any) { setMessage(e.message); } };
  return <div className="week9-page"><div className="page-intro"><div><span className="eyebrow">WEEK 9 · ATTACHMENT + REPEATING-GRID HARDENING</span><h2>Preparation integrity</h2><p>Exact category, exact approved version, persistence evidence, and identity-based grid reconciliation. Synthetic assisted mode only.</p></div><select value={projectId} onChange={e => setProjectId(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.project_number} · {p.project_name}</option>)}</select></div>{message && <div className="inline-message">{message}</div>}{!revisionId && <div className="panel week9-warning">Create or select a current PreparationRevision to inspect Week 9 attachment and grid controls.</div>}
    {revisionId && <><div className="metric-grid"><div className="metric blue"><span>Signed categories</span><strong>{manifest?.categories?.length || 0}</strong><small>Scenario-controlled category tree</small></div><div className="metric teal"><span>Manifest items</span><strong>{manifest?.items?.length || 0}</strong><small>{badge(manifest?.manifest?.status)}</small></div><div className="metric orange"><span>Canonical rows</span><strong>{grids?.intents?.length || 0}</strong><small>Business-key matching</small></div><div className="metric red"><span>Safety</span><strong>ASSISTED</strong><small>No machine submit or silent remap</small></div></div>
      <div className="week9-columns"><section className="panel"><div className="panel-head"><div><span className="eyebrow">ATTACHMENT MANIFEST</span><h3>Exact category associations</h3></div><button className="button-secondary" onClick={() => load()}>Refresh</button></div>{(manifest?.items || []).map((item: any) => <div className="attachment-row" key={`${item.category_code}-${item.document_version_id}`}><div><b>{item.category_code}</b><small>{item.requirement_state} · {item.intended_portal_filename || "No file"}</small><small className="ltr-id">{item.document_version_id || "NOT_APPLICABLE"} · {item.file_sha256 || "—"}</small></div>{badge(item.status)}</div>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">REPEATING GRID</span><h3>Canonical row identity</h3></div></div>{(grids?.intents || []).map((item: any) => <div className="grid-row" key={item.id}><span><b>{item.row_type}</b><small className="ltr-id">{item.canonical_row_id}</small></span><span className="ltr-id">{item.business_key}</span>{badge(item.status)}</div>)}</section></div>
      <div className="week9-columns"><section className="panel"><div className="panel-head"><div><span className="eyebrow">PORTAL STRUCTURE</span><h3>Attachment tree fingerprint</h3></div><button className="button-secondary" onClick={drift}>Simulate drift</button></div>{(fingerprint?.fingerprints || []).map((f: any) => <div className="fingerprint-row" key={f.id}><span className="ltr-id">{f.expected_hash.slice(0, 16)}…</span><b>→</b><span className="ltr-id">{f.observed_hash.slice(0, 16)}…</span>{badge(f.status)}{f.status === "DRIFTED" && <small>Assisted fallback active</small>}</div>)}{!fingerprint?.fingerprints?.length && <p className="muted">No structure evidence captured yet.</p>}</section><section className="panel"><span className="eyebrow">CONTROL PATH</span><h3>Evidence before confidence</h3><p className="journey">Approved DocumentVersion → locked manifest item → exact category → association intent → persisted portal state → reconcile → explicit match or exception.</p><p className="muted">Portal-derived values remain separate from deed/design truth and require configured review.</p></section></div></>}
  </div>;
}
