import { useEffect, useState } from "react";
import { api } from "./api";

export function Week14Page() {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState("");
  const load = async () => { try { const [r, mode, evidence, roles] = await Promise.all([api<any>("/api/acceptance-rehearsals"), api<any>("/api/production-mode"), api<any>("/api/g10/evidence"), api<any>("/api/role-readiness")]); setData({ r, mode, evidence, roles }); } catch (e:any) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  if (!data) return <div className="loading">Loading Week 14 acceptance evidence…</div>;
  const latest = data.r.rehearsals?.[0];
  return <><div className="page-intro"><div><span className="eyebrow">WEEK 14 · ACCEPTANCE REHEARSAL</span><h2>Assisted mode / G10 evidence pack</h2><p>Acceptance-style evidence is separated from formal G10, live authorization, and client approval.</p></div></div>{message && <div className="inline-message">{message}</div>}<div className="metric-grid"><div className="metric teal"><span>Rehearsal</span><strong>{latest?.result || "PENDING"}</strong><small>canonical fixture</small></div><div className="metric blue"><span>Production mode</span><strong>ASSISTED</strong><small>{data.mode.decision.decision}</small></div><div className="metric orange"><span>G10 evidence items</span><strong>{data.evidence.items.length}</strong><small>external conditions visible</small></div><div className="metric red"><span>Formal G10</span><strong>NO</strong><small>Week 15 gate</small></div></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>G10 evidence index</h3><span className="tag">NO FABRICATED PERMISSION</span></div>{data.evidence.items.map((x:any)=><div className="operator-row" key={x.id}><div><b>{x.criterion_id}</b><small>{x.requirement}</small></div><span className="tag">{x.status}</span></div>)}</section><section className="panel"><div className="panel-head"><h3>Role readiness</h3><span className="tag">CLIENT APPROVAL EXTERNAL</span></div>{data.roles.matrix.map((x:any)=><div className="operator-row" key={x.id}><div><b>{x.role}</b><small>{x.competency_evidence}</small></div><span className="tag">{x.client_approved ? "CLIENT APPROVED" : "READY_FOR_CLIENT_APPROVAL"}</span></div>)}</section></div><section className="panel"><div className="panel-head"><h3>Gate boundary</h3><span className="tag warning">READY FOR FORMAL REVIEW ≠ G10 GO</span></div><p>ASSISTED mode is the selected Wave 3 path. Automated draft writes remain unauthorized and cannot block the MVP. Live Ministry permissions, production security evidence, client workflow approval, and formal G10 remain external conditions.</p></section></>;
}
