import { useEffect, useState } from "react";
import { api } from "./api";

export function Week14Page() {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState("");
  const load = async () => { setMessage(""); setData(null); try { const [r, mode, evidence, roles] = await Promise.all([api<any>("/api/acceptance-rehearsals"), api<any>("/api/production-mode"), api<any>("/api/g10/evidence"), api<any>("/api/role-readiness")]); if (!Array.isArray(r?.rehearsals) || !mode?.decision || typeof mode.decision.decision !== "string" || !Array.isArray(evidence?.items) || !Array.isArray(roles?.matrix)) throw new Error("Week 14 acceptance evidence is incomplete. Retry after the evidence services recover."); setData({ r, mode, evidence, roles }); } catch (e:any) { setMessage(e instanceof Error ? e.message : "Week 14 acceptance evidence is unavailable. Retry required."); } };
  useEffect(() => { load(); }, []);
  if (!data && !message) return <div className="loading">Loading Week 14 acceptance evidence…</div>;
  if (!data) return <section className="panel error-state" role="alert"><h2>Week 14 acceptance evidence could not be loaded</h2><p>{message}</p><button className="button-primary" onClick={load}>Retry</button></section>;
  const latest = data.r.rehearsals?.[0];
  return <><div className="page-intro"><div><span className="eyebrow">WEEK 14 · ACCEPTANCE REHEARSAL</span><h2>Assisted mode / G10 evidence pack</h2><p>Acceptance-style evidence is separated from formal G10, live authorization, and client approval.</p></div></div>{message && <div className="inline-message">{message}</div>}<div className="metric-grid"><div className="metric teal"><span>Rehearsal</span><strong>{latest?.result || "PENDING"}</strong><small>canonical fixture</small></div><div className="metric blue"><span>Production mode</span><strong>ASSISTED</strong><small>Assisted review ready</small></div><div className="metric orange"><span>G10 evidence items</span><strong>{data.evidence.items.length}</strong><small>external conditions visible</small></div><div className="metric red"><span>Formal G10</span><strong>NO</strong><small>Week 15 gate</small></div></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>G10 evidence index</h3><span className="tag">NO FABRICATED PERMISSION</span></div>{data.evidence.items.map((x:any)=><div className="operator-row" key={x.id}><div><b>{x.criterion_id}</b><small>{x.requirement}</small></div><span className="tag">{String(x.status).replaceAll("_", " ")}</span></div>)}</section><section className="panel"><div className="panel-head"><h3>Role readiness</h3><span className="tag">CLIENT APPROVAL EXTERNAL</span></div>{data.roles.matrix.map((x:any)=><div className="operator-row" key={x.id}><div><b>{String(x.role).replaceAll("_", " ")}</b><small>{x.competency_evidence}</small></div><span className="tag">{x.client_approved ? "Client approved" : "Awaiting client approval"}</span></div>)}</section></div><section className="panel"><div className="panel-head"><h3>Gate boundary</h3><span className="tag warning">READY FOR FORMAL REVIEW ≠ G10 GO</span></div><p>ASSISTED mode is the selected Wave 3 path. Automated draft writes remain unauthorized and cannot block the MVP. Live Ministry permissions, production security evidence, client workflow approval, and formal G10 remain external conditions.</p></section></>;
}
