import { useEffect, useState } from "react";
import { api } from "./api";

export function Week13Page() {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState("");
  const load = async () => { try { const [recurrence, ops, recovery, defects] = await Promise.all([api<any>("/api/recurrence/analysis"), api<any>("/api/operations/report"), api<any>("/api/recovery/manifests"), api<any>("/api/shadow-defects")]); setData({ recurrence, ops: ops.report, recovery, defects }); } catch (e:any) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  if (!data) return <div className="loading">Loading Week 13 operations evidence…</div>;
  return <><div className="page-intro"><div><span className="eyebrow">WEEK 13 · OPERABLE SERVICE</span><h2>Recurrence, support & integrity operations</h2><p>Deterministic history reuse, preventive context, role boundaries, incident freeze, and TEST recovery evidence. No professional conclusion is automated.</p></div></div>{message && <div className="inline-message">{message}</div>}<div className="metric-grid"><div className="metric teal"><span>Recurrence groups</span><strong>{data.recurrence.items.length}</strong><small>deterministic keys</small></div><div className="metric blue"><span>Monitoring active</span><strong>{data.ops.monitoring.active}</strong><small>drifted: {data.ops.monitoring.drifted}</small></div><div className="metric orange"><span>Support cases</span><strong>{data.ops.support_cases}</strong><small>L1/L2/L3 bounded model</small></div><div className="metric red"><span>P1 incidents</span><strong>{data.ops.p1_incidents}</strong><small>evidence-preserving hold</small></div></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>Finding recurrence overview</h3><span className="tag">NO FUZZY AUTO-LINKING</span></div>{(data.recurrence.items||[]).slice(0,10).map((x:any)=><div className="operator-row" key={x.id}><div><b>{x.finding_code}</b><small>{x.recurrence_key}</small></div><span className="tag">{x.classification}</span><strong>{x.occurrence_count}</strong></div>)}{!data.recurrence.items.length && <p className="muted">Run analysis after a current Finding exists.</p>}</section><section className="panel"><div className="panel-head"><h3>Operational observability</h3><span className="tag">SYNTHETIC</span></div>{Object.entries(data.ops).filter(([k])=>!['monitoring','evidence_class','fixture'].includes(k)).slice(0,9).map(([k,v]:any)=><div className="exposure-row" key={k}><span>{k.replaceAll("_"," ")}</span><b>{String(v)}</b></div>)}</section></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>Recovery readiness</h3><span className="tag">TEST ONLY</span></div>{(data.recovery.rehearsals||[]).map((x:any)=><div className="operator-block" key={x.id}><b>{x.rehearsal_type} · {x.result}</b><small>Formal G10: {x.not_formal_g10 ? "NO" : "YES"}</small></div>)}<p className="muted">Restore rehearsal evidence remains distinct from formal G10.</p></section><section className="panel"><div className="panel-head"><h3>Support / defect boundary</h3><span className="tag warning">PROFESSIONAL DECISION HUMAN-ONLY</span></div><div className="operator-block"><b>L1</b><small>Process Champion triage and routing.</small></div><div className="operator-block"><b>L2</b><small>PermitOps / Arkan application, configuration, and adapter support.</small></div><div className="operator-block"><b>L3</b><small>External authority, infrastructure, Synology, Microsoft, or vendor dependency.</small></div></section></div></>;
}
