import { useEffect, useState } from "react";
import { api } from "./api";
import "./week8.css";

const badge = (value?: string) => <span className={`status status-${String(value || "UNKNOWN").toLowerCase().replaceAll("_", "-")}`}>{value || "UNKNOWN"}</span>;

export function LineageValidityPage({ projectId }: { projectId?: string }) {
  const [projects, setProjects] = useState<any[]>([]); const [selected, setSelected] = useState(projectId || ""); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); const [corpus, setCorpus] = useState<any>(null);
  const load = async (id = selected) => { if (!id) return; try { const [lineage, stale, validity] = await Promise.all([api<any>(`/api/projects/${id}/lineage`), api<any>(`/api/projects/${id}/stale-items`), api<any>(`/api/projects/${id}/validity-dashboard`)]); setData({ lineage, stale, validity }); } catch (e: any) { setMessage(e.message); } };
  useEffect(() => { api<any[]>("/api/projects").then(x => { setProjects(x); if (!selected && x[0]) setSelected(x[0].id); }).catch(e => setMessage(e.message)); }, []);
  useEffect(() => { if (selected) load(selected); }, [selected]);
  const runCorpus = async () => { try { setCorpus(await api<any>("/api/corpus-runs", { method: "POST", body: JSON.stringify({ project_id: selected, label: "SYNTHETIC / NON-CONTRACTUAL" }) })); setMessage("Corpus run completed"); } catch (e: any) { setMessage(e.message); } };
  return <div className="week8-page"><div className="page-intro"><div><span className="eyebrow">WEEK 8 · LINEAGE / VALIDITY / STALENESS</span><h2>Truth impact console</h2><p>Every package and preparation revision shows what changed, why it is stale, and what must be revalidated. No automatic approval or submission.</p></div><select value={selected} onChange={e => setSelected(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.project_number} · {p.project_name}</option>)}</select></div>
    {message && <div className="inline-message">{message}</div>}
    <div className="metric-grid"><div className="metric red"><span>Stale items</span><strong>{data?.stale?.reasons?.length || 0}</strong><small>Revalidation remains explicit</small></div><div className="metric blue"><span>Lineage edges</span><strong>{data?.lineage?.edges?.length || 0}</strong><small>Relational, version-aware graph</small></div><div className="metric teal"><span>Document validity</span><strong>{data?.validity?.validity?.documents?.filter((x: any) => x.validity_status === "VALID").length || 0}</strong><small>Current synthetic evidence</small></div><div className="metric orange"><span>Safety</span><strong>HUMAN GATE</strong><small>Replacement package is never auto-approved</small></div></div>
    <div className="week8-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">STALE REGISTER</span><h3>Impact requiring review</h3></div><button className="button-secondary" onClick={() => load()}>Refresh</button></div>{(data?.stale?.reasons || []).map((r: any) => <div className="week8-row" key={r.id}><div><b>{r.target_type}</b><small className="ltr-id">{r.target_id}</small><p>{r.reason}</p></div><div>{badge("STALE")}<small>{r.reason_code}</small></div></div>)}{!data?.stale?.reasons?.length && <p className="muted">No current stale reasons. Material changes will appear here with their lineage impact.</p>}</section>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">LINEAGE</span><h3>Recent dependency edges</h3></div></div>{(data?.lineage?.edges || []).slice(-12).reverse().map((e: any) => <div className="lineage-row" key={e.id}><span>{e.upstream_type}<small className="ltr-id">{e.upstream_id.slice(0, 12)}…</small></span><b>→</b><span>{e.downstream_type}<small className="ltr-id">{e.downstream_id.slice(0, 12)}…</small></span></div>)}</section></div>
    <section className="panel validity-panel"><div className="panel-head"><div><span className="eyebrow">VALIDITY</span><h3>Evidence and credentials</h3></div><button className="button-primary" onClick={runCorpus}>Run synthetic corpus</button></div><div className="validity-columns"><div><h4>Documents</h4>{(data?.validity?.validity?.documents || []).slice(0, 8).map((x: any) => <div className="validity-row" key={x.id}><span className="ltr-id">{x.document_version_id.slice(0, 12)}…</span>{badge(x.validity_status)}</div>)}</div><div><h4>Authority dependencies</h4>{(data?.validity?.validity?.dependencies || []).map((x: any) => <div className="validity-row" key={x.id}><span className="ltr-id">{x.approval_dependency_id.slice(0, 12)}…</span>{badge(x.status)}</div>)}</div><div><h4>Professional credentials</h4>{(data?.validity?.validity?.professional_credentials || []).map((x: any) => <div className="validity-row" key={x.id}><span>{x.credential_type}</span>{badge(x.status)}</div>)}</div></div></section>
    {corpus && <section className="panel corpus-result"><span className="eyebrow">CORPUS / SHADOW EVIDENCE</span><h3>{corpus.run?.label}</h3><p>{corpus.run?.metrics_json?.case_count || 0} cases · classification agreement {Math.round((corpus.run?.metrics_json?.document_classification_agreement_rate || 0) * 100)}% · false accepts {corpus.run?.metrics_json?.false_accept_count || 0}</p></section>}
  </div>;
}
