import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { Icon } from "./Icon";

type Project = { id: string; project_number: string; project_name: string; municipality: string; permit_type: string };

const badge = (value: string | undefined) => <span className={`status status-${String(value || "working").toLowerCase().replaceAll("_", "-")}`}>{value || "—"}</span>;

export function PackageReadinessPage({ initialProjectId }: { initialProjectId?: string } = {}) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectId, setProjectId] = useState("");
  const [readiness, setReadiness] = useState<any>(null);
  const [packageData, setPackageData] = useState<any>(null);
  const [forms, setForms] = useState<any>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { api<Project[]>("/api/projects").then(items => { setProjects(items); if (initialProjectId && items.some(item => item.id === initialProjectId)) setProjectId(initialProjectId); else if (items[0]) setProjectId(items[0].id); }).catch(e => setMessage(e.message)); }, [initialProjectId]);
  useEffect(() => { if (!projectId) return; api<any>(`/api/projects/${projectId}/readiness`).then(setReadiness).catch(e => setMessage(e.message)); api<any>(`/api/projects/${projectId}/forms`).then(setForms).catch(() => {}); }, [projectId]);
  const selected = useMemo(() => projects.find(p => p.id === projectId), [projects, projectId]);
  const evaluate = () => api<any>(`/api/projects/${projectId}/readiness/evaluate`, { method: "POST" }).then(setReadiness).catch(e => setMessage(e.message));
  const approveEvidence = async () => {
    const docs = await api<any[]>(`/api/projects/${projectId}/documents`);
    const required = new Set(["TITLE_DEED", "OWNER_QID", "DRAWING_SET"]);
    await Promise.all(docs.filter(d => required.has(d.document_type) && d.current_version_id).map(d => api(`/api/document-versions/${d.current_version_id}/approval-state`, { method: "PATCH", body: JSON.stringify({ approval_state: "APPROVED", actor_id: "synthetic-reviewer" }) })));
    evaluate();
  };
  const buildPackage = () => api<any>(`/api/projects/${projectId}/package`, { method: "POST" }).then(x => { setPackageData(x); setMessage("Package manifest generated from exact approved versions."); }).catch(e => setMessage(e.message));
  const renderForm = (code: string) => api<any>(`/api/projects/${projectId}/forms/${code}/render`, { method: "POST" }).then(x => { setForms((v: any) => ({ ...v, rendered: [x.rendered_form, ...(v?.rendered || [])] })); setMessage(`${code} rendered from current VerifiedAssertions.`); }).catch(e => setMessage(e.message));
  return <>
    <div className="page-intro"><div><span className="eyebrow">WEEK 4 · TRUSTED PACKAGE FOUNDATION</span><h2>Readiness & package control</h2><p>Deterministic readiness over verified facts, current approved versions, dependencies, drawing checks, and internal human gates.</p></div></div>
    <section className="panel week45-toolbar"><label>Canonical project<select value={projectId} onChange={e => setProjectId(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.project_number} · {p.project_name}</option>)}</select></label><div className="week45-actions"><button className="button-secondary" onClick={evaluate}>Evaluate readiness</button><button className="button-secondary" onClick={approveEvidence}>Approve synthetic evidence</button><button className="button-primary" disabled={readiness?.evaluation?.overall_status === "BLOCKED"} onClick={buildPackage}>Build exact package</button></div></section>
    {message && <div className="inline-message">{message}</div>}
    {selected && <div className="metric-grid"><div className="metric blue"><span>Project</span><strong>{selected.project_number}</strong><small>{selected.project_name}</small></div><div className="metric teal"><span>Readiness</span><strong>{readiness?.evaluation?.overall_status || "—"}</strong><small>{readiness?.evaluation?.blocker_count || 0} blockers · {readiness?.evaluation?.warning_count || 0} warnings</small></div><div className="metric orange"><span>Package</span><strong>{packageData?.package?.status || "—"}</strong><small>{packageData?.manifest?.manifest_hash?.slice(0, 12) || "No manifest yet"}</small></div><div className="metric red"><span>Safety boundary</span><strong>NO SUBMIT</strong><small>Human submission required</small></div></div>}
    <div className="two-col"><section className="panel"><div className="panel-head"><div><span className="eyebrow">READINESS RESULT</span><h3>Why this project is or is not ready</h3></div>{badge(readiness?.evaluation?.overall_status)}</div>{(readiness?.items || []).map((item: any) => <div className="readiness-row" key={item.id}><span className={item.status === "BLOCKED" ? "readiness-icon fail" : item.status === "WARNING" ? "readiness-icon warn" : "readiness-icon pass"}>{item.status === "BLOCKED" ? <Icon name="alert" size={15} /> : item.status === "WARNING" ? <Icon name="alert" size={15} /> : <Icon name="check" size={15} />}</span><div><b>{item.requirement_code}</b><small>{item.category} · {item.severity}</small><p>{item.reason}</p></div>{badge(item.status)}</div>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">FORMS & UNDERTAKINGS</span><h3>Verified facts → rendered artifact</h3></div></div>{(forms?.templates || []).map((template: any) => <div className="form-row" key={template.template_code}><span><b>{template.name}</b><small>{template.template_code} · v{template.versions?.[0]?.version}</small></span><button className="button-secondary" onClick={() => renderForm(template.template_code)}>Render</button></div>)}<p className="muted">Rendered forms retain input truth hash, template version, rendering-rule versions, and output hash. OCR candidates cannot feed this path.</p></section></div>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">PACKAGE MANIFEST</span><h3>Exact approved versions and attachment categories</h3></div>{packageData?.manifest && badge("LOCKED")}</div>{packageData ? <table><thead><tr><th>Category</th><th>Document version</th><th>SHA-256</th><th>Revision</th><th>Approval</th></tr></thead><tbody>{(packageData.items || []).map((item: any) => <tr key={item.id}><td><b>{item.attachment_category_code}</b></td><td>{item.document_version_id}</td><td>{item.file_sha256}</td><td>{item.revision || "—"}</td><td>{badge(item.approval_state)}</td></tr>)}</tbody></table> : <p className="muted">Package creation is blocked until readiness is deterministic READY.</p>}</section>
  </>;
}

export function MunicipalityPreparationPage({ initialProjectId }: { initialProjectId?: string } = {}) {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [revision, setRevision] = useState<any>(null); const [state, setState] = useState<any>(null); const [message, setMessage] = useState("");
  useEffect(() => { api<Project[]>("/api/projects").then(items => { setProjects(items); if (initialProjectId && items.some(item => item.id === initialProjectId)) setProjectId(initialProjectId); else if (items[0]) setProjectId(items[0].id); }).catch(e => setMessage(e.message)); }, [initialProjectId]);
  const start = async () => { try { const pkg = await api<any>(`/api/projects/${projectId}/package`); const approved = pkg.package.status === "APPROVED" ? pkg : await api<any>(`/api/packages/${pkg.package.id}/approve`, { method: "POST", body: JSON.stringify({ approved_by: "synthetic-requirement-steward" }) }); const r = await api<any>(`/api/projects/${projectId}/preparation-revisions`, { method: "POST", body: JSON.stringify({ package_id: approved.package.id, created_by: "synthetic-preparer" }) }); setRevision(r); setMessage("Preparation snapshot frozen. Assisted entry is ready."); } catch (e: any) { setMessage(e.message); } };
  const loadState = async (r = revision) => { if (!r) return; const [fields, grids, attachments] = await Promise.all([api<any>(`/api/preparation-revisions/${r.revision.id}/municipality/fields`), api<any>(`/api/preparation-revisions/${r.revision.id}/municipality/grids`), api<any>(`/api/preparation-revisions/${r.revision.id}/municipality/attachments`)]); setState({ fields: fields.fields, grids: grids.rows, attachments: attachments.attachments }); };
  const prepare = async () => { try { const r = revision; await api(`/api/preparation-revisions/${r.revision.id}/intended-state`, { method: "POST", body: JSON.stringify({ application_identity: { application_id: r.revision.application_id }, fields: { plot_number: "001234", owner_name: "Yousef Ahmed Ali" }, repeating_rows: state.grids, attachments: state.attachments }) }); await api(`/mock-authority/applications/${r.revision.application_id}/draft`, { method: "PUT", body: JSON.stringify({ state_json: { plot_number: "001234", owner_name: "Yousef Ahmed Ali", buildings: state.grids } }) }); const s = await api<any>(`/api/preparation-revisions/${r.revision.id}/portal-snapshots`, { method: "POST", body: JSON.stringify({ snapshot_type: "REOPENED", capture_method: "SIMULATOR_READ", grid_state: state.grids, attachment_state: state.attachments }) }); const reconciliation = await api<any>(`/api/preparation-revisions/${r.revision.id}/reconcile`, { method: "POST", body: JSON.stringify({ portal_snapshot_id: s.id }) }); setRevision({ ...revision, revision: reconciliation.revision }); setMessage("Persisted simulator state matches intended state."); } catch (e: any) { setMessage(e.message); } };
  return <><div className="page-intro"><div><span className="eyebrow">WEEK 5 · ASSISTED MUNICIPALITY</span><h2>Preparation operator</h2><p>Portal-ordered fields, grids, exact attachments, persisted-state reconciliation, precheck evidence, and human handoff. No portal write or submit action is available.</p></div></div><section className="panel week45-toolbar"><label>Canonical project<select value={projectId} onChange={e => setProjectId(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.project_number} · {p.project_name}</option>)}</select></label><div className="week45-actions"><button className="button-primary" onClick={start}>Create preparation revision</button>{revision && <button className="button-secondary" onClick={() => loadState()}>Load portal contract</button>}</div></section>{message && <div className="inline-message">{message}</div>}{revision && <><div className="metric-grid"><div className="metric teal"><span>Revision</span><strong>R{revision.revision.sequence}</strong><small>{revision.revision.id}</small></div><div className="metric blue"><span>Snapshot</span><strong>{revision.snapshot?.snapshot_hash?.slice(0, 12)}</strong><small>Frozen from approved package</small></div><div className="metric orange"><span>Portal order</span><strong>10 tabs</strong><small>Application → Status / Comments</small></div><div className="metric red"><span>Handoff</span><strong>HUMAN</strong><small>Final Submitter only</small></div></div><section className="panel"><div className="panel-head"><h3>Portal contract</h3><span className="tag">ATTENDED · USER + OTP</span></div>{state ? <><div className="portal-tabs">{["Application", "Property", "Owner", "Building", "Floors", "Units", "Attachments", "Validation", "Precheck", "Status / Comments"].map((tab, i) => <span key={tab} className={i === 0 ? "active" : ""}>{i + 1}. {tab}</span>)}</div><div className="two-col"><div><h3>Fields</h3>{state.fields.map((field: any, i: number) => <div className="operator-row" key={i}><div><b>{field.label}</b><small>{field.portal_tab} · order {field.portal_order} · {field.source_mode}</small></div><strong>{field.canonical_value || "HUMAN DECISION"}</strong><span className="tag">EVIDENCE</span></div>)}</div><div><h3>Repeating rows & attachments</h3><div className="operator-block"><b>{state.grids.length} stable grid rows</b><small>Building and floor identities remain explicit.</small></div><div className="operator-block"><b>{state.attachments.length} exact attachment items</b><small>DocumentVersion and SHA-256 are shown; no folder hunting.</small></div><button className="button-primary" onClick={prepare}>Save / reopen / reconcile simulator state</button></div></div></> : <p className="muted">Load the portal contract to begin assisted preparation.</p>}</section></>}</>;
}
