import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { useLocale } from "./i18n";
import "./week7.css";

const ar: Record<string, string> = {
  BLOCKING: "مانع", MAJOR: "رئيسي", ADVISORY: "إرشادي", OPEN: "مفتوح", ASSIGNED: "مسند",
  IN_PROGRESS: "قيد المعالجة", DISPUTED: "محل اعتراض", UNASSIGNED: "غير مسند", DELIVERED: "تم التسليم",
  FAILED: "فشل", PENDING: "قيد الانتظار", AUTHORITY_PRECHECK: "فحص مسبق من الجهة",
  OFFICIAL_MUNICIPALITY_COMMENT: "تعليق رسمي من البلدية", PORTAL_VALIDATION: "تحقق البوابة",
};
const label = (value: string | undefined) => value ? `${value} / ${ar[value] || value}` : "—";
const badge = (value: string | undefined) => <span className={`status status-${String(value || "working").toLowerCase().replaceAll("_", "-")}`}>{label(value)}</span>;

export function FindingsConsolePage() {
  const [findings, setFindings] = useState<any[]>([]);
  const [tasks, setTasks] = useState<any[]>([]);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [filter, setFilter] = useState("OPEN");
  const { locale, setLocale } = useLocale();
  const rtl = locale === "ar-EG";
  const [message, setMessage] = useState("");
  const load = async () => {
    const [f, t, n] = await Promise.all([api<any>(`/api/findings${filter ? `?status=${filter}` : ""}`), api<any>("/api/tasks"), api<any>("/api/notifications")]);
    setFindings(f.findings || []); setTasks(t.tasks || []); setNotifications(n.notifications || []);
    if (selected) setSelected((f.findings || []).find((x: any) => x.id === selected.id) || selected);
  };
  useEffect(() => { load().catch(e => setMessage(e.message)); }, [filter]);
  const openCount = useMemo(() => findings.filter(f => ["OPEN", "ASSIGNED", "IN_PROGRESS", "DISPUTED", "DEFERRED"].includes(f.status)).length, [findings]);
  const act = async (path: string, init?: RequestInit, success = "Updated") => { try { await api(path, init); setMessage(success); await load(); if (selected) setSelected(await api<any>(`/api/findings/${selected.id}`)); } catch (e: any) { setMessage(e.message); } };
  const selectedTask = selected?.task;
  return <div className="week7-page" dir={rtl ? "rtl" : "ltr"}>
    <PageIntro title="Findings & work console" arabicTitle="لوحة الملاحظات والمهام" description="Every consequential authority issue is preserved as source evidence, owned work, SLA, and notification." />
    <div className="week7-toolbar"><div className="week45-actions"><button className="button-secondary" onClick={() => setLocale(rtl ? "en" : "ar-EG")}>{rtl ? "English layout" : "العربية · RTL"}</button><button className="button-secondary" onClick={() => load()}>Refresh</button></div><span className="synthetic-note week7-note">DEMONSTRATION BASELINE · SYNTHETIC DATA · NO AUTHORITY POLLING</span></div>
    {message && <div className="inline-message">{message}</div>}
    <div className="metric-grid"><div className="metric red"><span>Open findings / الملاحظات المفتوحة</span><strong>{openCount}</strong><small>Blocking work remains visible</small></div><div className="metric teal"><span>My tasks / مهامي</span><strong>{tasks.length}</strong><small>PermitOps-owned durable tasks</small></div><div className="metric orange"><span>Notifications / الإشعارات</span><strong>{notifications.length}</strong><small>{notifications.filter(n => n.status === "FAILED").length} failed · retry available</small></div><div className="metric blue"><span>Safety / السلامة</span><strong>NO CLOSE</strong><small>No unrestricted finding closure</small></div></div>
    <div className="week7-layout"><section className="panel week7-list"><div className="panel-head"><div><span className="eyebrow">FINDINGS LIST · قائمة الملاحظات</span><h3>Visible consequential work</h3></div><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All</option><option value="OPEN">Open / مفتوح</option><option value="BLOCKING">Blocking / مانع</option><option value="OVERDUE">Overdue</option><option value="AUTHORITY_PRECHECK">Authority precheck</option><option value="OFFICIAL_MUNICIPALITY_COMMENT">Official comment</option><option value="PORTAL_VALIDATION">Portal validation</option><option value="UNASSIGNED">Unassigned</option></select></div>{findings.map(f => <button className={`week7-finding-row ${selected?.id === f.id ? "selected" : ""}`} key={f.id} onClick={() => api<any>(`/api/findings/${f.id}`).then(setSelected)}><div className="finding-severity">{f.severity === "BLOCKING" ? "!" : "•"}</div><div className="finding-main"><b>{f.title}</b><small><span className="ltr-id">{f.id.slice(0, 12)}…</span> · {f.source_type} · {f.finding_code?.code || "UNKNOWN_REVIEW"}</small><small>{f.project_id.slice(0, 10)}… · {f.discipline} · {f.owner?.display_name || f.assignee_role || "UNASSIGNED"}</small></div><div className="finding-side">{badge(f.severity)}{badge(f.sla_state)}{badge(f.status)}</div></button>)}{!findings.length && <p className="muted">No findings match this filter.</p>}</section>
      <section className="panel week7-detail"><div className="panel-head"><div><span className="eyebrow">FINDING DETAIL · تفاصيل الملاحظة</span><h3>{selected?.title || "Select a finding"}</h3></div>{selected && badge(selected.source_type)}</div>{selected ? <><div className="week7-detail-grid"><div><b>Raw source / المصدر الخام</b><p className="raw-evidence">{selected.raw_text}</p><small>Language / اللغة: {selected.language} · Evidence / الدليل: <span className="ltr-id">{selected.evidence_artifact_id || "—"}</span></small></div><div><b>Classification / التصنيف</b><p>{selected.finding_code?.code || "UNKNOWN_REVIEW"} · {selected.discipline}</p><p>{badge(selected.severity)} {selected.blocking ? "Blocking / مانع" : "Non-blocking"}</p><small>Requirement: {selected.requirement_code || "—"} · Object: {selected.affected_object_id || "—"}</small></div></div><div className="week7-detail-grid"><div><b>Owner / المسؤول</b><p>{selected.owner?.display_name || selected.assignee_role || "UNASSIGNED / غير مسند"}</p><small>Due / الاستحقاق: {selected.due_at ? new Date(selected.due_at).toLocaleString() : "—"} · SLA: {selected.sla_state}</small></div><div><b>Task / المهمة</b><p>{selectedTask ? `${selectedTask.title} · ${label(selectedTask.status)}` : "No task"}</p><small>{selectedTask?.owner_role || "—"} · {selectedTask?.id ? <span className="ltr-id">{selectedTask.id}</span> : "—"}</small></div></div><div className="week7-actions"><button className="button-secondary" disabled={!selectedTask} onClick={() => act(`/api/tasks/${selectedTask.id}/acknowledge`, { method: "POST" }, "Task acknowledged / تم إسناد المهمة")}>Acknowledge / إقرار</button><button className="button-secondary" disabled={!selectedTask} onClick={() => act(`/api/tasks/${selectedTask.id}/start`, { method: "POST" }, "Task started / بدأت المعالجة")}>Start work / بدء العمل</button><button className="button-secondary" onClick={() => act(`/api/findings/${selected.id}/dispute`, { method: "POST", body: JSON.stringify({ reason: "Operator review" }) }, "Disputed / محل اعتراض")}>Dispute / اعتراض</button><button className="button-secondary" onClick={() => act(`/api/findings/${selected.id}/note`, { method: "POST", body: JSON.stringify({ note: "Synthetic operator note" }) }, "Note added / تمت إضافة ملاحظة")}>Add note / إضافة ملاحظة</button></div><h4>Notification history / سجل الإشعارات</h4>{(selected.notifications || []).map((n: any) => <div className="operator-row" key={n.id}><div><b>{n.channel} · {n.event_type}</b><small><span className="ltr-id">{n.id}</span></small></div>{badge(n.status)}{n.status === "FAILED" && <button className="button-secondary" onClick={() => act(`/api/notifications/${n.id}/retry`, { method: "POST" }, "Retried / تمت إعادة المحاولة")}>Retry / إعادة</button>}</div>)}</> : <p className="muted">Choose a finding to inspect raw evidence, source lineage, owner, task, SLA, notification history, and audit timeline.</p>}</section></div>
    <div className="two-col week7-bottom"><section className="panel"><div className="panel-head"><div><span className="eyebrow">MY TASKS · مهامي</span><h3>PermitOps-owned work</h3></div></div>{tasks.slice(0, 8).map(t => <div className="operator-row" key={t.id}><div><b>{t.title}</b><small>{t.owner_role} · <span className="ltr-id">{t.finding?.id?.slice(0, 12)}…</span></small></div>{badge(t.status)}{badge(t.sla_state)}</div>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">NOTIFICATION OUTBOX · صندوق الإشعارات</span><h3>Delivery evidence</h3></div></div>{notifications.slice(0, 8).map(n => <div className="operator-row" key={n.id}><div><b>{n.channel} · {n.subject}</b><small><span className="ltr-id">{n.finding_id.slice(0, 12)}…</span></small></div>{badge(n.status)}{n.status === "FAILED" && <button className="button-secondary" onClick={() => act(`/api/notifications/${n.id}/retry`, { method: "POST" }, "Retried")}>Retry</button>}</div>)}</section></div>
  </div>;
}

function PageIntro({ title, arabicTitle, description }: { title: string; arabicTitle: string; description: string }) { return <div className="page-intro"><div><span className="eyebrow">WEEK 7 · FINDING / TASK / NOTIFICATION CORE</span><h2>{title}</h2><h3 className="arabic-title">{arabicTitle}</h3><p>{description}</p></div></div>; }
