"""Add construction and post-approval execution controls with frozen historical DDL."""

import sqlalchemy as sa
from alembic import op

revision = "0050_construction_post_approval_controls"
down_revision = "0049_billing_v2_communication_due_events"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # HISTORICAL_MIGRATION_REPAIR_EXCEPTION: this migration must describe the
    # 0050-era schema, not whatever the current ORM happens to contain.
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_executions (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tcontract_id VARCHAR(36), \n\tcontract_revision_id VARCHAR(36), \n\tauthority_case_id VARCHAR(36), \n\texecution_ref VARCHAR(120) NOT NULL, \n\ttitle VARCHAR(240) NOT NULL, \n\tscope_description TEXT, \n\tstatus VARCHAR(40) NOT NULL, \n\twork_state VARCHAR(40) NOT NULL, \n\tcurrent_authority_snapshot_id VARCHAR(36), \n\tcurrent_design_snapshot_id VARCHAR(36), \n\tcreated_by VARCHAR(200) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_execution_ref UNIQUE (project_id, execution_ref), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(contract_id) REFERENCES contracts (id), \n\tFOREIGN KEY(contract_revision_id) REFERENCES contract_revisions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_project_id ON construction_executions (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_current_design_snapshot_id ON construction_executions (current_design_snapshot_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_authority_case_id ON construction_executions (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_current_authority_snapshot_id ON construction_executions (current_authority_snapshot_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_contract_id ON construction_executions (contract_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_executions_contract_revision_id ON construction_executions (contract_revision_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_execution_project_status ON construction_executions (project_id, status, work_state)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS authority_approved_design_snapshots (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tauthority_outcome_id VARCHAR(36), \n\tsubmission_cycle_id VARCHAR(36), \n\texternal_submission_snapshot_id VARCHAR(36), \n\tsubmission_package_id VARCHAR(36), \n\tpreparation_revision_id VARCHAR(36), \n\tapproved_design_baseline_id VARCHAR(36) NOT NULL, \n\tauthority_decision_reference VARCHAR(240), \n\texternal_approval_reference VARCHAR(240), \n\tauthority_state VARCHAR(40) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\teffective_from DATE, \n\teffective_until DATE, \n\tsource_document_version_ids JSON NOT NULL, \n\tbaseline_member_snapshot JSON NOT NULL, \n\tsource_lineage_json JSON NOT NULL, \n\tsnapshot_hash VARCHAR(64) NOT NULL, \n\tcaptured_by VARCHAR(200) NOT NULL, \n\tcaptured_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(authority_outcome_id) REFERENCES authority_outcomes (id), \n\tFOREIGN KEY(submission_cycle_id) REFERENCES authority_submission_cycles (id), \n\tFOREIGN KEY(external_submission_snapshot_id) REFERENCES external_submission_snapshots (id), \n\tFOREIGN KEY(submission_package_id) REFERENCES submission_packages (id), \n\tFOREIGN KEY(preparation_revision_id) REFERENCES preparation_revisions (id), \n\tFOREIGN KEY(approved_design_baseline_id) REFERENCES approved_design_baselines (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_preparation_revision_id ON authority_approved_design_snapshots (preparation_revision_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_external_submiss_16f8 ON authority_approved_design_snapshots (external_submission_snapshot_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_submission_package_id ON authority_approved_design_snapshots (submission_package_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_snapshot_execution ON authority_approved_design_snapshots (construction_execution_id, status)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_project_id ON authority_approved_design_snapshots (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_authority_outcome_id ON authority_approved_design_snapshots (authority_outcome_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_submission_cycle_id ON authority_approved_design_snapshots (submission_cycle_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_approved_design__f6b5 ON authority_approved_design_snapshots (approved_design_baseline_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_construction_exe_0f48 ON authority_approved_design_snapshots (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_authority_approved_design_snapshots_authority_case_id ON authority_approved_design_snapshots (authority_case_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_design_snapshots (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tauthority_approved_design_snapshot_id VARCHAR(36) NOT NULL, \n\tapproved_design_baseline_id VARCHAR(36) NOT NULL, \n\tversion_number INTEGER NOT NULL, \n\tsnapshot_ref VARCHAR(120) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tmember_revision_ids JSON NOT NULL, \n\tmember_rendition_ids JSON NOT NULL, \n\tdocument_version_ids JSON NOT NULL, \n\tsnapshot_hash VARCHAR(64) NOT NULL, \n\tsupersedes_id VARCHAR(36), \n\tpromoted_by VARCHAR(200) NOT NULL, \n\tpromoted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_design_snapshot_version UNIQUE (construction_execution_id, version_number), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_approved_design_snapshot_id) REFERENCES authority_approved_design_snapshots (id), \n\tFOREIGN KEY(approved_design_baseline_id) REFERENCES approved_design_baselines (id), \n\tFOREIGN KEY(supersedes_id) REFERENCES construction_design_snapshots (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_design_snapshots_construction_execution_id ON construction_design_snapshots (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_design_snapshots_project_id ON construction_design_snapshots (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_design_snapshot_execution ON construction_design_snapshots (construction_execution_id, status)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_start_readiness (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tresult VARCHAR(40) NOT NULL, \n\tblockers_json JSON NOT NULL, \n\tchecks_json JSON NOT NULL, \n\tevaluation_fingerprint VARCHAR(64) NOT NULL, \n\tevaluated_by VARCHAR(200) NOT NULL, \n\tevaluated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_readiness_execution ON construction_start_readiness (construction_execution_id, evaluated_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_readiness_construction_execution_id ON construction_start_readiness (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_readiness_project_id ON construction_start_readiness (project_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_start_authorizations (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tproject_activation_id VARCHAR(36) NOT NULL, \n\tcontract_revision_id VARCHAR(36) NOT NULL, \n\tauthority_approved_design_snapshot_id VARCHAR(36) NOT NULL, \n\tconstruction_design_snapshot_id VARCHAR(36) NOT NULL, \n\tstatus VARCHAR(40) NOT NULL, \n\tintended_start_date DATE, \n\treadiness_snapshot JSON NOT NULL, \n\tparty_snapshot JSON NOT NULL, \n\tauthorization_snapshot JSON NOT NULL, \n\treason TEXT NOT NULL, \n\tidempotency_key VARCHAR(200) NOT NULL, \n\tauthorized_by VARCHAR(200) NOT NULL, \n\tauthorized_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_start_authorization_idempotency UNIQUE (idempotency_key), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(project_activation_id) REFERENCES project_activations (id), \n\tFOREIGN KEY(contract_revision_id) REFERENCES contract_revisions (id), \n\tFOREIGN KEY(authority_approved_design_snapshot_id) REFERENCES authority_approved_design_snapshots (id), \n\tFOREIGN KEY(construction_design_snapshot_id) REFERENCES construction_design_snapshots (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_authorization_execution ON construction_start_authorizations (construction_execution_id, status)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_authorizations_construction_execution_id ON construction_start_authorizations (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_start_authorizations_project_id ON construction_start_authorizations (project_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_party_assignments (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tparty_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tparty_role_assignment_id VARCHAR(36), \n\tprofessional_credential_id VARCHAR(36), \n\trole_code VARCHAR(80) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tvalid_from DATE, \n\tvalid_until DATE, \n\tsource_document_version_id VARCHAR(36), \n\tcredential_snapshot JSON NOT NULL, \n\tassigned_by VARCHAR(200) NOT NULL, \n\tassigned_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(party_id) REFERENCES parties (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(party_role_assignment_id) REFERENCES party_role_assignments (id), \n\tFOREIGN KEY(professional_credential_id) REFERENCES professional_credentials (id), \n\tFOREIGN KEY(source_document_version_id) REFERENCES document_versions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_construction_execution_id ON construction_party_assignments (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_source_document_version_id ON construction_party_assignments (source_document_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_project_id ON construction_party_assignments (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_party_role_assignment_id ON construction_party_assignments (party_role_assignment_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_professional_credential_id ON construction_party_assignments (professional_credential_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_party_id ON construction_party_assignments (party_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignments_authority_case_id ON construction_party_assignments (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_party_assignment_execution ON construction_party_assignments (construction_execution_id, role_code, status)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_obligation_definitions (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\trequirement_definition_id VARCHAR(36), \n\tpolicy_version_id VARCHAR(36), \n\tcode VARCHAR(120) NOT NULL, \n\tversion VARCHAR(40) NOT NULL, \n\ttitle VARCHAR(240) NOT NULL, \n\tdescription TEXT NOT NULL, \n\ttrigger_type VARCHAR(60) NOT NULL, \n\tsource_document_version_id VARCHAR(36), \n\trequired_role_codes JSON NOT NULL, \n\tdue_rule_json JSON NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tcreated_by VARCHAR(200) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_obligation_definition UNIQUE (project_id, code, version), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(requirement_definition_id) REFERENCES requirement_definitions (id), \n\tFOREIGN KEY(policy_version_id) REFERENCES requirement_policy_versions (id), \n\tFOREIGN KEY(source_document_version_id) REFERENCES document_versions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_definitions_requirement_defi_935b ON construction_obligation_definitions (requirement_definition_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_definitions_project_id ON construction_obligation_definitions (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_definitions_policy_version_id ON construction_obligation_definitions (policy_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_definitions_source_document__a0f6 ON construction_obligation_definitions (source_document_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_definitions_authority_case_id ON construction_obligation_definitions (authority_case_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_obligation_instances (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tdefinition_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tstatus VARCHAR(40) NOT NULL, \n\ttrigger_event_type VARCHAR(60), \n\ttrigger_event_id VARCHAR(36), \n\tdue_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tcompletion_evidence_document_version_ids JSON NOT NULL, \n\tinstance_snapshot JSON NOT NULL, \n\tcreated_by VARCHAR(200) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(definition_id) REFERENCES construction_obligation_definitions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_instance_execution ON construction_obligation_instances (construction_execution_id, status, due_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_instances_project_id ON construction_obligation_instances (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_instances_due_at ON construction_obligation_instances (due_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_instances_authority_case_id ON construction_obligation_instances (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_instances_construction_execution_id ON construction_obligation_instances (construction_execution_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_obligation_participants (\n\tid VARCHAR(36) NOT NULL, \n\tobligation_instance_id VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tparty_id VARCHAR(36) NOT NULL, \n\trole_code VARCHAR(80) NOT NULL, \n\tresponsibility TEXT, \n\tstatus VARCHAR(30) NOT NULL, \n\tassigned_by VARCHAR(200) NOT NULL, \n\tassigned_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_obligation_participant UNIQUE (obligation_instance_id, party_id, role_code), \n\tFOREIGN KEY(obligation_instance_id) REFERENCES construction_obligation_instances (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(party_id) REFERENCES parties (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_participants_party_id ON construction_obligation_participants (party_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_participants_project_id ON construction_obligation_participants (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_obligation_participants_obligation_instance_id ON construction_obligation_participants (obligation_instance_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_work_control_events (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tstart_authorization_id VARCHAR(36), \n\tevent_type VARCHAR(30) NOT NULL, \n\tprior_state VARCHAR(40) NOT NULL, \n\tnew_state VARCHAR(40) NOT NULL, \n\tevent_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_type VARCHAR(80) NOT NULL, \n\tsource_id VARCHAR(160), \n\tevidence_document_version_id VARCHAR(36), \n\tnotes TEXT, \n\tidempotency_key VARCHAR(200) NOT NULL, \n\trecorded_by VARCHAR(200) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_work_control_event_idempotency UNIQUE (idempotency_key), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(start_authorization_id) REFERENCES construction_start_authorizations (id), \n\tFOREIGN KEY(evidence_document_version_id) REFERENCES document_versions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_work_control_events_construction_execution_id ON construction_work_control_events (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_work_control_events_project_id ON construction_work_control_events (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_work_control_event_execution ON construction_work_control_events (construction_execution_id, event_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_work_control_events_start_authorization_id ON construction_work_control_events (start_authorization_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_work_control_events_evidence_document_v_72df ON construction_work_control_events (evidence_document_version_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_authority_notifications (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tobligation_instance_id VARCHAR(36), \n\twork_control_event_id VARCHAR(36), \n\tnotification_type VARCHAR(80) NOT NULL, \n\tstatus VARCHAR(40) NOT NULL, \n\tchannel_code VARCHAR(60) NOT NULL, \n\trecipient_snapshot JSON NOT NULL, \n\tpayload_snapshot JSON NOT NULL, \n\texternal_reference VARCHAR(240), \n\tevidence_document_version_id VARCHAR(36), \n\tprepared_by VARCHAR(200) NOT NULL, \n\tprepared_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsent_by VARCHAR(200), \n\tsent_at TIMESTAMP WITH TIME ZONE, \n\tacknowledged_at TIMESTAMP WITH TIME ZONE, \n\tidempotency_key VARCHAR(200) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_construction_authority_notification_idempotency UNIQUE (idempotency_key), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(obligation_instance_id) REFERENCES construction_obligation_instances (id), \n\tFOREIGN KEY(work_control_event_id) REFERENCES construction_work_control_events (id), \n\tFOREIGN KEY(evidence_document_version_id) REFERENCES document_versions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_project_id ON construction_authority_notifications (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_work_control_event_id ON construction_authority_notifications (work_control_event_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_evidence_docume_72b8 ON construction_authority_notifications (evidence_document_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_authority_case_id ON construction_authority_notifications (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_obligation_instance_id ON construction_authority_notifications (obligation_instance_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notification_execution ON construction_authority_notifications (construction_execution_id, status)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_authority_notifications_construction_ex_91d8 ON construction_authority_notifications (construction_execution_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_correspondence (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tdirection VARCHAR(20) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tsender_party_id VARCHAR(36), \n\trecipient_party_id VARCHAR(36), \n\tsubject VARCHAR(300) NOT NULL, \n\treference VARCHAR(160), \n\tdocument_version_id VARCHAR(36), \n\texternal_reference VARCHAR(240), \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trecorded_by VARCHAR(200) NOT NULL, \n\tnotes TEXT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(sender_party_id) REFERENCES parties (id), \n\tFOREIGN KEY(recipient_party_id) REFERENCES parties (id), \n\tFOREIGN KEY(document_version_id) REFERENCES document_versions (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_correspondence_execution ON construction_correspondence (construction_execution_id, status, occurred_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_correspondence_project_id ON construction_correspondence (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_correspondence_authority_case_id ON construction_correspondence (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_correspondence_document_version_id ON construction_correspondence (document_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_correspondence_construction_execution_id ON construction_correspondence (construction_execution_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_inspections (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tauthority_case_id VARCHAR(36), \n\tinspection_kind VARCHAR(30) NOT NULL, \n\tstatus VARCHAR(40) NOT NULL, \n\trequested_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tscheduled_at TIMESTAMP WITH TIME ZONE, \n\toccurred_at TIMESTAMP WITH TIME ZONE, \n\tinspector_party_id VARCHAR(36), \n\tauthority_reference VARCHAR(240), \n\toutcome VARCHAR(40), \n\tfindings_json JSON NOT NULL, \n\tevidence_document_version_ids JSON NOT NULL, \n\trecorded_by VARCHAR(200) NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_case_id) REFERENCES authority_cases (id), \n\tFOREIGN KEY(inspector_party_id) REFERENCES parties (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_inspection_execution ON construction_inspections (construction_execution_id, inspection_kind, status)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_inspections_construction_execution_id ON construction_inspections (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_inspections_authority_case_id ON construction_inspections (authority_case_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_inspections_project_id ON construction_inspections (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_inspections_inspector_party_id ON construction_inspections (inspector_party_id)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_issues (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tissue_ref VARCHAR(120) NOT NULL, \n\tcategory VARCHAR(80) NOT NULL, \n\tseverity VARCHAR(30) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tdescription TEXT NOT NULL, \n\taffected_scope VARCHAR(240), \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tobserved_by VARCHAR(200) NOT NULL, \n\tauthority_case_finding_id VARCHAR(36), \n\tdesign_change_request_id VARCHAR(36), \n\trequirement_instance_id VARCHAR(36), \n\tevidence_document_version_ids JSON NOT NULL, \n\tresolution_notes TEXT, \n\tresolved_by VARCHAR(200), \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(authority_case_finding_id) REFERENCES authority_case_findings (id), \n\tFOREIGN KEY(design_change_request_id) REFERENCES design_change_requests (id), \n\tFOREIGN KEY(requirement_instance_id) REFERENCES requirement_instances (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issues_design_change_request_id ON construction_issues (design_change_request_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issues_requirement_instance_id ON construction_issues (requirement_instance_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issues_construction_execution_id ON construction_issues (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issues_authority_case_finding_id ON construction_issues (authority_case_finding_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issues_project_id ON construction_issues (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_issue_execution ON construction_issues (construction_execution_id, status, severity)'))
    op.execute(sa.text('CREATE TABLE IF NOT EXISTS construction_evidence_links (\n\tid VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tconstruction_execution_id VARCHAR(36) NOT NULL, \n\tevidence_type VARCHAR(60) NOT NULL, \n\tdocument_version_id VARCHAR(36), \n\tphysical_evidence_item_id VARCHAR(36), \n\tmaterial_test_id VARCHAR(36), \n\tdescription TEXT NOT NULL, \n\tcaptured_by VARCHAR(200) NOT NULL, \n\tcaptured_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tmetadata_json JSON NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id), \n\tFOREIGN KEY(construction_execution_id) REFERENCES construction_executions (id), \n\tFOREIGN KEY(document_version_id) REFERENCES document_versions (id), \n\tFOREIGN KEY(physical_evidence_item_id) REFERENCES physical_evidence_items (id), \n\tFOREIGN KEY(material_test_id) REFERENCES engineering_material_tests (id)\n)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_links_document_version_id ON construction_evidence_links (document_version_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_links_physical_evidence_item_id ON construction_evidence_links (physical_evidence_item_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_links_construction_execution_id ON construction_evidence_links (construction_execution_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_link_execution ON construction_evidence_links (construction_execution_id, evidence_type)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_links_project_id ON construction_evidence_links (project_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_construction_evidence_links_material_test_id ON construction_evidence_links (material_test_id)'))
    if op.get_bind().dialect.name == "postgresql":
        for table_name, constraint_name, columns, referred_table in (
            ("construction_executions", "construction_executions_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("authority_approved_design_snapshots", "authority_approved_design_snapshots_submission_cycle_id_fkey", ["submission_cycle_id"], "authority_submission_cycles"),
            ("authority_approved_design_snapshots", "authority_approved_design_sna_external_submission_snapshot_fkey", ["external_submission_snapshot_id"], "external_submission_snapshots"),
            ("authority_approved_design_snapshots", "authority_approved_design_snapshots_authority_outcome_id_fkey", ["authority_outcome_id"], "authority_case_outcomes"),
            ("authority_approved_design_snapshots", "authority_approved_design_snapshots_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("authority_approved_design_snapshots", "authority_approved_design_snapshot_preparation_revision_id_fkey", ["preparation_revision_id"], "preparation_revisions"),
            ("authority_approved_design_snapshots", "authority_approved_design_snapshots_submission_package_id_fkey", ["submission_package_id"], "submission_packages"),
            ("authority_approved_design_snapshots", "authority_approved_design_snap_approved_design_baseline_id_fkey", ["approved_design_baseline_id"], "approved_design_baselines"),
            ("construction_design_snapshots", "construction_design_snapshots_approved_design_baseline_id_fkey", ["approved_design_baseline_id"], "approved_design_baselines"),
            ("construction_issues", "construction_issues_authority_case_finding_id_fkey", ["authority_case_finding_id"], "authority_case_findings"),
            ("construction_issues", "construction_issues_design_change_request_id_fkey", ["design_change_request_id"], "design_change_requests"),
            ("construction_issues", "construction_issues_requirement_instance_id_fkey", ["requirement_instance_id"], "requirement_instances"),
            ("construction_obligation_definitions", "construction_obligation_definitions_policy_version_id_fkey", ["policy_version_id"], "requirement_policy_versions"),
            ("construction_obligation_definitions", "construction_obligation_definiti_requirement_definition_id_fkey", ["requirement_definition_id"], "requirement_definitions"),
            ("construction_obligation_definitions", "construction_obligation_definitions_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_obligation_instances", "construction_obligation_instances_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_party_assignments", "construction_party_assignments_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_party_assignments", "construction_party_assignments_professional_credential_id_fkey", ["professional_credential_id"], "professional_credentials"),
            ("construction_party_assignments", "construction_party_assignments_party_id_fkey", ["party_id"], "parties"),
            ("construction_authority_notifications", "construction_authority_notifications_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_correspondence", "construction_correspondence_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_correspondence", "construction_correspondence_sender_party_id_fkey", ["sender_party_id"], "parties"),
            ("construction_correspondence", "construction_correspondence_recipient_party_id_fkey", ["recipient_party_id"], "parties"),
            ("construction_inspections", "construction_inspections_authority_case_id_fkey", ["authority_case_id"], "authority_cases"),
            ("construction_inspections", "construction_inspections_inspector_party_id_fkey", ["inspector_party_id"], "parties"),
            ("construction_obligation_participants", "construction_obligation_participants_party_id_fkey", ["party_id"], "parties"),
            ("construction_evidence_links", "construction_evidence_links_physical_evidence_item_id_fkey", ["physical_evidence_item_id"], "physical_evidence_items"),
            ("construction_evidence_links", "construction_evidence_links_material_test_id_fkey", ["material_test_id"], "engineering_material_tests"),
        ):
            exists = op.get_bind().execute(sa.text(
                "SELECT 1 FROM pg_constraint WHERE conname = :constraint_name"
            ), {"constraint_name": constraint_name}).scalar()
            if not exists:
                op.create_foreign_key(
                    constraint_name, table_name, referred_table, columns, ["id"]
                )


def downgrade() -> None:
    # Construction evidence is an audit boundary; retain the table while
    # removing every 0050-owned dependency on 0044 tables first.
    for table_name, constraint_name in (
        ("construction_executions", "construction_executions_authority_case_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snapshots_submission_cycle_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_sna_external_submission_snapshot_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snapshots_authority_outcome_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snapshots_authority_case_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snapshot_preparation_revision_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snapshots_submission_package_id_fkey"),
        ("authority_approved_design_snapshots", "authority_approved_design_snap_approved_design_baseline_id_fkey"),
        ("construction_design_snapshots", "construction_design_snapshots_approved_design_baseline_id_fkey"),
        ("construction_issues", "construction_issues_authority_case_finding_id_fkey"),
        ("construction_issues", "construction_issues_design_change_request_id_fkey"),
        ("construction_issues", "construction_issues_requirement_instance_id_fkey"),
        ("construction_obligation_definitions", "construction_obligation_definitions_policy_version_id_fkey"),
        ("construction_obligation_definitions", "construction_obligation_definiti_requirement_definition_id_fkey"),
        ("construction_obligation_definitions", "construction_obligation_definitions_authority_case_id_fkey"),
        ("construction_obligation_instances", "construction_obligation_instances_authority_case_id_fkey"),
        ("construction_party_assignments", "construction_party_assignments_authority_case_id_fkey"),
        ("construction_party_assignments", "construction_party_assignments_professional_credential_id_fkey"),
        ("construction_party_assignments", "construction_party_assignments_party_id_fkey"),
        ("construction_authority_notifications", "construction_authority_notifications_authority_case_id_fkey"),
        ("construction_correspondence", "construction_correspondence_authority_case_id_fkey"),
        ("construction_correspondence", "construction_correspondence_sender_party_id_fkey"),
        ("construction_correspondence", "construction_correspondence_recipient_party_id_fkey"),
        ("construction_inspections", "construction_inspections_authority_case_id_fkey"),
        ("construction_inspections", "construction_inspections_inspector_party_id_fkey"),
        ("construction_obligation_participants", "construction_obligation_participants_party_id_fkey"),
        ("construction_evidence_links", "construction_evidence_links_physical_evidence_item_id_fkey"),
        ("construction_evidence_links", "construction_evidence_links_material_test_id_fkey"),
    ):
        op.execute(sa.text(
            f"ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}"
        ))
